const g67 = {

    0: [ // January
      {
        id: "g67-jan-s1",
        topic: "Formal and informal greetings",
        fecha: "26 jan – 1 feb",
        vocab: [
          // Categoría A — Formal (purple)
          { topic:"Formal and informal greetings", cat:"A", catLabel:"Formal", emoji:"🤝", en:"Good morning", es:"Good morning" },
          { topic:"Formal and informal greetings", cat:"A", catLabel:"Formal", emoji:"🤝", en:"Good afternoon", es:"Good afternoon" },
          { topic:"Formal and informal greetings", cat:"A", catLabel:"Formal", emoji:"🤝", en:"Good evening", es:"Good evening" },
          { topic:"Formal and informal greetings", cat:"A", catLabel:"Formal", emoji:"🤝", en:"How do you do?", es:"How do you do?" },
          { topic:"Formal and informal greetings", cat:"A", catLabel:"Formal", emoji:"🤝", en:"Nice to meet you", es:"Nice to meet you" },
          { topic:"Formal and informal greetings", cat:"A", catLabel:"Formal", emoji:"🤝", en:"Pleased to meet you", es:"Pleased to meet you" },
          { topic:"Formal and informal greetings", cat:"A", catLabel:"Formal", emoji:"🤝", en:"Good bye", es:"Good bye" },
          // Categoría B — Informal (orange)
          { topic:"Formal and informal greetings", cat:"B", catLabel:"Informal", emoji:"👋", en:"Hi!", es:"Hi!" },
          { topic:"Formal and informal greetings", cat:"B", catLabel:"Informal", emoji:"👋", en:"Hey!", es:"Hey!" },
          { topic:"Formal and informal greetings", cat:"B", catLabel:"Informal", emoji:"👋", en:"What's up?", es:"What's up?" },
          { topic:"Formal and informal greetings", cat:"B", catLabel:"Informal", emoji:"👋", en:"How are you?", es:"How are you?" },
          { topic:"Formal and informal greetings", cat:"B", catLabel:"Informal", emoji:"👋", en:"How's it going?", es:"How's it going?" },
          { topic:"Formal and informal greetings", cat:"B", catLabel:"Informal", emoji:"👋", en:"See you later!", es:"See you later!" },
          { topic:"Formal and informal greetings", cat:"B", catLabel:"Informal", emoji:"👋", en:"Take care!", es:"Take care!" },
          { topic:"Formal and informal greetings", cat:"B", catLabel:"Informal", emoji:"👋", en:"Catch you later!", es:"Catch you later!" },
        ],
        games: ["pandyMemory","snapCards","quizMultiple"],
        presentation: [{"objective":"Learn formal and informal greetings for different situations and contexts.","rewards":[{"emoji":"⭐","title":"+100 XP"},{"emoji":"🏆","title":"Weekly Badge"},{"emoji":"🎯","title":"New Achievement"}],"tips":["Practice greeting family with 'Good morning'","Use 'Hi!' and 'Hey!' with friends","Memorize both formal and informal forms"]}],
        resources: [
          { title: "ESL Games World — Greetings", desc: "Interactive games de saludos en inglés", url: "https://www.eslgamesworld.com/members/games/vocabulary/greetings/" },
          { title: "British Council — Greetings video", desc: "Short video with formal and informal greetings", url: "https://learnenglishkids.britishcouncil.org/" },
          { title: "Wordwall — Greetings", desc: "Ready-made templates for review activities", url: "https://wordwall.net/" },
        ],
      },
    ],
    1: [ // February
      {
        id:"g67-feb-s2", topic:"Alphabet (spelling), Cardinal and ordinal number", fecha:"2 – 8 feb",
        vocab:[
          // Categoría A — Números ordinales (purple)
          { topic:"Alphabet, spelling y números", cat:"A", catLabel:"Ordinal", emoji:"🏆", en:"First", es:"First" },
          { topic:"Alphabet, spelling y números", cat:"A", catLabel:"Ordinal", emoji:"🥈", en:"Second", es:"Second" },
          { topic:"Alphabet, spelling y números", cat:"A", catLabel:"Ordinal", emoji:"🥉", en:"Third", es:"Third" },
          { topic:"Alphabet, spelling y números", cat:"A", catLabel:"Ordinal", emoji:"🏅", en:"Fourth", es:"Fourth" },
          { topic:"Alphabet, spelling y números", cat:"A", catLabel:"Ordinal", emoji:"🏅", en:"Fifth", es:"Fifth" },
          { topic:"Alphabet, spelling y números", cat:"A", catLabel:"Ordinal", emoji:"🏅", en:"Sixth", es:"Sixth" },
          { topic:"Alphabet, spelling y números", cat:"A", catLabel:"Ordinal", emoji:"🏅", en:"Tenth", es:"Tenth" },
          { topic:"Alphabet, spelling y números", cat:"A", catLabel:"Ordinal", emoji:"🏅", en:"Twentieth", es:"Twentieth" },
          // Categoría B — Números cardinales y alphabet (orange)
          { topic:"Alphabet, spelling y números", cat:"B", catLabel:"Cardinal Numbers & Alphabet", emoji:"🔢", en:"Eleven", es:"Eleven" },
          { topic:"Alphabet, spelling y números", cat:"B", catLabel:"Cardinal Numbers & Alphabet", emoji:"🔢", en:"Twelve", es:"Twelve" },
          { topic:"Alphabet, spelling y números", cat:"B", catLabel:"Cardinal Numbers & Alphabet", emoji:"🔢", en:"Fifteen", es:"Fifteen" },
          { topic:"Alphabet, spelling y números", cat:"B", catLabel:"Cardinal Numbers & Alphabet", emoji:"🔤", en:"Vowel", es:"Vowel" },
          { topic:"Alphabet, spelling y números", cat:"B", catLabel:"Cardinal Numbers & Alphabet", emoji:"🔤", en:"Consonant", es:"Consonant" },
          { topic:"Alphabet, spelling y números", cat:"B", catLabel:"Cardinal Numbers & Alphabet", emoji:"🔤", en:"Spell it!", es:"Spell it!" },
          { topic:"Alphabet, spelling y números", cat:"B", catLabel:"Cardinal Numbers & Alphabet", emoji:"🔢", en:"Twenty", es:"Twenty" },
        ],
        games: ["pandyMemory","snapCards","quizMultiple"],
        presentation: [{"objective":"Master the alphabet, spelling, and cardinal/ordinal numbers.","rewards":[{"emoji":"⭐","title":"+100 XP"},{"emoji":"🏆","title":"Weekly Badge"},{"emoji":"🎯","title":"New Achievement"}],"tips":["Practice spelling each letter out loud","Learn ordinal numbers 1st through 20th","Count objects to practice cardinal numbers"]}],
        resources:[
          {title:"ABCya — Alphabet Gamonth", desc:"Interactive games del alphabet para primaria", url:"https://www.abcya.com/games/alphabet"},
          {title:"Spelling City — Ordinal Numbers", desc:"Práctica de números ordinales con juegos", url:"https://www.spellingcity.com/ordinal-numbers.html"},
          {title:"Wordwall — Numbers 1–20", desc:"Actividades de números cardinales y ordinales", url:"https://wordwall.net/resource/ordinal-numbers"},
        ],
      },
      {
        id:"g67-feb-s3", topic:"Days of the week and months of the year", fecha:"9 – 15 feb",
vocab:[
          // Category A — Days of the week (purple)
          { topic:"Days of the week and months of the year", cat:"A", catLabel:"Days", emoji:"📅", en:"Monday", es:"Monday" },
          { topic:"Days of the week and months of the year", cat:"A", catLabel:"Days", emoji:"📅", en:"Tuesday", es:"Tuesday" },
          { topic:"Days of the week and months of the year", cat:"A", catLabel:"Days", emoji:"📅", en:"Wednesday", es:"Wednesday" },
          { topic:"Days of the week and months of the year", cat:"A", catLabel:"Days", emoji:"📅", en:"Thursday", es:"Thursday" },
          { topic:"Days of the week and months of the year", cat:"A", catLabel:"Days", emoji:"📅", en:"Friday", es:"Friday" },
          { topic:"Days of the week and months of the year", cat:"A", catLabel:"Days", emoji:"📅", en:"Saturday", es:"Saturday" },
          { topic:"Days of the week and months of the year", cat:"A", catLabel:"Days", emoji:"📅", en:"Sunday", es:"Sunday" },
          // Category B — Months of the year (orange)
          { topic:"Days of the week and months of the year", cat:"B", catLabel:"Months", emoji:"🗓️", en:"January", es:"January" },
          { topic:"Days of the week and months of the year", cat:"B", catLabel:"Months", emoji:"🗓️", en:"February", es:"February" },
          { topic:"Days of the week and months of the year", cat:"B", catLabel:"Months", emoji:"🌸", en:"March", es:"March" },
          { topic:"Days of the week and months of the year", cat:"B", catLabel:"Months", emoji:"🌸", en:"April", es:"April" },
          { topic:"Days of the week and months of the year", cat:"B", catLabel:"Months", emoji:"☀️", en:"June", es:"June" },
          { topic:"Days of the week and months of the year", cat:"B", catLabel:"Months", emoji:"🍂", en:"October", es:"October" },
          { topic:"Days of the week and months of the year", cat:"B", catLabel:"Months", emoji:"❄️", en:"December", es:"December" },
          { topic:"Days of the week and months of the year", cat:"B", catLabel:"Months", emoji:"🗓️", en:"August", es:"August" },
        ],
        games: ["pandyMemory","snapCards","quizMultiple"],
        presentation: [{"objective":"Learn the days of the week and months of the year in English.","rewards":[{"emoji":"⭐","title":"+100 XP"},{"emoji":"🏆","title":"Weekly Badge"},{"emoji":"🎯","title":"New Achievement"}],"tips":["Memorize the 7 days in order","Learn the 12 months and their order","Create sentences like 'My birthday is in January'"]}],
        resources:[
          {title:"British Council — Days of the Week", desc:"Canción y actividades de los días", url:"https://learnenglishkids.britishcouncil.org/songs/days-week"},
          {title:"ESL Game Plus — Months", desc:"Game of months del año en inglés", url:"https://www.eslgamesplus.com/months-of-the-year-esl-vocabulary-interactive-game/"},
          {title:"Quizlet — Days & Months", desc:"Flashcards y test de días y months", url:"https://quizlet.com/subject/days-of-the-week-and-months-of-the-year/"},
        ],
      },
      {
        id:"g67-feb-s4", topic:"Personal pronouns and verbo To Be", fecha:"16 – 22 feb",
       vocab:[
          // Category A — Pronouns + To Be (purple)
          { topic:"Personal pronouns and verb To Be", cat:"A", catLabel:"To Be", emoji:"🙋", en:"I am", es:"Yo soy / estoy" },
          { topic:"Personal pronouns and verb To Be", cat:"A", catLabel:"To Be", emoji:"🙋", en:"You are", es:"Tú eres / estás" },
          { topic:"Personal pronouns and verb To Be", cat:"A", catLabel:"To Be", emoji:"👦", en:"He is", es:"Él es / está" },
          { topic:"Personal pronouns and verb To Be", cat:"A", catLabel:"To Be", emoji:"👧", en:"She is", es:"Ella es / está" },
          { topic:"Personal pronouns and verb To Be", cat:"A", catLabel:"To Be", emoji:"📦", en:"It is", es:"Es / está (para cosas)" },
          { topic:"Personal pronouns and verb To Be", cat:"A", catLabel:"To Be", emoji:"👥", en:"We are", es:"Nosotros somos / estamos" },
          { topic:"Personal pronouns and verb To Be", cat:"A", catLabel:"To Be", emoji:"👥", en:"They are", es:"Ellos son / están" },
          { topic:"Personal pronouns and verb To Be", cat:"A", catLabel:"To Be", emoji:"🙋", en:"You are (pl.)", es:"Ustedes son / están" },
          // Category B — Negations & Questions (orange)
          { topic:"Personal pronouns and verb To Be", cat:"B", catLabel:"Negative & Question", emoji:"❌", en:"I am not", es:"Yo no soy / no estoy" },
          { topic:"Personal pronouns and verb To Be", cat:"B", catLabel:"Negative & Question", emoji:"❌", en:"She is not", es:"Ella no es / no está" },
          { topic:"Personal pronouns and verb To Be", cat:"B", catLabel:"Negative & Question", emoji:"❌", en:"They aren't", es:"Ellos no son / no están" },
          { topic:"Personal pronouns and verb To Be", cat:"B", catLabel:"Negative & Question", emoji:"❓", en:"Am I…?", es:"¿Soy yo…?" },
          { topic:"Personal pronouns and verb To Be", cat:"B", catLabel:"Negative & Question", emoji:"❓", en:"Is she…?", es:"¿Es ella…?" },
          { topic:"Personal pronouns and verb To Be", cat:"B", catLabel:"Negative & Question", emoji:"❓", en:"Are they…?", es:"¿Son ellos…?" },
          { topic:"Personal pronouns and verb To Be", cat:"B", catLabel:"Negative & Question", emoji:"❓", en:"Where are you?", es:"¿Dónde estás?" },
        ],
        games: ["wordRace","snapCards","quizMultiple"],
        presentation: [{"objective":"Use personal pronouns and the verb 'to be' in affirmative, negative, and question sentences.","rewards":[{"emoji":"⭐","title":"+100 XP"},{"emoji":"🏆","title":"Weekly Badge"},{"emoji":"🎯","title":"New Achievement"}],"tips":["Match pronouns to correct 'to be' forms: I am, you are, he is","Practice negations: I am not, she is not","Turn statements into questions: Are they..."]}],
        resources:[
          {title:"British Council — To Be", desc:"Ejercicios del verbo To Be nivel básico", url:"https://learnenglish.britishcouncil.org/grammar/beginner-to-pre-intermediate/verb-be-positive-negative"},
          {title:"ESL Gamonth Plus — Pronouns", desc:"Game of pronombres personales", url:"https://www.eslgamesplus.com/personal-pronouns-grammar-esl-interactive-crocodile-board-game/"},
          {title:"Kahoot — To Be Quiz", desc:"Quiz interactivo del verbo To Be", url:"https://kahoot.com/schools-u/"},
        ],
      },
      {
        id:"g67-feb-s5", topic:"Verbo Have and family vocabulary", fecha:"23 feb – 1 mar",
     vocab:[
          // Category A — Nuclear family (purple)
          { topic:"Verb Have and family vocabulary", cat:"A", catLabel:"Family", emoji:"👨‍👩‍👧", en:"Mother", es:"Madre" },
          { topic:"Verb Have and family vocabulary", cat:"A", catLabel:"Family", emoji:"👨‍👩‍👧", en:"Father", es:"Padre" },
          { topic:"Verb Have and family vocabulary", cat:"A", catLabel:"Family", emoji:"👦",     en:"Brother", es:"Hermano" },
          { topic:"Verb Have and family vocabulary", cat:"A", catLabel:"Family", emoji:"👧",     en:"Sister", es:"Hermana" },
          { topic:"Verb Have and family vocabulary", cat:"A", catLabel:"Family", emoji:"👶",     en:"Baby", es:"Bebé" },
          { topic:"Verb Have and family vocabulary", cat:"A", catLabel:"Family", emoji:"👴",     en:"Grandfather", es:"Abuelo" },
          { topic:"Verb Have and family vocabulary", cat:"A", catLabel:"Family", emoji:"👵",     en:"Grandmother", es:"Abuela" },
          { topic:"Verb Have and family vocabulary", cat:"A", catLabel:"Family", emoji:"👫",     en:"Cousin", es:"Primo/a" },
          // Category B — Verb Have in context (orange)
          { topic:"Verb Have and family vocabulary", cat:"B", catLabel:"Verb Have", emoji:"✋", en:"I have a sister", es:"Yo tengo una hermana" },
          { topic:"Verb Have and family vocabulary", cat:"B", catLabel:"Verb Have", emoji:"✋", en:"She has blue eyes", es:"Ella tiene los ojos azules" },
          { topic:"Verb Have and family vocabulary", cat:"B", catLabel:"Verb Have", emoji:"✋", en:"He has a big family", es:"Él tiene una familia grande" },
          { topic:"Verb Have and family vocabulary", cat:"B", catLabel:"Verb Have", emoji:"✋", en:"We have two brothers", es:"Nosotros tenemos dos hermanos" },
          { topic:"Verb Have and family vocabulary", cat:"B", catLabel:"Verb Have", emoji:"❓", en:"Do you have a pet?", es:"¿Tienes una mascota?" },
          { topic:"Verb Have and family vocabulary", cat:"B", catLabel:"Verb Have", emoji:"❓", en:"Does she have cousins?", es:"¿Ella tiene primos?" },
          { topic:"Verb Have and family vocabulary", cat:"B", catLabel:"Verb Have", emoji:"✋", en:"They have a big house", es:"Ellos tienen una casa grande" },
        ],
        games: ["pandyMemory","snapCards","quizMultiple"],
        presentation: [{"objective":"Use the verb 'have' and learn family vocabulary.","rewards":[{"emoji":"⭐","title":"+100 XP"},{"emoji":"🏆","title":"Weekly Badge"},{"emoji":"🎯","title":"New Achievement"}],"tips":["Practice 'I have', 'you have', 'she has'","Learn family member names in English","Ask 'Do you have...?' and 'Does she have...?'"]}],
        resources:[
          {title:"British Council — Family", desc:"Vocabulary de familia con actividades interactivas", url:"https://learnenglishkids.britishcouncil.org/word-games/family"},
          {title:"ESL Games World — Family", desc:"Juegos de vocabulary de familia en inglés", url:"https://www.eslgamesworld.com/members/games/vocabulary/family/"},
          {title:"Canva — Family Tree Template", desc:"Plantilla digital para árbol genealógico", url:"https://www.canva.com/graphs/family-trees/"},
        ],
      },
    ],
    2: [ // March
      {
        id:"g67-mar-s6", topic:"There is / There are · Sustantivos singular/plural", fecha:"2 – 8 mar",
     vocab:[
          // Category A — There is / There are (purple)
          { topic:"There is / There are · Plurals", cat:"A", catLabel:"There is / There are", emoji:"🏫", en:"There is a board", es:"Hay una pizarra" },
          { topic:"There is / There are · Plurals", cat:"A", catLabel:"There is / There are", emoji:"🏫", en:"There is a door", es:"Hay una puerta" },
          { topic:"There is / There are · Plurals", cat:"A", catLabel:"There is / There are", emoji:"🏫", en:"There is a window", es:"Hay una ventana" },
          { topic:"There is / There are · Plurals", cat:"A", catLabel:"There is / There are", emoji:"📚", en:"There are 30 students", es:"Hay 30 estudiantes" },
          { topic:"There is / There are · Plurals", cat:"A", catLabel:"There is / There are", emoji:"📚", en:"There are many books", es:"Hay muchos libros" },
          { topic:"There is / There are · Plurals", cat:"A", catLabel:"There is / There are", emoji:"📚", en:"There are two chairs", es:"Hay dos sillas" },
          { topic:"There is / There are · Plurals", cat:"A", catLabel:"There is / There are", emoji:"❓", en:"Is there a pencil?", es:"¿Hay un lápiz?" },
          { topic:"There is / There are · Plurals", cat:"A", catLabel:"There is / There are", emoji:"❓", en:"Are there any tables?", es:"¿Hay mesas?" },
          // Category B — Singular / plural nouns (orange)
          { topic:"There is / There are · Plurals", cat:"B", catLabel:"Singular & Plural", emoji:"📖", en:"Book → Books", es:"Libro → Libros" },
          { topic:"There is / There are · Plurals", cat:"B", catLabel:"Singular & Plural", emoji:"🪑", en:"Chair → Chairs", es:"Silla → Sillas" },
          { topic:"There is / There are · Plurals", cat:"B", catLabel:"Singular & Plural", emoji:"✏️", en:"Pencil → Pencils", es:"Lápiz → Lápices" },
          { topic:"There is / There are · Plurals", cat:"B", catLabel:"Singular & Plural", emoji:"👶", en:"Child → Children", es:"Niño → Niños" },
          { topic:"There is / There are · Plurals", cat:"B", catLabel:"Singular & Plural", emoji:"🦷", en:"Tooth → Teeth", es:"Diente → Dientes" },
          { topic:"There is / There are · Plurals", cat:"B", catLabel:"Singular & Plural", emoji:"👤", en:"Person → People", es:"Persona → Personas" },
          { topic:"There is / There are · Plurals", cat:"B", catLabel:"Singular & Plural", emoji:"📦", en:"Box → Boxes", es:"Caja → Cajas" },
        ],
        games: ["wordRace","snapCards","quizMultiple"],
        presentation: [{"objective":"Use 'there is' and 'there are' correctly, and form singular/plural nouns.","rewards":[{"emoji":"⭐","title":"+100 XP"},{"emoji":"🏆","title":"Weekly Badge"},{"emoji":"🎯","title":"New Achievement"}],"tips":["Remember: 'there is' for singular, 'there are' for plural","Add -s or -es for plurals: book -> books","Practice 'Is there...?' and 'Are there...?'"]}],
        resources:[
          {title:"British Council — There is/are", desc:"Ejercicios de there is / there are", url:"https://learnenglish.britishcouncil.org/grammar/beginner-to-pre-intermediate/there-is-there-are"},
          {title:"Wordwall — Classroom Objects", desc:"Juegos de objetos del salón en inglés", url:"https://wordwall.net/resource/classroom-objects"},
          {title:"ESL Kids — Plural Nouns", desc:"Juego of theirstantivos singular y plural", url:"https://www.eslkidsgames.com/plural-nouns"},
        ],
      },
      {
        id:"g67-mar-s7", topic:"Physical appearance adjectives", fecha:"9 – 15 mar",
      vocab:[
          // Category A — Height & Build (purple)
          { topic:"Physical appearance adjectives", cat:"A", catLabel:"Height & Build", emoji:"📏", en:"Tall", es:"Alto/a" },
          { topic:"Physical appearance adjectives", cat:"A", catLabel:"Height & Build", emoji:"📏", en:"Short", es:"Bajo/a" },
          { topic:"Physical appearance adjectives", cat:"A", catLabel:"Height & Build", emoji:"⚖️", en:"Slim / Thin", es:"Delgado/a" },
          { topic:"Physical appearance adjectives", cat:"A", catLabel:"Height & Build", emoji:"⚖️", en:"Heavy-set", es:"Corpulento/a" },
          { topic:"Physical appearance adjectives", cat:"A", catLabel:"Height & Build", emoji:"📏", en:"Medium height", es:"Estatura media" },
          { topic:"Physical appearance adjectives", cat:"A", catLabel:"Height & Build", emoji:"💪", en:"Athletic", es:"Atlético/a" },
          { topic:"Physical appearance adjectives", cat:"A", catLabel:"Height & Build", emoji:"🧓", en:"Elderly", es:"Anciano/a" },
          // Category B — Hair & Eyes (orange)
          { topic:"Physical appearance adjectives", cat:"B", catLabel:"Hair & Eyes", emoji:"💇", en:"Curly hair", es:"Cabello rizado" },
          { topic:"Physical appearance adjectives", cat:"B", catLabel:"Hair & Eyes", emoji:"💇", en:"Straight hair", es:"Cabello lacio" },
          { topic:"Physical appearance adjectives", cat:"B", catLabel:"Hair & Eyes", emoji:"👱", en:"Blonde hair", es:"Cabello rubio" },
          { topic:"Physical appearance adjectives", cat:"B", catLabel:"Hair & Eyes", emoji:"🟤", en:"Brown hair", es:"Cabello castaño" },
          { topic:"Physical appearance adjectives", cat:"B", catLabel:"Hair & Eyes", emoji:"🖤", en:"Dark hair", es:"Cabello oscuro" },
          { topic:"Physical appearance adjectives", cat:"B", catLabel:"Hair & Eyes", emoji:"👁️", en:"Blue eyes", es:"Ojos azules" },
          { topic:"Physical appearance adjectives", cat:"B", catLabel:"Hair & Eyes", emoji:"👁️", en:"Brown eyes", es:"Ojos marrones" },
          { topic:"Physical appearance adjectives", cat:"B", catLabel:"Hair & Eyes", emoji:"🧔", en:"Beard", es:"Barba" },
        ],
        games: ["pandyMemory","snapCards","quizMultiple"],
        presentation: [{"objective":"Describe physical appearance using height, build, hair, and eye vocabulary.","rewards":[{"emoji":"⭐","title":"+100 XP"},{"emoji":"🏆","title":"Weekly Badge"},{"emoji":"🎯","title":"New Achievement"}],"tips":["Learn adjectives: tall, short, slim, heavy-set","Practice 'He has curly hair' and 'She has blue eyes'","Use 'He is tall' and 'She is short'"]}],
        resources:[
          {title:"British Council — Physical Description", desc:"Vocabulary de descripción física con actividades", url:"https://learnenglishkids.britishcouncil.org/word-games/body"},
          {title:"ESL Gamonth Plus — Adjectives", desc:"Game of adjetivos de descripción", url:"https://www.eslgamesplus.com/adjectives-esl-grammar-interactive-crocodile-board-game/"},
          {title:"Canva — Character Poster", desc:"Crea póster de descripción de personaje", url:"https://www.canva.com/posters/"},
        ],
      },
      {
        id:"g67-mar-s8", topic:"First term", fecha:"16 – 22 mar", badge:"Evaluación",
        vocab:[
          // Category A — Grammar period 1 (purple)
          { topic:"Review — First term", cat:"A", catLabel:"Grammar", emoji:"📝", en:"I am a student", es:"Yo soy estudiante" },
          { topic:"Review — First term", cat:"A", catLabel:"Grammar", emoji:"📝", en:"She has long hair", es:"Ella tiene el cabello largo" },
          { topic:"Review — First term", cat:"A", catLabel:"Grammar", emoji:"📝", en:"There is a window", es:"Hay una ventana" },
          { topic:"Review — First term", cat:"A", catLabel:"Grammar", emoji:"📝", en:"There are 3 books", es:"Hay 3 libros" },
          { topic:"Review — First term", cat:"A", catLabel:"Grammar", emoji:"📝", en:"We are from Colombia", es:"Nosotros somos de Colombia" },
          { topic:"Review — First term", cat:"A", catLabel:"Grammar", emoji:"📝", en:"They aren't tall", es:"Ellos no son altos" },
          { topic:"Review — First term", cat:"A", catLabel:"Grammar", emoji:"📝", en:"Do you have a brother?", es:"¿Tienes un hermano?" },
          // Category B — Vocabulary period 1 (orange)
          { topic:"Review — First term", cat:"B", catLabel:"Vocabulary", emoji:"📚", en:"Good morning", es:"Buenos días" },
          { topic:"Review — First term", cat:"B", catLabel:"Vocabulary", emoji:"📚", en:"Wednesday", es:"Miércoles" },
          { topic:"Review — First term", cat:"B", catLabel:"Vocabulary", emoji:"📚", en:"October", es:"Octubre" },
          { topic:"Review — First term", cat:"B", catLabel:"Vocabulary", emoji:"📚", en:"Grandfather", es:"Abuelo" },
          { topic:"Review — First term", cat:"B", catLabel:"Vocabulary", emoji:"📚", en:"Curly hair", es:"Cabello rizado" },
          { topic:"Review — First term", cat:"B", catLabel:"Vocabulary", emoji:"📚", en:"Child → Children", es:"Niño → Niños" },
          { topic:"Review — First term", cat:"B", catLabel:"Vocabulary", emoji:"📚", en:"Third", es:"Tercero" },
          { topic:"Review — First term", cat:"B", catLabel:"Vocabulary", emoji:"📚", en:"Nice to meet you", es:"Mucho gusto" },
        ],
        games: ["finalChallenge","bingo","quizMultiple"],
        presentation: [{"objective":"Review grammar and vocabulary from the first term in a comprehensive challenge.","rewards":[{"emoji":"⭐","title":"+100 XP"},{"emoji":"🏆","title":"Weekly Badge"},{"emoji":"🎯","title":"New Achievement"}],"tips":["Review all verb forms: to be, have, there is/are","Practice singular/plural nouns","Use adjectives from physical descriptions"]}],
        resources:[
          {title:"Kahoot — Review Quiz", desc:"Crea un quiz de repaso del período en Kahoot", url:"https://kahoot.com/schools-u/"},
          {title:"Quizlet — Period 1 Review", desc:"General Review de todos los temas del período", url:"https://quizlet.com/"},
          {title:"Wordwall — Mixed Review", desc:"Actividades mixtas de repaso del primer período", url:"https://wordwall.net/"},
        ],
      },
      {
        id:"g67-mar-s9", topic:"Feedbackback and end-of-term closing", fecha:"23 – 29 mar", badge:"Retroalimentación",
vocab:[
          // Category A — Learning reflection (purple)
          { topic:"Feedback and end-of-term closing", cat:"A", catLabel:"Reflection", emoji:"💡", en:"I learned", es:"Aprendí" },
          { topic:"Feedback and end-of-term closing", cat:"A", catLabel:"Reflection", emoji:"💡", en:"I improved", es:"Mejoré" },
          { topic:"Feedback and end-of-term closing", cat:"A", catLabel:"Reflection", emoji:"💡", en:"My mistake was", es:"Mi error fue" },
          { topic:"Feedback and end-of-term closing", cat:"A", catLabel:"Reflection", emoji:"💡", en:"I need to practice", es:"Necesito practicar" },
          { topic:"Feedback and end-of-term closing", cat:"A", catLabel:"Reflection", emoji:"🏆", en:"My goal is", es:"Mi meta es" },
          { topic:"Feedback and end-of-term closing", cat:"A", catLabel:"Reflection", emoji:"🏆", en:"I can do better", es:"Puedo hacerlo mejor" },
          { topic:"Feedback and end-of-term closing", cat:"A", catLabel:"Reflection", emoji:"🏆", en:"My progress", es:"Mi progreso" },
          // Category B — Closing vocabulary (orange)
          { topic:"Feedback and end-of-term closing", cat:"B", catLabel:"Closing", emoji:"📋", en:"Review", es:"Repaso" },
          { topic:"Feedback and end-of-term closing", cat:"B", catLabel:"Closing", emoji:"📋", en:"Feedback", es:"Retroalimentación" },
          { topic:"Feedback and end-of-term closing", cat:"B", catLabel:"Closing", emoji:"📋", en:"Success", es:"Éxito" },
          { topic:"Feedback and end-of-term closing", cat:"B", catLabel:"Closing", emoji:"📋", en:"Effort", es:"Esfuerzo" },
          { topic:"Feedback and end-of-term closing", cat:"B", catLabel:"Closing", emoji:"📋", en:"Achievement", es:"Logro" },
          { topic:"Feedback and end-of-term closing", cat:"B", catLabel:"Closing", emoji:"🚀", en:"Next period", es:"Próximo período" },
          { topic:"Feedback and end-of-term closing", cat:"B", catLabel:"Closing", emoji:"🚀", en:"Keep going!", es:"¡Sigue así!" },
          { topic:"Feedback and end-of-term closing", cat:"B", catLabel:"Closing", emoji:"🚀", en:"Well done!", es:"¡Bien hecho!" },
        ],
        games: ["finalChallenge","bingo","quizMultiple"],
        presentation: [{"objective":"Reflect on learning progress and set goals for the next term.","rewards":[{"emoji":"⭐","title":"+100 XP"},{"emoji":"🏆","title":"Weekly Badge"},{"emoji":"🎯","title":"New Achievement"}],"tips":["Describe what you learned: 'I learned...'","Set improvement goals: 'I need to practice...'","Acknowledge mistakes and plan next steps"]}],
        resources:[
          {title:"Canva — Mind Map", desc:"Crea un mapa mental del período con Canva", url:"https://www.canva.com/graphs/mind-maps/"},
          {title:"Mentimeter — Live Feedback", desc:"Recoge retroalimentación en time real", url:"https://www.mentimeter.com/"},
          {title:"Google Forms — Self-Assessment", desc:"Crea autoevaluación digital del período", url:"https://forms.google.com/"},
        ],
      },
    ],
    3: [ // April
      {
        id:"g67-apr-s1", topic:"Present simple tense", fecha:"6 – 12 apr",
        vocab:[
          {en:"WAKE UP", es:"DESPERTAR"},
          {en:"EAT", es:"COMER"},
          {en:"STUDY", es:"ESTUDIAR"},
          {en:"PLAY", es:"JUGAR"},
          {en:"SLEEP", es:"DORMIR"},
          {en:"WALK", es:"CAMINAR"},
          {en:"WORK", es:"TRABAJAR"},
          {en:"WATCH", es:"VER"},
        ],
        games: ["wordRace","snapCards","quizMultiple"],
        presentation: [{"objective":"Use the present simple tense to describe daily routines and habits.","rewards":[{"emoji":"⭐","title":"+100 XP"},{"emoji":"🏆","title":"Weekly Badge"},{"emoji":"🎯","title":"New Achievement"}],"tips":["Add -s for he/she/it: he walks, she eats","Use time expressions: always, usually, often","Practice 'I wake up at 7 AM'"]}],
        resources:[
          {title:"British Council — Present Simple", desc:"Explicación y ejercicios del presente simple", url:"https://learnenglish.britishcouncil.org/grammar/beginner-to-pre-intermediate/present-simple"},
          {title:"ESL Gamonth Plus — Simple Present", desc:"Game ofl presente simple afirmativo", url:"https://www.eslgamesplus.com/simple-present-tense-esl-interactive-grammar-activity/"},
          {title:"Wordwall — Daily Routines", desc:"Actividades de rutina diaria en presente simple", url:"https://wordwall.net/resource/daily-routines-present-simple"},
        ],
      },
      {
        id:"g67-apr-s2", topic:" Interrogative and negative present simple tense", fecha:"13 – 19 apr",
        vocab:[
          {en:"DO", es:"HACER"},
          {en:"DOES", es:"HACE"},
          {en:"DON'T", es:"NO HAGO"},
          {en:"DOESN'T", es:"NO HACE"},
          {en:"WHERE", es:"DÓNDE"},
          {en:"WHEN", es:"CUÁNDO"},
          {en:"WHAT", es:"WHAT"},
          {en:"HOW", es:"HOW"},
        ],
        games: ["wordRace","snapCards","quizMultiple"],
        presentation: [{"objective":"Form negative sentences and yes/no questions in the present simple.","rewards":[{"emoji":"⭐","title":"+100 XP"},{"emoji":"🏆","title":"Weekly Badge"},{"emoji":"🎯","title":"New Achievement"}],"tips":["Negatives: 'I do not', 'she does not'","Questions: 'Do you...?', 'Does he...?'","Use 'Where', 'When', 'What', 'How' to start questions"]}],
        resources:[
          {title:"British Council — Present Simple Negative", desc:"Ejercicios de negación en presente simple", url:"https://learnenglish.britishcouncil.org/grammar/beginner-to-pre-intermediate/present-simple-negatives-and-questions"},
          {title:"ESL Gamonth Plus — Do Does Questions", desc:"Game of preguntas con Do y Does", url:"https://www.eslgamesplus.com/"},
          {title:"Kahoot — Do/Does Quiz", desc:"Quiz interactivo de preguntas en presente simple", url:"https://kahoot.com/schools-u/"},
        ],
      },
      {
        id:"g67-apr-s3", topic:"Adverb of frequency and daily routine", fecha:"20 – 26 apr",
       vocab:[
          {en:"ALWAYS", es:"SIEMPRE"},
          {en:"USUALLY", es:"GENERALMENTE"},
          {en:"OFTEN", es:"A MENUDO"},
          {en:"SOMETIMES", es:"A VECES"},
          {en:"RARELY", es:"RARA VEZ"},
          {en:"NEVER", es:"NUNCA"},
          {en:"EVERY DAY", es:"TODOS LOS DÍAS"},
          {en:"ROUTINE", es:"RUTINA"},
        ],
        games: ["pandyMemory","snapCards","quizMultiple"],
        presentation: [{"objective":"Use adverbs of frequency to describe how often you do things.","rewards":[{"emoji":"⭐","title":"+100 XP"},{"emoji":"🏆","title":"Weekly Badge"},{"emoji":"🎯","title":"New Achievement"}],"tips":["Order: always, usually, often, sometimes, never","Practice 'I always wake up early'","Match adverbs to daily routine verbs"]}],
        resources:[
          {title:"British Council — Adverbs of Frequency", desc:"Ejercicios de adverbios de frecuencia", url:"https://learnenglish.britishcouncil.org/grammar/beginner-to-pre-intermediate/adverbs-of-frequency"},
          {title:"ESL Games World — Frequency", desc:"Juegos de adverbios de frecuencia", url:"https://www.eslgamesworld.com/"},
          {title:"Wordwall — Frequency Adverbs", desc:"Actividades de adverbios de frecuencia", url:"https://wordwall.net/resource/adverbs-of-frequency"},
        ],
      },
      {
        id:"g67-apr-s4", topic:"Likes and dislikes — means of transport", fecha:"27 apr – 3 may",
       vocab:[
          {en:"BUS", es:"AUTOBÚS"},
          {en:"CAR", es:"CARRO"},
          {en:"BICYCLE", es:"BICICLETA"},
          {en:"MOTORCYCLE", es:"MOTOCICLETA"},
          {en:"TRAIN", es:"TREN"},
          {en:"PLANE", es:"AVIÓN"},
          {en:"LIKE", es:"GUSTAR"},
          {en:"LOVE", es:"AMAR"},
        ],
        games: ["pandyMemory","snapCards","quizMultiple"],
        presentation: [{"objective":"Express likes, dislikes, and preferences about transport and daily activities.","rewards":[{"emoji":"⭐","title":"+100 XP"},{"emoji":"🏆","title":"Weekly Badge"},{"emoji":"🎯","title":"New Achievement"}],"tips":["Use 'I like', 'I love', 'I don't like'","Practice transport vocabulary: bus, car, bicycle","Ask 'Do you like...?' about transport"]}],
        resources:[
          {title:"British Council — Transport", desc:"Vocabulary de transporte con actividades", url:"https://learnenglishkids.britishcouncil.org/word-games/transport"},
          {title:"ESL Gamonth Plus — Likes & Dislikes", desc:"Game of gustos y preferencias en inglés", url:"https://www.eslgamesplus.com/likes-and-dislikes-esl-grammar-interactive-activity/"},
          {title:"Canva — Activities Poster", desc:"Crea un folleto de actividades favoritas", url:"https://www.canva.com/posters/"},
        ],
      },
    ],
    4: [ // May
      {
        id:"g67-may-s5", topic:"preposition of the place", fecha:"4 – 10 may",
      vocab:[
          {en:"IN", es:"EN / DENTRO DE"},
          {en:"ON", es:"SOBRE / ENCIMA DE"},
          {en:"UNDER", es:"DEBAJO DE"},
          {en:"NEXT TO", es:"AL LADO DE"},
          {en:"BEHIND", es:"DETRÁS DE"},
          {en:"IN FRONT OF", es:"ENFRENTE DE"},
          {en:"BETWEEN", es:"ENTRE"},
          {en:"NEAR", es:"CERCA DE"},
        ],
        games: ["wordRace","snapCards","quizMultiple"],
        presentation: [{"objective":"Use prepositions of place to describe where things are.","rewards":[{"emoji":"⭐","title":"+100 XP"},{"emoji":"🏆","title":"Weekly Badge"},{"emoji":"🎯","title":"New Achievement"}],"tips":["Memorize: in, on, under, next to, behind, in front of","Practice 'The book is on the table'","Use 'Where is...?' to ask about location"]}],
        resources:[
          {title:"British Council — Prepositions of Place", desc:"Ejercicios de preposiciones de lugar", url:"https://learnenglish.britishcouncil.org/grammar/beginner-to-pre-intermediate/prepositions-of-place"},
          {title:"ESL Gamonth Plus — Prepositions", desc:"Juego interactivo de preposiciones de lugar", url:"https://www.eslgamesplus.com/prepositions-of-place-esl-vocabulary-game/"},
          {title:"Google My Maps", desc:"Crea un mapa del barrio con ubicaciones en inglés", url:"https://www.google.com/maps/about/mymaps/"},
        ],
      },
      {
       id:"g67-may-s6", topic:"Weather vocabulary", fecha:"11 – 17 may",
        vocab:[
          {en:"SUNNY", es:"SOLEADO"},
          {en:"RAINY", es:"LLUVIOSO"},
          {en:"CLOUDY", es:"NUBLADO"},
          {en:"WINDY", es:"VENTOSO"},
          {en:"FOGGY", es:"CON NIEBLA"},
          {en:"HOT", es:"CALIENTE"},
          {en:"COLD", es:"FRÍO"},
          {en:"WEATHER", es:"CLIMA"},
        ],
        games: ["pandyMemory","snapCards","quizMultiple"],
        presentation: [{"objective":"Learn weather vocabulary and describe the weather.","rewards":[{"emoji":"⭐","title":"+100 XP"},{"emoji":"🏆","title":"Weekly Badge"},{"emoji":"🎯","title":"New Achievement"}],"tips":["Memorize: sunny, rainy, cloudy, windy, foggy, hot, cold","Practice 'It is sunny today'","Use 'What is the weather like?'"]}],
        resources:[
          {title:"British Council — Weather", desc:"Vocabulary del clima con canciones y actividades", url:"https://learnenglishkids.britishcouncil.org/songs/weather-song"},
          {title:"Weather.com en inglés", desc:"Consulta el clima real en inglés para usar en clase", url:"https://weather.com/"},
          {title:"ESL Games World — Weather", desc:"Juegos de vocabulary del time", url:"https://www.eslgamesworld.com/members/games/vocabulary/weather/"},
        ],
      },
      {
       id:"g67-may-s7", topic:"Integrated practice: places, weather and routine", fecha:"18 – 24 may",
        vocab:[
          {en:"PARK", es:"PARQUE"},
          {en:"SCHOOL", es:"ESCUELA"},
          {en:"MARKET", es:"MERCADO"},
          {en:"HOSPITAL", es:"HOSPITAL"},
          {en:"MORNING", es:"MAÑANA"},
          {en:"AFTERNOON", es:"TARDE"},
          {en:"EVENING", es:"NOCHE"},
          {en:"NEIGHBORHOOD", es:"BARRIO"},
        ],
        games: ["pandyMemory","snapCards","wordRace"],
        presentation: [{"objective":"Integrate vocabulary about places, weather, and daily routines into sentences.","rewards":[{"emoji":"⭐","title":"+100 XP"},{"emoji":"🏆","title":"Weekly Badge"},{"emoji":"🎯","title":"New Achievement"}],"tips":["Practice 'The school is next to the park'","Use 'I am going to the market'","Combine weather and place vocabulary"]}],
        resources:[
          {title:"Canva — My Life Presentation", desc:"Template for presentation: My life, my neighborhood", url:"https://www.canva.com/presentations/"},
          {title:"Google Slides", desc:"Create integrated digital presentations in English", url:"https://slides.google.com/"},
          {title:"Mentimeter — Live Poll", desc:"Live poll: what is your neighborhood like?", url:"https://www.mentimeter.com/"},
        ],
      },
      {
        id:"g67-may-s8", topic:"General term review", fecha:"25 – 31 may",
        vocab:[
          {en:"ALWAYS", es:"SIEMPRE"},
          {en:"WEATHER", es:"CLIMA"},
          {en:"NEXT TO", es:"AL LADO DE"},
          {en:"BUS", es:"AUTOBÚS"},
          {en:"SUNNY", es:"SOLEADO"},
          {en:"SCHOOL", es:"ESCUELA"},
          {en:"ROUTINE", es:"RUTINA"},
          {en:"PLAY", es:"JUGAR"},
        ],
        games: ["finalChallenge","bingo","quizMultiple"],
        presentation: [{"objective":"Review and consolidate vocabulary and grammar from the second term.","rewards":[{"emoji":"⭐","title":"+100 XP"},{"emoji":"🏆","title":"Weekly Badge"},{"emoji":"🎯","title":"New Achievement"}],"tips":["Review prepositions: next to, behind, in front of","Practice weather vocabulary","Use vocabulary from the week: bus, sunny, school"]}],
        resources:[
          {title:"Kahoot — Period 2 Review", desc:"Period 2 review quiz", url:"https://kahoot.com/schools-u/"},
          {title:"Wordwall — Mixed Games P2", desc:"Mixed review games for period 2", url:"https://wordwall.net/"},
          {title:"Canva — Mind Map Period 2", desc:"Mind map template for visual review", url:"https://www.canva.com/graphs/mind-maps/"},
        ],
      },
    ],
    5: [ // June
      {
        id:"g67-jun-s1", topic:"Written evaluation of the second term", fecha:"1 – 7 jun", badge:"Evaluation",
        vocab:[
          {en:"SUNNY", es:"SOLEADO"},
          {en:"ALWAYS", es:"SIEMPRE"},
          {en:"SCHOOL", es:"ESCUELA"},
          {en:"LIKE", es:"GUSTAR"},
          {en:"DOESN'T", es:"NO (tercera persona)"},
          {en:"RAINY", es:"LLUVIOSO"},
          {en:"NEXT TO", es:"AL LADO DE"},
          {en:"ROUTINE", es:"RUTINA"},
        ],
        games: ["finalChallenge","bingo","quizMultiple"],
        presentation: [{"objective":"Complete the written evaluation covering second-term vocabulary and grammar.","rewards":[{"emoji":"⭐","title":"+100 XP"},{"emoji":"🏆","title":"Weekly Badge"},{"emoji":"🎯","title":"New Achievement"}],"tips":["Review present simple affirmative, negative, and questions","Practice prepositions of place","Review weather and transport vocabulary"]}],
        resources:[
          {title:"Quizlet — Period 2 Final Review", desc:"Review final de vocabulary y gramática del período", url:"https://quizlet.com/"},
          {title:"Google Forms — Exit Ticket", desc:"Evalúa la comprensión al cierre del período", url:"https://forms.google.com/"},
          {title:"Kahoot — Final Quiz P2", desc:"Quiz final del segundo período", url:"https://kahoot.com/schools-u/"},
        ],
      },
      {
        id:"g67-jun-s2", topic:"Feedback and closure of the second term", fecha:"8 – 14 jun", badge:"Feedback",
        vocab:[
          {en:"IMPROVE", es:"MEJORAR"},
          {en:"GOAL", es:"META"},
          {en:"EFFORT", es:"ESFUERZO"},
          {en:"ACHIEVE", es:"LOGRAR"},
          {en:"REFLECT", es:"REFLEXIONAR"},
          {en:"LEARN", es:"APRENDER"},
          {en:"NEXT", es:"SIGUIENTE"},
          {en:"PLAN", es:"PLAN"},
        ],
        games: ["finalChallenge","bingo","quizMultiple"],
        presentation: [{"objective":"Reflect on second-term progress and plan improvements for the next term.","rewards":[{"emoji":"⭐","title":"+100 XP"},{"emoji":"🏆","title":"Weekly Badge"},{"emoji":"🎯","title":"New Achievement"}],"tips":["Describe your progress: 'I improved my...'","Set goals: 'My goal is to...'","Acknowledge effort: 'My effort was...'"]}],
        resources:[
          {title:"Canva — Self-Assessment Poster", desc:"Visual self-assessment poster template for the term", url:"https://www.canva.com/posters/"},
          {title:"Mentimeter — Reflection Activity", desc:"Real-time group reflection activity", url:"https://www.mentimeter.com/"},
          {title:"Google Forms — Self-Assessment", desc:"Self-assessment form for term 2", url:"https://forms.google.com/"},
        ],
      },
    ],
    6: [ // July — Período 3
      {
      id:"g67-jul-s1", topic:"Possessive adjectives", fecha:"6 – 12 jul",
        vocab:[
          {topic:"Possessive adjectives",cat:"A",catLabel:"Singular",emoji:"👤",en:"My book", es:"Mi libro"},
          {topic:"Possessive adjectives",cat:"A",catLabel:"Singular",emoji:"👤",en:"Your pen", es:"Tu lapicero"},
          {topic:"Possessive adjectives",cat:"A",catLabel:"Singular",emoji:"👤",en:"His bag", es:"Su bolso (de él)"},
          {topic:"Possessive adjectives",cat:"A",catLabel:"Singular",emoji:"👤",en:"Her house", es:"Su casa (de ella)"},
          {topic:"Possessive adjectives",cat:"A",catLabel:"Singular",emoji:"👤",en:"Its name", es:"Su nombre (de eso)"},
          {topic:"Possessive adjectives",cat:"A",catLabel:"Singular",emoji:"👤",en:"Our school", es:"Nuestra escuela"},
          {topic:"Possessive adjectives",cat:"A",catLabel:"Singular",emoji:"👤",en:"Their team", es:"Su equipo (de ellos)"},
          {topic:"Possessive adjectives",cat:"B",catLabel:"In context",emoji:"🏡",en:"My mother's car", es:"El carro de mi madre"},
          {topic:"Possessive adjectives",cat:"B",catLabel:"In context",emoji:"🏡",en:"His friend's name", es:"El nombre del amigo de él"},
          {topic:"Possessive adjectives",cat:"B",catLabel:"In context",emoji:"🏡",en:"Our teacher's class", es:"La clase de nuestro profesor"},
          {topic:"Possessive adjectives",cat:"B",catLabel:"In context",emoji:"🏡",en:"Their parents' house", es:"La casa de los padres de ellos"},
          {topic:"Possessive adjectives",cat:"B",catLabel:"In context",emoji:"🏡",en:"Your dog's food", es:"La comida de tu perro"},
          {topic:"Possessive adjectives",cat:"B",catLabel:"In context",emoji:"🏡",en:"Its tail", es:"Su cola (de eso)"},
          {topic:"Possessive adjectives",cat:"B",catLabel:"In context",emoji:"🏡",en:"Her favorite color", es:"Su color favorito (de ella)"},
          {topic:"Possessive adjectives",cat:"B",catLabel:"In context",emoji:"🏡",en:"My best friend", es:"Mi mejor amigo/a"},
        ],
        games: ["wordRace","snapCards","quizMultiple"],
        presentation: [{"objective":"Use possessive adjectives (my, your, his, her, its, our, their) correctly.","rewards":[{"emoji":"⭐","title":"+100 XP"},{"emoji":"🏆","title":"Weekly Badge"},{"emoji":"🎯","title":"New Achievement"}],"tips":["Match possessive adjectives to subjects: my/your/his/her/its/our/their","Practice 'My book is here'","Use before the noun directly"]}],
        resources:[
          {title:"British Council — Possessives",desc:"Possessive adjectives exercises",url:"https://learnenglish.britishcouncil.org/grammar/beginner-to-pre-intermediate/possessives"},
          {title:"ESL Games Plus — My/Your/His/Her",desc:"Possessive adjectives game",url:"https://www.eslgamesplus.com/"},
          {title:"Quizlet — Possessive Adjectives",desc:"Possessive adjectives flashcards and test",url:"https://quizlet.com/subject/possessive-adjectives/"},
        ],
      },
      {
        id:"g67-jul-s2", topic:"Possessive pronouns", fecha:"13 – 19 jul",
        vocab:[
          {topic:"Possessive pronouns",cat:"A",catLabel:"Pronouns",emoji:"✋",en:"Mine", es:"Mío/a"},
          {topic:"Possessive pronouns",cat:"A",catLabel:"Pronouns",emoji:"✋",en:"Yours", es:"Tuyo/a"},
          {topic:"Possessive pronouns",cat:"A",catLabel:"Pronouns",emoji:"✋",en:"His", es:"Suyo/a (de él)"},
          {topic:"Possessive pronouns",cat:"A",catLabel:"Pronouns",emoji:"✋",en:"Hers", es:"Suyo/a (de ella)"},
          {topic:"Possessive pronouns",cat:"A",catLabel:"Pronouns",emoji:"✋",en:"Ours", es:"Nuestro/a"},
          {topic:"Possessive pronouns",cat:"A",catLabel:"Pronouns",emoji:"✋",en:"Theirs", es:"Suyo/a (de ellos)"},
          {topic:"Possessive pronouns",cat:"A",catLabel:"Pronouns",emoji:"✋",en:"That pen is mine", es:"Ese lapicero es mío"},
          {topic:"Possessive pronouns",cat:"B",catLabel:"Dialogues",emoji:"💬",en:"Whose bag is this?", es:"¿De quién es este bolso?"},
          {topic:"Possessive pronouns",cat:"B",catLabel:"Dialogues",emoji:"💬",en:"It's hers", es:"Es de ella"},
          {topic:"Possessive pronouns",cat:"B",catLabel:"Dialogues",emoji:"💬",en:"Is this yours?", es:"¿Esto es tuyo?"},
          {topic:"Possessive pronouns",cat:"B",catLabel:"Dialogues",emoji:"💬",en:"No, it's his", es:"No, es de él"},
          {topic:"Possessive pronouns",cat:"B",catLabel:"Dialogues",emoji:"💬",en:"These books are ours", es:"Estos libros son nuestros"},
          {topic:"Possessive pronouns",cat:"B",catLabel:"Dialogues",emoji:"💬",en:"That car is theirs", es:"Ese carro es de ellos"},
          {topic:"Possessive pronouns",cat:"B",catLabel:"Dialogues",emoji:"💬",en:"This phone is mine", es:"Este teléfono es mío"},
          {topic:"Possessive pronouns",cat:"B",catLabel:"Dialogues",emoji:"💬",en:"Whose turn is it?", es:"¿De quién es el turno?"},
        ],
        games: ["wordRace","snapCards","quizMultiple"],
        presentation: [{"objective":"Use possessive pronouns (mine, yours, his, hers, ours, theirs) in sentences.","rewards":[{"emoji":"⭐","title":"+100 XP"},{"emoji":"🏆","title":"Weekly Badge"},{"emoji":"🎯","title":"New Achievement"}],"tips":["Remember: possessive pronouns replace nouns: 'The pen is mine'","Practice 'Whose bag is this?' -> 'It's hers.'","Use after 'is'/'are': 'It is hers'"]}],
        resources:[
          {title:"British Council — Possessive Pronouns",desc:"Possessive pronouns exercises",url:"https://learnenglish.britishcouncil.org/grammar/beginner-to-pre-intermediate/possessives"},
          {title:"ESL Games Plus — Pronouns",desc:"Possessive pronouns game",url:"https://www.eslgamesplus.com/"},
          {title:"Wordwall — Mine Yours His Hers",desc:"Possessive pronouns activities",url:"https://wordwall.net/"},
        ],
      },
      {
       id:"g67-jul-s3", topic:"Present continuous", fecha:"20 – 26 jul",
        vocab:[
          {topic:"Present continuous",cat:"A",catLabel:"Actions",emoji:"🏃",en:"I am running", es:"Estoy corriendo"},
          {topic:"Present continuous",cat:"A",catLabel:"Actions",emoji:"📖",en:"She is reading", es:"Ella está leyendo"},
          {topic:"Present continuous",cat:"A",catLabel:"Actions",emoji:"🎵",en:"He is singing", es:"Él está cantando"},
          {topic:"Present continuous",cat:"A",catLabel:"Actions",emoji:"🍳",en:"We are cooking", es:"Nosotros estamos cocinando"},
          {topic:"Present continuous",cat:"A",catLabel:"Actions",emoji:"💻",en:"They are studying", es:"Ellos están estudiando"},
          {topic:"Present continuous",cat:"A",catLabel:"Actions",emoji:"⚽",en:"You are playing", es:"Tú estás jugando"},
          {topic:"Present continuous",cat:"A",catLabel:"Actions",emoji:"🐕",en:"The dog is sleeping", es:"El perro está durmiendo"},
          {topic:"Present continuous",cat:"B",catLabel:"Negative & Question",emoji:"❌",en:"I am not eating", es:"Yo no estoy comiendo"},
          {topic:"Present continuous",cat:"B",catLabel:"Negative & Question",emoji:"❌",en:"She isn't dancing", es:"Ella no está bailando"},
          {topic:"Present continuous",cat:"B",catLabel:"Negative & Question",emoji:"❓",en:"Are you listening?", es:"¿Estás escuchando?"},
          {topic:"Present continuous",cat:"B",catLabel:"Negative & Question",emoji:"❓",en:"What are they doing?", es:"¿Qué están haciendo ellos?"},
          {topic:"Present continuous",cat:"B",catLabel:"Negative & Question",emoji:"❓",en:"Is he working?", es:"¿Está él trabajando?"},
          {topic:"Present continuous",cat:"B",catLabel:"Negative & Question",emoji:"❓",en:"Why is she crying?", es:"¿Por qué está llorando ella?"},
          {topic:"Present continuous",cat:"B",catLabel:"Negative & Question",emoji:"❓",en:"Where are you going?", es:"¿A dónde vas?"},
          {topic:"Present continuous",cat:"B",catLabel:"Negative & Question",emoji:"❌",en:"We aren't watching TV", es:"Nosotros no estamos viendo TV"},
        ],
        games: ["wordRace","snapCards","quizMultiple"],
        presentation: [{"objective":"Use the present continuous tense to describe actions happening now.","rewards":[{"emoji":"⭐","title":"+100 XP"},{"emoji":"🏆","title":"Weekly Badge"},{"emoji":"🎯","title":"New Achievement"}],"tips":["Form: subject + am/is/are + verb-ing","Practice 'I am running', 'She is reading'","Use 'What are they doing?' for questions"]}],
        resources:[
          {title:"British Council — Present Continuous",desc:"Ejercicios del presente continuo",url:"https://learnenglish.britishcouncil.org/grammar/beginner-to-pre-intermediate/present-continuous"},
          {title:"ESL Gamonth Plus — -ing forms",desc:"Game of verbos en -ing",url:"https://www.eslgamesplus.com/"},
          {title:"Wordwall — Present Continuous",desc:"Actividades del presente continuo",url:"https://wordwall.net/resource/present-continuous"},
        ],
      },
      {
        id:"g67-jul-s4", topic:"Neighborhood places and expanded prepositions", fecha:"27 jul – 2 aug",
        vocab:[
          {topic:"Neighborhood and prepositions",cat:"A",catLabel:"Places",emoji:"🏘️",en:"Park", es:"Parque"},
          {topic:"Neighborhood and prepositions",cat:"A",catLabel:"Places",emoji:"🏥",en:"Hospital", es:"Hospital"},
          {topic:"Neighborhood and prepositions",cat:"A",catLabel:"Places",emoji:"🏫",en:"School", es:"Escuela"},
          {topic:"Neighborhood and prepositions",cat:"A",catLabel:"Places",emoji:"🏪",en:"Supermarket", es:"Supermercado"},
          {topic:"Neighborhood and prepositions",cat:"A",catLabel:"Places",emoji:"🏦",en:"Bank", es:"Banco"},
          {topic:"Neighborhood and prepositions",cat:"A",catLabel:"Places",emoji:"⛪",en:"Church", es:"Iglesia"},
          {topic:"Neighborhood and prepositions",cat:"A",catLabel:"Places",emoji:"🚒",en:"Fire station", es:"Estación de bomberos"},
          {topic:"Neighborhood and prepositions",cat:"B",catLabel:"Prepositions",emoji:"📍",en:"Across from", es:"Frente a"},
          {topic:"Neighborhood and prepositions",cat:"B",catLabel:"Prepositions",emoji:"📍",en:"Around the corner", es:"A la vuelta de la esquina"},
          {topic:"Neighborhood and prepositions",cat:"B",catLabel:"Prepositions",emoji:"📍",en:"Down the street", es:"Calle abajo"},
          {topic:"Neighborhood and prepositions",cat:"B",catLabel:"Prepositions",emoji:"📍",en:"Next to the park", es:"Al lado del parque"},
          {topic:"Neighborhood and prepositions",cat:"B",catLabel:"Prepositions",emoji:"📍",en:"Between the bank", es:"Entre el banco"},
          {topic:"Neighborhood and prepositions",cat:"B",catLabel:"Prepositions",emoji:"📍",en:"Behind the school", es:"Detrás de la escuela"},
          {topic:"Neighborhood and prepositions",cat:"B",catLabel:"Prepositions",emoji:"📍",en:"In front of the church", es:"Enfrente de la iglesia"},
          {topic:"Neighborhood and prepositions",cat:"B",catLabel:"Prepositions",emoji:"📍",en:"On the corner", es:"En la esquina"},
        ],
        games: ["pandyMemory","snapCards","quizMultiple"],
        presentation: [{"objective":"Describe neighborhood places and use expanded prepositions in context.","rewards":[{"emoji":"⭐","title":"+100 XP"},{"emoji":"🏆","title":"Weekly Badge"},{"emoji":"🎯","title":"New Achievement"}],"tips":["Learn place names: park, school, supermarket, bank, hospital","Practice 'The school is next to the park'","Use 'across from', 'around the corner', 'down the street'"]}],
        resources:[
          {title:"British Council — Prepositions of Place",desc:"Expanded prepositions of place",url:"https://learnenglish.britishcouncil.org/grammar/beginner-to-pre-intermediate/prepositions-of-place"},
          {title:"Google My Maps",desc:"Create a neighborhood map in English",url:"https://www.google.com/maps/about/mymaps/"},
          {title:"Wordwall — Neighborhood",desc:"Neighborhood vocabulary games",url:"https://wordwall.net/"},
        ],     
       },
    ],
    7: [ // August — Período 3
      {
        id:"g67-aug-s1", topic:"Integrated practice: present continuous and prepositions", fecha:"3 – 9 aug",
        vocab:[
          {topic:"Term 3 integrated practice",cat:"A",catLabel:"Present Continuous",emoji:"🏃",en:"She is walking to school", es:"Ella está caminando a la escuela"},
          {topic:"Term 3 integrated practice",cat:"A",catLabel:"Present Continuous",emoji:"🚴",en:"He is riding his bike", es:"Él está montando en bicicleta"},
          {topic:"Term 3 integrated practice",cat:"A",catLabel:"Present Continuous",emoji:"🛍️",en:"They are shopping", es:"Ellos están de compras"},
          {topic:"Term 3 integrated practice",cat:"A",catLabel:"Present Continuous",emoji:"📱",en:"I am texting", es:"Estoy enviando mensajes de texto"},
          {topic:"Term 3 integrated practice",cat:"A",catLabel:"Present Continuous",emoji:"🎮",en:"We are playing games", es:"Nosotros estamos jugando videojuegos"},
          {topic:"Term 3 integrated practice",cat:"A",catLabel:"Present Continuous",emoji:"🍕",en:"She is eating pizza", es:"Ella está comiendo pizza"},
          {topic:"Term 3 integrated practice",cat:"A",catLabel:"Present Continuous",emoji:"📚",en:"He is doing homework", es:"Él está haciendo la tarea"},
          {topic:"Term 3 integrated practice",cat:"B",catLabel:"Place + Action",emoji:"📍",en:"The girl next to the park", es:"La niña al lado del parque"},
          {topic:"Term 3 integrated practice",cat:"B",catLabel:"Place + Action",emoji:"📍",en:"He is running across the street", es:"Él está corriendo cruzando la calle"},
          {topic:"Term 3 integrated practice",cat:"B",catLabel:"Place + Action",emoji:"📍",en:"They are sitting behind us", es:"Ellos están sentados detrás de nosotros"},
          {topic:"Term 3 integrated practice",cat:"B",catLabel:"Place + Action",emoji:"📍",en:"My book is on the desk", es:"Mi libro está sobre el escritorio"},
          {topic:"Term 3 integrated practice",cat:"B",catLabel:"Place + Action",emoji:"📍",en:"She is standing in front of the board", es:"Ella está parada enfrente del tablero"},
          {topic:"Term 3 integrated practice",cat:"B",catLabel:"Place + Action",emoji:"📍",en:"The cat is sleeping under the table", es:"El gato está durmiendo debajo de la mesa"},
          {topic:"Term 3 integrated practice",cat:"B",catLabel:"Place + Action",emoji:"📍",en:"We are between two parks", es:"Estamos entre dos parques"},
          {topic:"Term 3 integrated practice",cat:"B",catLabel:"Place + Action",emoji:"📍",en:"He is walking down the street", es:"Él está caminando por la calle"},
        ],
        games: ["pandyMemory","snapCards","wordRace"],
        presentation: [{"objective":"Integrate present continuous and prepositions to describe location and action.","rewards":[{"emoji":"⭐","title":"+100 XP"},{"emoji":"🏆","title":"Weekly Badge"},{"emoji":"🎯","title":"New Achievement"}],"tips":["Combine tenses: 'She is walking to school'","Use prepositions: 'next to', 'across from'","Practice full descriptive sentences"]}],
        resources:[
          {title:"Canva — Comic Strip",desc:"Create a comic strip using present continuous and prepositions",url:"https://www.canva.com/"},
          {title:"Google Slides — My Neighborhood",desc:"Present your neighborhood in English",url:"https://slides.google.com/"},
          {title:"Wordwall — Mixed Review P3",desc:"Mixed review for the third term",url:"https://wordwall.net/"},
        ],
      },
      {
        id:"g67-aug-s2", topic:"General review of the third term", fecha:"10 – 16 aug",
        vocab:[
          {topic:"Term 3 Review",cat:"A",catLabel:"Grammar",emoji:"📝",en:"My sister is reading", es:"Mi hermana está leyendo"},
          {topic:"Term 3 Review",cat:"A",catLabel:"Grammar",emoji:"📝",en:"Their house is big", es:"La casa de ellos es grande"},
          {topic:"Term 3 Review",cat:"A",catLabel:"Grammar",emoji:"📝",en:"Are you studying?", es:"¿Estás estudiando?"},
          {topic:"Term 3 Review",cat:"A",catLabel:"Grammar",emoji:"📝",en:"Whose book is this?", es:"¿De quién es este libro?"},
          {topic:"Term 3 Review",cat:"A",catLabel:"Grammar",emoji:"📝",en:"It's hers", es:"Es de ella"},
          {topic:"Term 3 Review",cat:"A",catLabel:"Grammar",emoji:"📝",en:"He isn't playing", es:"Él no está jugando"},
          {topic:"Term 3 Review",cat:"A",catLabel:"Grammar",emoji:"📝",en:"Our team is winning", es:"Nuestro equipo está ganando"},
          {topic:"Term 3 Review",cat:"B",catLabel:"Vocabulary",emoji:"📚",en:"Across from", es:"Frente a"},
          {topic:"Term 3 Review",cat:"B",catLabel:"Vocabulary",emoji:"📚",en:"Supermarket", es:"Supermercado"},
          {topic:"Term 3 Review",cat:"B",catLabel:"Vocabulary",emoji:"📚",en:"Theirs", es:"Suyo/a (de ellos)"},
          {topic:"Term 3 Review",cat:"B",catLabel:"Vocabulary",emoji:"📚",en:"Around the corner", es:"A la vuelta de la esquina"},
          {topic:"Term 3 Review",cat:"B",catLabel:"Vocabulary",emoji:"📚",en:"She is dancing", es:"Ella está bailando"},
          {topic:"Term 3 Review",cat:"B",catLabel:"Vocabulary",emoji:"📚",en:"Your school", es:"Tu escuela"},
          {topic:"Term 3 Review",cat:"B",catLabel:"Vocabulary",emoji:"📚",en:"Fire station", es:"Estación de bomberos"},
          {topic:"Term 3 Review",cat:"B",catLabel:"Vocabulary",emoji:"📚",en:"They are cooking", es:"Ellos están cocinando"},
        ],
        games: ["finalChallenge","bingo","quizMultiple"],
        presentation: [{"objective":"Review and consolidate all grammar and vocabulary from the third term.","rewards":[{"emoji":"⭐","title":"+100 XP"},{"emoji":"🏆","title":"Weekly Badge"},{"emoji":"🎯","title":"New Achievement"}],"tips":["Review present continuous: 'They are studying'","Practice possessive pronouns: 'It is hers'","Review prepositions: 'across from', 'behind'"]}],
        resources:[
          {title:"Kahoot — Term 3 Review",desc:"Third term review quiz",url:"https://kahoot.com/schools-u/"},
          {title:"Quizlet — Period 3 Review",desc:"General review with flashcards",url:"https://quizlet.com/"},
          {title:"Canva — Mind Map",desc:"Term 3 mind map",url:"https://www.canva.com/graphs/mind-maps/"},
        ],
      },
      {
       id:"g67-aug-s3", topic:"English's Day preparation (week 1)", fecha:"17 – 23 aug", badge:"English's Day prep",
        vocab:[
          {topic:"English's Day Prep",cat:"A",catLabel:"Oral Presentation",emoji:"🎤",en:"Good morning everyone", es:"Buenos días a todos"},
          {topic:"English's Day Prep",cat:"A",catLabel:"Oral Presentation",emoji:"🎤",en:"My topic is...", es:"Mi tema es..."},
          {topic:"English's Day Prep",cat:"A",catLabel:"Oral Presentation",emoji:"🎤",en:"First of all", es:"En primer lugar"},
          {topic:"English's Day Prep",cat:"A",catLabel:"Oral Presentation",emoji:"🎤",en:"In conclusion", es:"En conclusión"},
          {topic:"English's Day Prep",cat:"A",catLabel:"Oral Presentation",emoji:"🎤",en:"Thank you for listening", es:"Gracias por escuchar"},
          {topic:"English's Day Prep",cat:"A",catLabel:"Oral Presentation",emoji:"🎤",en:"Any questions?", es:"¿Alguna pregunta?"},
          {topic:"English's Day Prep",cat:"A",catLabel:"Oral Presentation",emoji:"🎤",en:"As you can see", es:"Como pueden ver"},
          {topic:"English's Day Prep",cat:"B",catLabel:"Supporting Vocabulary",emoji:"📊",en:"I would like to talk about", es:"Me gustaría hablar sobre"},
          {topic:"English's Day Prep",cat:"B",catLabel:"Supporting Vocabulary",emoji:"📊",en:"The most important thing is", es:"Lo más importante es"},
          {topic:"English's Day Prep",cat:"B",catLabel:"Supporting Vocabulary",emoji:"📊",en:"For example", es:"Por ejemplo"},
          {topic:"English's Day Prep",cat:"B",catLabel:"Supporting Vocabulary",emoji:"📊",en:"On the other hand", es:"Por otro lado"},
          {topic:"English's Day Prep",cat:"B",catLabel:"Supporting Vocabulary",emoji:"📊",en:"To sum up", es:"En resumen"},
          {topic:"English's Day Prep",cat:"B",catLabel:"Supporting Vocabulary",emoji:"📊",en:"Slide number...", es:"Diapositiva número..."},
          {topic:"English's Day Prep",cat:"B",catLabel:"Supporting Vocabulary",emoji:"📊",en:"Please look at the screen", es:"Por favor miren la pantalla"},
          {topic:"English's Day Prep",cat:"B",catLabel:"Supporting Vocabulary",emoji:"📊",en:"My name is... and I am...", es:"Mi nombre es... y tengo..."},
        ],
        games: ["toBeQuest","pandyMemory","quizMultiple"],
        presentation: [{"objective":"Prepare for English's Day presentation with oral presentation vocabulary and structure.","rewards":[{"emoji":"⭐","title":"+100 XP"},{"emoji":"🏆","title":"Weekly Badge"},{"emoji":"🎯","title":"New Achievement"}],"tips":["Practice 'Good morning everyone, my topic is...'","Use 'First of all...' and 'In conclusion...'","Ask 'Any questions?' and say 'Thank you for listening'"]}],
        resources:[
          {title:"Canva — Presentation Template",desc:"Presentation templates for English's Day",url:"https://www.canva.com/presentations/"},
          {title:"Google Slides",desc:"Create your digital presentation in English",url:"https://slides.google.com/"},
          {title:"Mentimeter — Live Presentation",desc:"Real-time interactive presentation",url:"https://www.mentimeter.com/"},
        ],
      },
      {
        id:"g67-aug-s4", topic:"English's Day preparation (week 2)", fecha:"24 – 30 aug", badge:"English's Day prep",
        vocab:[
          {topic:"English's Day Final",cat:"A",catLabel:"Key Pronunciation",emoji:"🗣️",en:"Pronunciation", es:"Pronunciación"},
          {topic:"English's Day Final",cat:"A",catLabel:"Key Pronunciation",emoji:"🗣️",en:"Fluency", es:"Fluidez"},
          {topic:"English's Day Final",cat:"A",catLabel:"Key Pronunciation",emoji:"🗣️",en:"Eye contact", es:"Contacto visual"},
          {topic:"English's Day Final",cat:"A",catLabel:"Key Pronunciation",emoji:"🗣️",en:"Body language", es:"Lenguaje corporal"},
          {topic:"English's Day Final",cat:"A",catLabel:"Key Pronunciation",emoji:"🗣️",en:"Speak clearly", es:"Habla claramente"},
          {topic:"English's Day Final",cat:"A",catLabel:"Key Pronunciation",emoji:"🗣️",en:"Loud and clear", es:"Alto y claro"},
          {topic:"English's Day Final",cat:"A",catLabel:"Key Pronunciation",emoji:"🗣️",en:"Slow down", es:"Habla más despacio"},
          {topic:"English's Day Final",cat:"B",catLabel:"Self-Assessment",emoji:"⭐",en:"I did well", es:"Lo hice bien"},
          {topic:"English's Day Final",cat:"B",catLabel:"Self-Assessment",emoji:"⭐",en:"I need to improve", es:"Necesito mejorar"},
          {topic:"English's Day Final",cat:"B",catLabel:"Self-Assessment",emoji:"⭐",en:"My best part was", es:"Mi mejor parte fue"},
          {topic:"English's Day Final",cat:"B",catLabel:"Self-Assessment",emoji:"⭐",en:"Next time I will", es:"La próxima vez voy a"},
          {topic:"English's Day Final",cat:"B",catLabel:"Self-Assessment",emoji:"⭐",en:"I am proud of", es:"Estoy orgulloso/a de"},
          {topic:"English's Day Final",cat:"B",catLabel:"Self-Assessment",emoji:"⭐",en:"My weakness is", es:"Mi debilidad es"},
          {topic:"English's Day Final",cat:"B",catLabel:"Self-Assessment",emoji:"⭐",en:"I learned that", es:"Aprendí que"},
          {topic:"English's Day Final",cat:"B",catLabel:"Self-Assessment",emoji:"⭐",en:"I feel confident", es:"Me siento con confianza"},
        ],
        games: ["toBeQuest","pandyMemory","quizMultiple"],
        presentation: [{"objective":"Refine pronunciation, fluency, and self-assessment skills for English's Day.","rewards":[{"emoji":"⭐","title":"+100 XP"},{"emoji":"🏆","title":"Weekly Badge"},{"emoji":"🎯","title":"New Achievement"}],"tips":["Practice speaking clearly and loudly","Maintain eye contact and good body language","Self-assess: 'I did well', 'I need to improve'"]}],
        resources:[
          {title:"Flipgrid / Flip",desc:"Record your presentation on video to practice",url:"https://info.flip.com/"},
          {title:"British Council — Giving Presentations",desc:"Tips for oral presentations in English",url:"https://learnenglish.britishcouncil.org/"},
          {title:"Google Forms — Self-Assessment",desc:"Presentation self-assessment rubric",url:"https://forms.google.com/"},
        ],
      },
    ],
    8: [ // September — Período 3 (cierre) / Período 4 (inicio)
      {
        id:"g67-sep-s9", topic:"English's Day presentation (September 4)", fecha:"31 aug – 6 sep", badge:"English's Day",
        vocab:[
          {topic:"English's Day Presentation",cat:"A",catLabel:"English's Day",emoji:"🎤",en:"I presented my topic", es:"Presenté mi tema"},
          {topic:"English's Day Presentation",cat:"A",catLabel:"English's Day",emoji:"🎤",en:"The audience was great", es:"El público estuvo genial"},
          {topic:"English's Day Presentation",cat:"A",catLabel:"English's Day",emoji:"🎤",en:"I felt nervous", es:"Me sentí nervioso/a"},
          {topic:"English's Day Presentation",cat:"A",catLabel:"English's Day",emoji:"🎤",en:"My classmates presented well", es:"Mis compañeros presentaron bien"},
          {topic:"English's Day Presentation",cat:"A",catLabel:"English's Day",emoji:"🎤",en:"We all did our best", es:"Todos dimos lo mejor de nosotros"},
          {topic:"English's Day Presentation",cat:"A",catLabel:"English's Day",emoji:"🎤",en:"Next year I will do better", es:"El próximo año lo haré mejor"},
          {topic:"English's Day Presentation",cat:"A",catLabel:"English's Day",emoji:"🎤",en:"English is important", es:"El inglés es importante"},
          {topic:"English's Day Presentation",cat:"B",catLabel:"Reflection",emoji:"💭",en:"I am proud of my work", es:"Estoy orgulloso/a de mi trabajo"},
          {topic:"English's Day Presentation",cat:"B",catLabel:"Reflection",emoji:"💭",en:"It was a great experience", es:"Fue una gran experiencia"},
          {topic:"English's Day Presentation",cat:"B",catLabel:"Reflection",emoji:"💭",en:"I learned a lot today", es:"Aprendí mucho hoy"},
          {topic:"English's Day Presentation",cat:"B",catLabel:"Reflection",emoji:"💭",en:"My teacher was proud of me", es:"Mi profesor/a estaba orgulloso/a de mí"},
          {topic:"English's Day Presentation",cat:"B",catLabel:"Reflection",emoji:"💭",en:"Public speaking is hard", es:"Hablar en público es difícil"},
          {topic:"English's Day Presentation",cat:"B",catLabel:"Reflection",emoji:"💭",en:"I want to improve next time", es:"Quiero mejorar la próxima vez"},
          {topic:"English's Day Presentation",cat:"B",catLabel:"Reflection",emoji:"💭",en:"Congratulations to everyone", es:"Felicitaciones a todos"},
          {topic:"English's Day Presentation",cat:"B",catLabel:"Reflection",emoji:"💭",en:"Thank you for watching", es:"Gracias por ver"},
        ],
        games: ["toBeQuest","pandyMemory","quizMultiple"],
        presentation: [{"objective":"Present and reflect on your English's Day presentation.","rewards":[{"emoji":"⭐","title":"+100 XP"},{"emoji":"🏆","title":"Weekly Badge"},{"emoji":"🎯","title":"New Achievement"}],"tips":["Use 'I presented my topic'","Describe the audience: 'The audience was great'","Reflect: 'I felt nervous', 'We all did our best'"]}],
        resources:[
          {title:"Canva — Reflection Poster", desc:"English's Day reflection in poster format", url:"https://www.canva.com/posters/"},
          {title:"Flipgrid / Flip", desc:"Record an English's Day reflection video", url:"https://info.flip.com/"},
          {title:"Google Forms — Peer Evaluation", desc:"Digital peer evaluation of the presentations", url:"https://forms.google.com/"},
        ],
      },
      {
        id:"g67-sep-s10", topic:"Evaluation and feedback for the third term", fecha:"7 – 13 sep", badge:"Evaluation",
        vocab:[
          {topic:"Term 3 Evaluation G67",cat:"A",catLabel:"General Review",emoji:"📝",en:"She is reading her book", es:"Ella está leyendo su libro"},
          {topic:"Term 3 Evaluation G67",cat:"A",catLabel:"General Review",emoji:"📝",en:"Whose turn is it?", es:"¿De quién es el turno?"},
          {topic:"Term 3 Evaluation G67",cat:"A",catLabel:"General Review",emoji:"📝",en:"The school is next to the park", es:"La escuela está al lado del parque"},
          {topic:"Term 3 Evaluation G67",cat:"A",catLabel:"General Review",emoji:"📝",en:"My friend's name is Carlos", es:"El nombre de mi amigo es Carlos"},
          {topic:"Term 3 Evaluation G67",cat:"A",catLabel:"General Review",emoji:"📝",en:"Are they playing football?", es:"¿Están ellos jugando fútbol?"},
          {topic:"Term 3 Evaluation G67",cat:"A",catLabel:"General Review",emoji:"📝",en:"This notebook is mine", es:"Este cuaderno es mío"},
          {topic:"Term 3 Evaluation G67",cat:"A",catLabel:"General Review",emoji:"📝",en:"We are learning English", es:"Nosotros estamos aprendiendo inglés"},
          {topic:"Term 3 Evaluation G67",cat:"B",catLabel:"Vocabulary",emoji:"📚",en:"Down the street", es:"Calle abajo"},
          {topic:"Term 3 Evaluation G67",cat:"B",catLabel:"Vocabulary",emoji:"📚",en:"His bag", es:"Su bolso (de él)"},
          {topic:"Term 3 Evaluation G67",cat:"B",catLabel:"Vocabulary",emoji:"📚",en:"I am running", es:"Estoy corriendo"},
          {topic:"Term 3 Evaluation G67",cat:"B",catLabel:"Vocabulary",emoji:"📚",en:"Across from", es:"Frente a"},
          {topic:"Term 3 Evaluation G67",cat:"B",catLabel:"Vocabulary",emoji:"📚",en:"Theirs", es:"Suyo/a (de ellos)"},
          {topic:"Term 3 Evaluation G67",cat:"B",catLabel:"Vocabulary",emoji:"📚",en:"She is dancing", es:"Ella está bailando"},
          {topic:"Term 3 Evaluation G67",cat:"B",catLabel:"Vocabulary",emoji:"📚",en:"Supermarket", es:"Supermercado"},
          {topic:"Term 3 Evaluation G67",cat:"B",catLabel:"Vocabulary",emoji:"📚",en:"Fire station", es:"Estación de bomberos"},
        ],
        games: ["finalChallenge","bingo","quizMultiple"],
        presentation: [{"objective":"Complete the evaluation and feedback for the third term.","rewards":[{"emoji":"⭐","title":"+100 XP"},{"emoji":"🏆","title":"Weekly Badge"},{"emoji":"🎯","title":"New Achievement"}],"tips":["Review all grammar: present simple, continuous, to be, have","Practice 'She is reading her book'","Review vocabulary: Wednesday, grandfather, rainy"]}],
        resources:[
          {title:"Kahoot — Review P3 Final",desc:"Final quiz for the third term",url:"https://kahoot.com/schools-u/"},
          {title:"Quizlet — Period 3 Final",desc:"Flashcard review for term 3",url:"https://quizlet.com/"},
          {title:"Google Forms — Exam P3", desc:"Digital evaluation for the third term", url:"https://forms.google.com/"},
        ],
      },
      {
       id:"g67-sep-s2", topic:"Definite and indefinite articles and professions", fecha:"14 – 20 sep",
        vocab:[
          {topic:"Articles and professions",cat:"A",catLabel:"Articles",emoji:"📌",en:"A doctor", es:"Un doctor"},
          {topic:"Articles and professions",cat:"A",catLabel:"Articles",emoji:"📌",en:"An engineer", es:"Un ingeniero"},
          {topic:"Articles and professions",cat:"A",catLabel:"Articles",emoji:"📌",en:"The teacher", es:"El/la profesor(a)"},
          {topic:"Articles and professions",cat:"A",catLabel:"Articles",emoji:"📌",en:"A nurse", es:"Un/a enfermero/a"},
          {topic:"Articles and professions",cat:"A",catLabel:"Articles",emoji:"📌",en:"An artist", es:"Un/a artista"},
          {topic:"Articles and professions",cat:"A",catLabel:"Articles",emoji:"📌",en:"The police officer", es:"El/la oficial de policía"},
          {topic:"Articles and professions",cat:"A",catLabel:"Articles",emoji:"📌",en:"A firefighter", es:"Un/a bombero/a"},
          {topic:"Articles and professions",cat:"B",catLabel:"Professions",emoji:"👷",en:"Lawyer", es:"Abogado/a"},
          {topic:"Articles and professions",cat:"B",catLabel:"Professions",emoji:"👩‍⚕️",en:"Surgeon", es:"Cirujano/a"},
          {topic:"Articles and professions",cat:"B",catLabel:"Professions",emoji:"👨‍🍳",en:"Chef", es:"Chef"},
          {topic:"Articles and professions",cat:"B",catLabel:"Professions",emoji:"👩‍💻",en:"Software developer", es:"Desarrollador/a de software"},
          {topic:"Articles and professions",cat:"B",catLabel:"Professions",emoji:"✈️",en:"Pilot", es:"Piloto"},
          {topic:"Articles and professions",cat:"B",catLabel:"Professions",emoji:"🎓",en:"Professor", es:"Profesor/a universitario/a"},
          {topic:"Articles and professions",cat:"B",catLabel:"Professions",emoji:"🏗️",en:"Architect", es:"Arquitecto/a"},
          {topic:"Articles and professions",cat:"B",catLabel:"Professions",emoji:"🔬",en:"Scientist", es:"Científico/a"},
        ],
        games: ["pandyMemory","snapCards","quizMultiple"],
        presentation: [{"objective":"Use definite and indefinite articles (a, an, the) with professions.","rewards":[{"emoji":"⭐","title":"+100 XP"},{"emoji":"🏆","title":"Weekly Badge"},{"emoji":"🎯","title":"New Achievement"}],"tips":["Use 'a' before consonant sounds: a doctor, a nurse","Use 'an' before vowel sounds: an engineer, an artist","Use 'the' for specific people: the teacher"]}],
        resources:[
          {title:"British Council — Articles",desc:"Exercises on articles a/an/the",url:"https://learnenglish.britishcouncil.org/grammar/beginner-to-pre-intermediate/articles"},
          {title:"ESL Games Plus — Jobs & Professions",desc:"Jobs and professions game in English",url:"https://www.eslgamesplus.com/"},
          {title:"Canva — Future Jobs Poster",desc:"Poster: What do I want to be?",url:"https://www.canva.com/posters/"},
        ],
      },
      {
        id:"g67-sep-s3", topic:"Extended present progressive", fecha:"21 – 27 sep",
        vocab:[
          {topic:"Present progressive",cat:"A",catLabel:"-ing Rules",emoji:"📏",en:"Run → Running", es:"Correr → Corriendo"},
          {topic:"Present progressive",cat:"A",catLabel:"-ing Rules",emoji:"📏",en:"Swim → Swimming", es:"Nadar → Nadando"},
          {topic:"Present progressive",cat:"A",catLabel:"-ing Rules",emoji:"📏",en:"Write → Writing", es:"Escribir → Escribiendo"},
          {topic:"Present progressive",cat:"A",catLabel:"-ing Rules",emoji:"📏",en:"Dance → Dancing", es:"Bailar → Bailando"},
          {topic:"Present progressive",cat:"A",catLabel:"-ing Rules",emoji:"📏",en:"Sit → Sitting", es:"Sentarse → Sentado/a"},
          {topic:"Present progressive",cat:"A",catLabel:"-ing Rules",emoji:"📏",en:"Make → Making", es:"Hacer → Haciendo"},
          {topic:"Present progressive",cat:"A",catLabel:"-ing Rules",emoji:"📏",en:"Shop → Shopping", es:"Comprar → Comprando"},
          {topic:"Present progressive",cat:"B",catLabel:"Sentences",emoji:"💬",en:"The children are swimming", es:"Los niños están nadando"},
          {topic:"Present progressive",cat:"B",catLabel:"Sentences",emoji:"💬",en:"She is writing a letter", es:"Ella está escribiendo una carta"},
          {topic:"Present progressive",cat:"B",catLabel:"Sentences",emoji:"💬",en:"We are sitting in class", es:"Nosotros estamos sentados en clase"},
          {topic:"Present progressive",cat:"B",catLabel:"Sentences",emoji:"💬",en:"He is making lunch", es:"Él está haciendo el almuerzo"},
          {topic:"Present progressive",cat:"B",catLabel:"Sentences",emoji:"💬",en:"They are shopping at the market", es:"Ellos están comprando en el mercado"},
          {topic:"Present progressive",cat:"B",catLabel:"Sentences",emoji:"💬",en:"I am not watching TV", es:"Yo no estoy viendo TV"},
          {topic:"Present progressive",cat:"B",catLabel:"Sentences",emoji:"💬",en:"Are you dancing?", es:"¿Estás bailando?"},
          {topic:"Present progressive",cat:"B",catLabel:"Sentences",emoji:"💬",en:"What is she making?", es:"¿Qué está haciendo ella?"},
        ],
        games: ["wordRace","snapCards","quizMultiple"],
        presentation: [{"objective":"Use the present progressive (-ing forms) with irregular and regular verbs.","rewards":[{"emoji":"⭐","title":"+100 XP"},{"emoji":"🏆","title":"Weekly Badge"},{"emoji":"🎯","title":"New Achievement"}],"tips":["Regular: run->running, swim->swimming","Irregular: write->writing, dance->dancing","Practice 'She is writing a letter'"]}],
        resources:[
          {title:"British Council — Present Progressive",desc:"Present progressive exercises",url:"https://learnenglish.britishcouncil.org/grammar/beginner-to-pre-intermediate/present-continuous"},
          {title:"ESL Games Plus — -ing rules",desc:"-ing spelling rules game",url:"https://www.eslgamesplus.com/"},
          {title:"Canva — Story Creator",desc:"Create a digital story using present progressive",url:"https://www.canva.com/"},
        ],
      },
      {
       id:"g67-sep-s4", topic:"Can / Can't — abilities", fecha:"28 sep – 4 oct",
        vocab:[
          {topic:"Can / Can't",cat:"A",catLabel:"Abilities",emoji:"💪",en:"I can swim", es:"Yo puedo nadar"},
          {topic:"Can / Can't",cat:"A",catLabel:"Abilities",emoji:"🎸",en:"She can play guitar", es:"Ella puede tocar guitarra"},
          {topic:"Can / Can't",cat:"A",catLabel:"Abilities",emoji:"🏃",en:"He can run fast", es:"Él puede correr rápido"},
          {topic:"Can / Can't",cat:"A",catLabel:"Abilities",emoji:"🎨",en:"They can draw", es:"Ellos pueden dibujar"},
          {topic:"Can / Can't",cat:"A",catLabel:"Abilities",emoji:"🌍",en:"We can speak English", es:"Nosotros podemos hablar inglés"},
          {topic:"Can / Can't",cat:"A",catLabel:"Abilities",emoji:"🍳",en:"My mom can cook well", es:"Mi mamá puede cocinar bien"},
          {topic:"Can / Can't",cat:"A",catLabel:"Abilities",emoji:"🚲",en:"Can you ride a bike?", es:"¿Puedes andar en bicicleta?"},
          {topic:"Can / Can't",cat:"B",catLabel:"Negative & Question",emoji:"❌",en:"I can't fly", es:"Yo no puedo volar"},
          {topic:"Can / Can't",cat:"B",catLabel:"Negative & Question",emoji:"❌",en:"She can't drive yet", es:"Ella todavía no puede conducir"},
          {topic:"Can / Can't",cat:"B",catLabel:"Negative & Question",emoji:"❌",en:"Cats can't bark", es:"Los gatos no pueden ladrar"},
          {topic:"Can / Can't",cat:"B",catLabel:"Negative & Question",emoji:"❓",en:"Can he sing?", es:"¿Puede él cantar?"},
          {topic:"Can / Can't",cat:"B",catLabel:"Negative & Question",emoji:"❓",en:"What can you do?", es:"¿Qué puedes hacer?"},
          {topic:"Can / Can't",cat:"B",catLabel:"Negative & Question",emoji:"❓",en:"Can they dance?", es:"¿Pueden ellos bailar?"},
          {topic:"Can / Can't",cat:"B",catLabel:"Negative & Question",emoji:"❓",en:"Yes, I can!", es:"¡Sí, puedo!"},
          {topic:"Can / Can't",cat:"B",catLabel:"Negative & Question",emoji:"❓",en:"No, she can't", es:"No, ella no puede"},
        ],
        games: ["wordRace","snapCards","quizMultiple"],
        presentation: [{"objective":"Express abilities and preferences using 'can' and 'can't'.","rewards":[{"emoji":"⭐","title":"+100 XP"},{"emoji":"🏆","title":"Weekly Badge"},{"emoji":"🎯","title":"New Achievement"}],"tips":["Affirmative: 'I can swim', 'She can play guitar'","Negative: 'I can't fly', 'She can't drive yet'","Questions: 'Can you...?', 'What can you do?'"]}],
        resources:[
          {title:"British Council — Can/Can't",desc:"Can and can't exercises",url:"https://learnenglish.britishcouncil.org/grammar/beginner-to-pre-intermediate/can-and-cant"},
          {title:"ESL Games Plus — Abilities",desc:"Abilities game with can",url:"https://www.eslgamesplus.com/"},
          {title:"Canva — My Abilities Poster",desc:"Poster of class abilities",url:"https://www.canva.com/posters/"},
        ],
      },
    ],
    9: [ // October — Período 4 (receso 5-11 oct)
      {
       id:"g67-oct-s2", topic:"Extended WH-Questions", fecha:"12 – 18 oct",
        vocab:[
          {topic:"WH-Questions",cat:"A",catLabel:"WH Question Words",emoji:"❓",en:"What", es:"Qué"},
          {topic:"WH-Questions",cat:"A",catLabel:"WH Question Words",emoji:"❓",en:"Where", es:"Dónde"},
          {topic:"WH-Questions",cat:"A",catLabel:"WH Question Words",emoji:"❓",en:"When", es:"Cuándo"},
          {topic:"WH-Questions",cat:"A",catLabel:"WH Question Words",emoji:"❓",en:"Who", es:"Quién"},
          {topic:"WH-Questions",cat:"A",catLabel:"WH Question Words",emoji:"❓",en:"Why", es:"Por qué"},
          {topic:"WH-Questions",cat:"A",catLabel:"WH Question Words",emoji:"❓",en:"How", es:"Cómo"},
          {topic:"WH-Questions",cat:"A",catLabel:"WH Question Words",emoji:"❓",en:"How many", es:"Cuántos/as"},
          {topic:"WH-Questions",cat:"B",catLabel:"In Use",emoji:"💬",en:"What is your name?", es:"¿Cómo te llamas?"},
          {topic:"WH-Questions",cat:"B",catLabel:"In Use",emoji:"💬",en:"Where do you live?", es:"¿Dónde vives?"},
          {topic:"WH-Questions",cat:"B",catLabel:"In Use",emoji:"💬",en:"When is your birthday?", es:"¿Cuándo es tu cumpleaños?"},
          {topic:"WH-Questions",cat:"B",catLabel:"In Use",emoji:"💬",en:"Who is your best friend?", es:"¿Quién es tu mejor amigo/a?"},
          {topic:"WH-Questions",cat:"B",catLabel:"In Use",emoji:"💬",en:"Why do you like English?", es:"¿Por qué te gusta el inglés?"},
          {topic:"WH-Questions",cat:"B",catLabel:"In Use",emoji:"💬",en:"How do you go to school?", es:"¿Cómo vas a la escuela?"},
          {topic:"WH-Questions",cat:"B",catLabel:"In Use",emoji:"💬",en:"How many siblings do you have?", es:"¿Cuántos hermanos tienes?"},
          {topic:"WH-Questions",cat:"B",catLabel:"In Use",emoji:"💬",en:"What time do you wake up?", es:"¿A qué hora te despiertas?"},
        ],
        games: ["wordRace","snapCards","quizMultiple"],
        presentation: [{"objective":"Use WH-question words (what, where, when, who, why, how, how many) in sentences.","rewards":[{"emoji":"⭐","title":"+100 XP"},{"emoji":"🏆","title":"Weekly Badge"},{"emoji":"🎯","title":"New Achievement"}],"tips":["Practice question starters: 'What is your name?'","Use 'Where do you live?' for location","Use 'How many siblings do you have?' for quantities"]}],
        resources:[
          {title:"British Council — WH-Questions",desc:"WH-Questions exercises",url:"https://learnenglish.britishcouncil.org/grammar/beginner-to-pre-intermediate/wh-questions"},
          {title:"ESL Games Plus — Question Words",desc:"Question words game",url:"https://www.eslgamesplus.com/"},
          {title:"Kahoot — WH-Questions Quiz",desc:"Interactive WH-Questions quiz",url:"https://kahoot.com/schools-u/"},
        ],
      },
      {
        id:"g67-oct-s3", topic:"Celebrations and traditions", fecha:"19 – 25 oct",
        vocab:[
          {topic:"Celebrations",cat:"A",catLabel:"Holidays",emoji:"🎃",en:"Halloween", es:"Halloween"},
          {topic:"Celebrations",cat:"A",catLabel:"Holidays",emoji:"🎄",en:"Christmas", es:"Navidad"},
          {topic:"Celebrations",cat:"A",catLabel:"Holidays",emoji:"🎆",en:"New Year's Eve", es:"Fin de año"},
          {topic:"Celebrations",cat:"A",catLabel:"Holidays",emoji:"❤️",en:"Valentine's Day", es:"Día de San Valentín"},
          {topic:"Celebrations",cat:"A",catLabel:"Holidays",emoji:"🦃",en:"Thanksgiving", es:"Acción de Gracias"},
          {topic:"Celebrations",cat:"A",catLabel:"Holidays",emoji:"🌺",en:"Mother's Day", es:"Día de la Madre"},
          {topic:"Celebrations",cat:"A",catLabel:"Holidays",emoji:"🇨🇴",en:"Independence Day", es:"Día de la Independencia"},
          {topic:"Celebrations",cat:"B",catLabel:"Traditions",emoji:"🎁",en:"We exchange gifts", es:"Intercambiamos regalos"},
          {topic:"Celebrations",cat:"B",catLabel:"Traditions",emoji:"🕯️",en:"We light candles", es:"Encendemos velas"},
          {topic:"Celebrations",cat:"B",catLabel:"Traditions",emoji:"🍽️",en:"We have a family dinner", es:"Tenemos una cena familiar"},
          {topic:"Celebrations",cat:"B",catLabel:"Traditions",emoji:"🎭",en:"We wear costumes", es:"Usamos disfraces"},
          {topic:"Celebrations",cat:"B",catLabel:"Traditions",emoji:"🎉",en:"We celebrate together", es:"Celebramos juntos"},
          {topic:"Celebrations",cat:"B",catLabel:"Traditions",emoji:"🌟",en:"It is a special tradition", es:"Es una tradición especial"},
          {topic:"Celebrations",cat:"B",catLabel:"Traditions",emoji:"🪔",en:"People gather together", es:"Las personas se reúnen"},
          {topic:"Celebrations",cat:"B",catLabel:"Traditions",emoji:"🎶",en:"We sing traditional songs", es:"Cantamos canciones tradicionales"},
        ],
        games: ["pandyMemory","snapCards","quizMultiple"],
        presentation: [{"objective":"Learn vocabulary about celebrations and traditions from around the world.","rewards":[{"emoji":"⭐","title":"+100 XP"},{"emoji":"🏆","title":"Weekly Badge"},{"emoji":"🎯","title":"New Achievement"}],"tips":["Memorize holidays: Halloween, Christmas, Valentine's Day","Practice traditions: 'We exchange gifts'","Use 'It is a special tradition'"]}],
        resources:[
          {title:"British Council — Celebrations",desc:"Celebrations vocabulary in English",url:"https://learnenglishkids.britishcouncil.org/"},
          {title:"Canva — Greeting Card",desc:"Create a celebration card in English",url:"https://www.canva.com/cards/"},
          {title:"ESL Games World — Holidays",desc:"Holiday games in English",url:"https://www.eslgamesworld.com/"},
        ],
      },
      {
        id:"g67-oct-s4", topic:"Integrated practice: description and can", fecha:"26 oct – 1 nov",
        vocab:[
          {topic:"Term 4 Practice",cat:"A",catLabel:"Integration",emoji:"✨",en:"She can dance very well", es:"Ella puede bailar muy bien"},
          {topic:"Term 4 Practice",cat:"A",catLabel:"Integration",emoji:"✨",en:"Where does he live?", es:"¿Dónde vive él?"},
          {topic:"Term 4 Practice",cat:"A",catLabel:"Integration",emoji:"✨",en:"They can't come tonight", es:"Ellos no pueden venir esta noche"},
          {topic:"Term 4 Practice",cat:"A",catLabel:"Integration",emoji:"✨",en:"What do you celebrate?", es:"¿Qué celebras?"},
          {topic:"Term 4 Practice",cat:"A",catLabel:"Integration",emoji:"✨",en:"We wear costumes on Halloween", es:"Usamos disfraces en Halloween"},
          {topic:"Term 4 Practice",cat:"A",catLabel:"Integration",emoji:"✨",en:"How many people can come?", es:"¿Cuántas personas pueden venir?"},
          {topic:"Term 4 Practice",cat:"A",catLabel:"Integration",emoji:"✨",en:"Who can help me?", es:"¿Quién puede ayudarme?"},
          {topic:"Term 4 Practice",cat:"B",catLabel:"Review",emoji:"📚",en:"Can they swim?", es:"¿Pueden ellos nadar?"},
          {topic:"Term 4 Practice",cat:"B",catLabel:"Review",emoji:"📚",en:"When is Christmas?", es:"¿Cuándo es Navidad?"},
          {topic:"Term 4 Practice",cat:"B",catLabel:"Review",emoji:"📚",en:"Why do you like Halloween?", es:"¿Por qué te gusta Halloween?"},
          {topic:"Term 4 Practice",cat:"B",catLabel:"Review",emoji:"📚",en:"I can speak two languages", es:"Yo puedo hablar dos idiomas"},
          {topic:"Term 4 Practice",cat:"B",catLabel:"Review",emoji:"📚",en:"We exchange gifts at Christmas", es:"Intercambiamos regalos en Navidad"},
          {topic:"Term 4 Practice",cat:"B",catLabel:"Review",emoji:"📚",en:"How do you celebrate?", es:"¿Cómo celebras?"},
          {topic:"Term 4 Practice",cat:"B",catLabel:"Review",emoji:"📚",en:"She can't play piano", es:"Ella no puede tocar piano"},
          {topic:"Term 4 Practice",cat:"B",catLabel:"Review",emoji:"📚",en:"Who is your favorite singer?", es:"¿Quién es tu cantante favorito/a?"},
        ],
        games: ["pandyMemory","snapCards","wordRace"],
        presentation: [{"objective":"Integrate description adjectives and 'can/can't' abilities in context.","rewards":[{"emoji":"⭐","title":"+100 XP"},{"emoji":"🏆","title":"Weekly Badge"},{"emoji":"🎯","title":"New Achievement"}],"tips":["Combine: 'She can dance very well'","Use 'Where does he live?' for questions","Review celebrations: 'We wear costumes on Halloween'"]}],
        resources:[
          {title:"Mentimeter — Live Poll Celebrations",desc:"Live poll on favorite celebrations",url:"https://www.mentimeter.com/"},
          {title:"Canva — Celebrations Presentation",desc:"Oral presentation about celebrations",url:"https://www.canva.com/presentations/"},
          {title:"Wordwall — Mixed Review P4",desc:"Mixed review for the fourth term",url:"https://wordwall.net/"},
        ],
      },
    ],
    10: [ // November — Período 4 (cierre)
      {
       id:"g67-nov-s1", topic:"General term review", fecha:"2 – 8 nov",
        vocab:[
          {topic:"Full-Year General Review",cat:"A",catLabel:"Whole Year",emoji:"📅",en:"I am a student", es:"Yo soy estudiante"},
          {topic:"Full-Year General Review",cat:"A",catLabel:"Whole Year",emoji:"📅",en:"She was at home", es:"Ella estaba en casa"},
          {topic:"Full-Year General Review",cat:"A",catLabel:"Whole Year",emoji:"📅",en:"They are playing now", es:"Ellos están jugando ahora"},
          {topic:"Full-Year General Review",cat:"A",catLabel:"Whole Year",emoji:"📅",en:"Can you swim?", es:"¿Puedes nadar?"},
          {topic:"Full-Year General Review",cat:"A",catLabel:"Whole Year",emoji:"📅",en:"Where do you live?", es:"¿Dónde vives?"},
          {topic:"Full-Year General Review",cat:"A",catLabel:"Whole Year",emoji:"📅",en:"My book is mine", es:"Mi libro es mío"},
          {topic:"Full-Year General Review",cat:"A",catLabel:"Whole Year",emoji:"📅",en:"There are 30 students", es:"Hay 30 estudiantes"},
          {topic:"Full-Year General Review",cat:"B",catLabel:"Year Vocabulary",emoji:"📚",en:"Wednesday", es:"Miércoles"},
          {topic:"Full-Year General Review",cat:"B",catLabel:"Year Vocabulary",emoji:"📚",en:"Grandmother", es:"Abuela"},
          {topic:"Full-Year General Review",cat:"B",catLabel:"Year Vocabulary",emoji:"📚",en:"Rainy", es:"Lluvioso"},
          {topic:"Full-Year General Review",cat:"B",catLabel:"Year Vocabulary",emoji:"📚",en:"Supermarket", es:"Supermercado"},
          {topic:"Full-Year General Review",cat:"B",catLabel:"Year Vocabulary",emoji:"📚",en:"Independence Day", es:"Día de la Independencia"},
          {topic:"Full-Year General Review",cat:"B",catLabel:"Year Vocabulary",emoji:"📚",en:"She is swimming", es:"Ella está nadando"},
          {topic:"Full-Year General Review",cat:"B",catLabel:"Year Vocabulary",emoji:"📚",en:"First", es:"Primero"},
          {topic:"Full-Year General Review",cat:"B",catLabel:"Year Vocabulary",emoji:"📚",en:"I can't fly", es:"Yo no puedo volar"},
        ],
        games: ["finalChallenge","bingo","quizMultiple"],
        presentation: [{"objective":"Review all major grammar and vocabulary from the entire school year.","rewards":[{"emoji":"⭐","title":"+100 XP"},{"emoji":"🏆","title":"Weekly Badge"},{"emoji":"🎯","title":"New Achievement"}],"tips":["Review to be: 'I am a student'","Practice 'They are playing now'","Review vocabulary: Wednesday, rainy, supermarket"]}],
        resources:[
          {title:"Kahoot — Review Anual",desc:"Full-year review quiz",url:"https://kahoot.com/schools-u/"},
          {title:"Quizlet — Annual Review",desc:"Annual review with flashcards",url:"https://quizlet.com/"},
          {title:"Canva — Year Portfolio",desc:"Digital portfolio of the school year",url:"https://www.canva.com/"},
        ],
      },
      {
        id:"g67-nov-s2", topic:"Final evaluation for the fourth term", fecha:"9 – 15 nov", badge:"Evaluation",
        vocab:[
          {topic:"Final Evaluation",cat:"A",catLabel:"Grammar",emoji:"📝",en:"She can't drive", es:"Ella no puede conducir"},
          {topic:"Final Evaluation",cat:"A",catLabel:"Grammar",emoji:"📝",en:"What time do you wake up?", es:"¿A qué hora te despiertas?"},
          {topic:"Final Evaluation",cat:"A",catLabel:"Grammar",emoji:"📝",en:"We are celebrating together", es:"Estamos celebrando juntos"},
          {topic:"Final Evaluation",cat:"A",catLabel:"Grammar",emoji:"📝",en:"My sister's book", es:"El libro de mi hermana"},
          {topic:"Final Evaluation",cat:"A",catLabel:"Grammar",emoji:"📝",en:"It's theirs", es:"Es de ellos"},
          {topic:"Final Evaluation",cat:"A",catLabel:"Grammar",emoji:"📝",en:"The bank is across from the park", es:"El banco está frente al parque"},
          {topic:"Final Evaluation",cat:"A",catLabel:"Grammar",emoji:"📝",en:"Are they singing?", es:"¿Están ellos cantando?"},
          {topic:"Final Evaluation",cat:"B",catLabel:"Vocabulary",emoji:"📚",en:"Pilot", es:"Piloto"},
          {topic:"Final Evaluation",cat:"B",catLabel:"Vocabulary",emoji:"📚",en:"Sit → Sitting", es:"Sentarse → Sentado/a"},
          {topic:"Final Evaluation",cat:"B",catLabel:"Vocabulary",emoji:"📚",en:"Who", es:"Quién"},
          {topic:"Final Evaluation",cat:"B",catLabel:"Vocabulary",emoji:"📚",en:"Christmas", es:"Navidad"},
          {topic:"Final Evaluation",cat:"B",catLabel:"Vocabulary",emoji:"📚",en:"Ours", es:"Nuestro/a"},
          {topic:"Final Evaluation",cat:"B",catLabel:"Vocabulary",emoji:"📚",en:"Why", es:"Por qué"},
          {topic:"Final Evaluation",cat:"B",catLabel:"Vocabulary",emoji:"📚",en:"An engineer", es:"Un ingeniero"},
          {topic:"Final Evaluation",cat:"B",catLabel:"Vocabulary",emoji:"📚",en:"We exchange gifts", es:"Intercambiamos regalos"},
        ],
        games: ["finalChallenge","bingo","quizMultiple"],
        presentation: [{"objective":"Complete the final evaluation for the fourth term covering all year material.","rewards":[{"emoji":"⭐","title":"+100 XP"},{"emoji":"🏆","title":"Weekly Badge"},{"emoji":"🎯","title":"New Achievement"}],"tips":["Review can/can't: 'She can't drive'","Practice 'Where do you live?'","Review possessives: 'My sister's book', 'It's theirs'"]}],
        resources:[
          {title:"Google Forms — Evaluación Final",desc:"Digital evaluation for the fourth term",url:"https://forms.google.com/"},
          {title:"Kahoot — Final Quiz P4",desc:"Final quiz for the school year",url:"https://kahoot.com/schools-u/"},
          {title:"Quizlet — Year Final Review",desc:"Final review for the whole year",url:"https://quizlet.com/"},
        ],
      },
      {
        id:"g67-nov-s3", topic:"Feedback and end-of-school-year closing", fecha:"16 – 22 nov", badge:"Closing",
        vocab:[
          {topic:"End-of-Year Closing",cat:"A",catLabel:"Reflection",emoji:"🌟",en:"I learned a lot this year", es:"Aprendí mucho este año"},
          {topic:"End-of-Year Closing",cat:"A",catLabel:"Reflection",emoji:"🌟",en:"My favorite topic was", es:"Mi tema favorito fue"},
          {topic:"End-of-Year Closing",cat:"A",catLabel:"Reflection",emoji:"🌟",en:"I improved my English", es:"Mejoré mi inglés"},
          {topic:"End-of-Year Closing",cat:"A",catLabel:"Reflection",emoji:"🌟",en:"Next year I will", es:"El próximo año voy a"},
          {topic:"End-of-Year Closing",cat:"A",catLabel:"Reflection",emoji:"🌟",en:"My biggest achievement", es:"Mi mayor logro"},
          {topic:"End-of-Year Closing",cat:"A",catLabel:"Reflection",emoji:"🌟",en:"I am proud of myself", es:"Estoy orgulloso/a de mí mismo/a"},
          {topic:"End-of-Year Closing",cat:"A",catLabel:"Reflection",emoji:"🌟",en:"English helps me", es:"El inglés me ayuda"},
          {topic:"End-of-Year Closing",cat:"B",catLabel:"Farewell",emoji:"👋",en:"Goodbye and good luck!", es:"¡Adiós y buena suerte!"},
          {topic:"End-of-Year Closing",cat:"B",catLabel:"Farewell",emoji:"👋",en:"See you next year!", es:"¡Nos vemos el próximo año!"},
          {topic:"End-of-Year Closing",cat:"B",catLabel:"Farewell",emoji:"👋",en:"It was a great year!", es:"¡Fue un gran año!"},
          {topic:"End-of-Year Closing",cat:"B",catLabel:"Farewell",emoji:"👋",en:"Keep practising English", es:"Sigue practicando inglés"},
          {topic:"End-of-Year Closing",cat:"B",catLabel:"Farewell",emoji:"👋",en:"You did an amazing job", es:"Hiciste un trabajo increíble"},
          {topic:"End-of-Year Closing",cat:"B",catLabel:"Farewell",emoji:"👋",en:"I will miss this class", es:"Voy a extrañar esta clase"},
          {topic:"End-of-Year Closing",cat:"B",catLabel:"Farewell",emoji:"👋",en:"Thank you, teacher!", es:"¡Gracias, profesor(a)!"},
          {topic:"End-of-Year Closing",cat:"B",catLabel:"Farewell",emoji:"👋",en:"Have a great vacation!", es:"¡Que tengas unas excelentes vacaciones!"},
        ],
        games: ["finalChallenge","bingo","quizMultiple"],
        presentation: [{"objective":"Reflect on the school year, celebrate achievements, and say goodbye.","rewards":[{"emoji":"⭐","title":"+100 XP"},{"emoji":"🏆","title":"Weekly Badge"},{"emoji":"🎯","title":"New Achievement"}],"tips":["Share learning: 'I learned a lot this year'","Describe favorites: 'My favorite topic was...'","Say goodbye: 'See you next year!'"]}],
        resources:[
          {title:"Canva — Year End Card",desc:"Digital card for the end of the school year",url:"https://www.canva.com/cards/"},
          {title:"Flipgrid / Flip",desc:"Record a year-in-review reflection video in English",url:"https://info.flip.com/"},
          {title:"Google Forms — Autoevaluación Anual",desc:"Annual self-assessment and year-end closing",url:"https://forms.google.com/"},
        ],
      },
    ],
};

export default g67;
