const g8 = {
    0: [ // Enero — Grado 8
      {
        id:"g8-ene-s1", topic:"Simple Present — Affirmative", fecha:"26 ene – 1 feb",
        vocab:[
          {topic:"Repaso presente simple",cat:"A",catLabel:"Rutinas",emoji:"⏰",en:"Wake up",es:"Despertarse"},
          {topic:"Repaso presente simple",cat:"A",catLabel:"Rutinas",emoji:"🍳",en:"Cook breakfast",es:"Preparar el desayuno"},
          {topic:"Repaso presente simple",cat:"A",catLabel:"Rutinas",emoji:"🚌",en:"Take the bus",es:"Tomar el bus"},
          {topic:"Repaso presente simple",cat:"A",catLabel:"Rutinas",emoji:"📚",en:"Study",es:"Estudiar"},
          {topic:"Repaso presente simple",cat:"A",catLabel:"Rutinas",emoji:"⚽",en:"Play sports",es:"Hacer deporte"},
          {topic:"Repaso presente simple",cat:"A",catLabel:"Rutinas",emoji:"🛁",en:"Take a shower",es:"Ducharse"},
          {topic:"Repaso presente simple",cat:"A",catLabel:"Rutinas",emoji:"😴",en:"Go to bed",es:"Irse a dormir"},
          {topic:"Repaso presente simple",cat:"B",catLabel:"Oraciones",emoji:"📝",en:"She walks to school",es:"Ella camina al colegio"},
          {topic:"Repaso presente simple",cat:"B",catLabel:"Oraciones",emoji:"📝",en:"He reads every night",es:"Él lee todas las noches"},
          {topic:"Repaso presente simple",cat:"B",catLabel:"Oraciones",emoji:"📝",en:"We eat together",es:"Comemos juntos"},
          {topic:"Repaso presente simple",cat:"B",catLabel:"Oraciones",emoji:"📝",en:"They watch TV",es:"Ellos ven televisión"},
          {topic:"Repaso presente simple",cat:"B",catLabel:"Oraciones",emoji:"📝",en:"I drink coffee",es:"Yo tomo café"},
          {topic:"Repaso presente simple",cat:"B",catLabel:"Oraciones",emoji:"📝",en:"My dad drives a car",es:"Mi papá conduce un carro"},
          {topic:"Repaso presente simple",cat:"B",catLabel:"Oraciones",emoji:"📝",en:"She teaches English",es:"Ella enseña inglés"},
          {topic:"Repaso presente simple",cat:"B",catLabel:"Oraciones",emoji:"📝",en:"We live in Colombia",es:"Vivimos en Colombia"},
        ],
        games:["wordsearch","hangman","matching","scramble"],
        resources:[
          {title:"British Council — Present Simple",desc:"Ejercicios de repaso del presente simple",url:"https://learnenglish.britishcouncil.org/grammar/beginner-to-pre-intermediate/present-simple"},
          {title:"Kahoot — Daily Routines",desc:"Quiz de rutinas diarias en presente simple",url:"https://kahoot.com/schools-u/"},
          {title:"Wordwall — Simple Present",desc:"Actividades del presente simple",url:"https://wordwall.net/"},
        ],
      },
    ],
    1: [ // Febrero — Grado 8
      {
        id:"g8-feb-s1", topic:"Simple Present — Negative & Questions", fecha:"2 – 8 feb",
        vocab:[
          {topic:"Do/Does",cat:"A",catLabel:"Negativo",emoji:"❌",en:"I don't eat meat",es:"No como carne"},
          {topic:"Do/Does",cat:"A",catLabel:"Negativo",emoji:"❌",en:"She doesn't like fish",es:"A ella no le gusta el pescado"},
          {topic:"Do/Does",cat:"A",catLabel:"Negativo",emoji:"❌",en:"We don't live there",es:"No vivimos ahí"},
          {topic:"Do/Does",cat:"A",catLabel:"Negativo",emoji:"❌",en:"He doesn't speak French",es:"Él no habla francés"},
          {topic:"Do/Does",cat:"A",catLabel:"Negativo",emoji:"❌",en:"They don't play chess",es:"Ellos no juegan ajedrez"},
          {topic:"Do/Does",cat:"A",catLabel:"Negativo",emoji:"❌",en:"It doesn't rain here",es:"No llueve aquí"},
          {topic:"Do/Does",cat:"A",catLabel:"Negativo",emoji:"❌",en:"I don't understand",es:"No entiendo"},
          {topic:"Do/Does",cat:"B",catLabel:"Interrogativo",emoji:"❓",en:"Do you like pizza?",es:"¿Te gusta la pizza?"},
          {topic:"Do/Does",cat:"B",catLabel:"Interrogativo",emoji:"❓",en:"Does she work here?",es:"¿Ella trabaja aquí?"},
          {topic:"Do/Does",cat:"B",catLabel:"Interrogativo",emoji:"❓",en:"Do they have a car?",es:"¿Ellos tienen carro?"},
          {topic:"Do/Does",cat:"B",catLabel:"Interrogativo",emoji:"❓",en:"Does he play guitar?",es:"¿Él toca guitarra?"},
          {topic:"Do/Does",cat:"B",catLabel:"Interrogativo",emoji:"❓",en:"Do we need help?",es:"¿Necesitamos ayuda?"},
          {topic:"Do/Does",cat:"B",catLabel:"Interrogativo",emoji:"❓",en:"Does it work?",es:"¿Funciona?"},
          {topic:"Do/Does",cat:"B",catLabel:"Interrogativo",emoji:"❓",en:"Do you speak English?",es:"¿Hablas inglés?"},
          {topic:"Do/Does",cat:"B",catLabel:"Interrogativo",emoji:"❓",en:"Does she like music?",es:"¿A ella le gusta la música?"},
        ],
        games:["wordsearch","hangman","truefalsegame","fillblank"],
        resources:[
          {title:"British Council — Do/Does",desc:"Ejercicios con Do y Does",url:"https://learnenglish.britishcouncil.org/grammar/beginner-to-pre-intermediate/present-simple-negatives-and-questions"},
          {title:"ESL Games Plus — Do/Does Quiz",desc:"Juego de preguntas con Do y Does",url:"https://www.eslgamesplus.com/"},
          {title:"Kahoot — Do/Does",desc:"Quiz interactivo de Do/Does",url:"https://kahoot.com/schools-u/"},
        ],
      },
      {
        id:"g8-feb-s2", topic:"WH-Questions", fecha:"9 – 15 feb",
        vocab:[
          {topic:"WH-Questions G8",cat:"A",catLabel:"WH-Words",emoji:"❓",en:"What do you do?",es:"¿Qué haces?"},
          {topic:"WH-Questions G8",cat:"A",catLabel:"WH-Words",emoji:"❓",en:"Where do you work?",es:"¿Dónde trabajas?"},
          {topic:"WH-Questions G8",cat:"A",catLabel:"WH-Words",emoji:"❓",en:"When does she arrive?",es:"¿Cuándo llega ella?"},
          {topic:"WH-Questions G8",cat:"A",catLabel:"WH-Words",emoji:"❓",en:"Who does he call?",es:"¿A quién llama él?"},
          {topic:"WH-Questions G8",cat:"A",catLabel:"WH-Words",emoji:"❓",en:"Why do they leave?",es:"¿Por qué se van ellos?"},
          {topic:"WH-Questions G8",cat:"A",catLabel:"WH-Words",emoji:"❓",en:"How does it work?",es:"¿Cómo funciona?"},
          {topic:"WH-Questions G8",cat:"A",catLabel:"WH-Words",emoji:"❓",en:"How often do you exercise?",es:"¿Con qué frecuencia ejercitas?"},
          {topic:"WH-Questions G8",cat:"B",catLabel:"Respuestas",emoji:"💬",en:"I work at a school",es:"Trabajo en un colegio"},
          {topic:"WH-Questions G8",cat:"B",catLabel:"Respuestas",emoji:"💬",en:"She arrives at 8am",es:"Ella llega a las 8am"},
          {topic:"WH-Questions G8",cat:"B",catLabel:"Respuestas",emoji:"💬",en:"He calls his mom",es:"Él llama a su mamá"},
          {topic:"WH-Questions G8",cat:"B",catLabel:"Respuestas",emoji:"💬",en:"They leave because it's late",es:"Se van porque es tarde"},
          {topic:"WH-Questions G8",cat:"B",catLabel:"Respuestas",emoji:"💬",en:"It works with batteries",es:"Funciona con pilas"},
          {topic:"WH-Questions G8",cat:"B",catLabel:"Respuestas",emoji:"💬",en:"I exercise every day",es:"Ejercito todos los días"},
          {topic:"WH-Questions G8",cat:"B",catLabel:"Respuestas",emoji:"💬",en:"We live in Bogotá",es:"Vivimos en Bogotá"},
          {topic:"WH-Questions G8",cat:"B",catLabel:"Respuestas",emoji:"💬",en:"She studies at night",es:"Ella estudia de noche"},
        ],
        games:["matching","scramble","truefalsegame","fillblank"],
        resources:[
          {title:"British Council — WH-Questions",desc:"Ejercicios de WH-Questions nivel 8",url:"https://learnenglish.britishcouncil.org/grammar/beginner-to-pre-intermediate/wh-questions"},
          {title:"ESL Games Plus — Question Words",desc:"Juego de palabras interrogativas",url:"https://www.eslgamesplus.com/"},
          {title:"Mentimeter — Q&A Live",desc:"Sesión de preguntas en vivo con WH-Questions",url:"https://www.mentimeter.com/"},
        ],
      },
      {
        id:"g8-feb-s3", topic:"Possessive Adjectives", fecha:"16 – 22 feb",
        vocab:[
          {topic:"Posesivos G8",cat:"A",catLabel:"Adjetivos posesivos",emoji:"👤",en:"My family",es:"Mi familia"},
          {topic:"Posesivos G8",cat:"A",catLabel:"Adjetivos posesivos",emoji:"👤",en:"Your idea",es:"Tu idea"},
          {topic:"Posesivos G8",cat:"A",catLabel:"Adjetivos posesivos",emoji:"👤",en:"His dream",es:"Su sueño (él)"},
          {topic:"Posesivos G8",cat:"A",catLabel:"Adjetivos posesivos",emoji:"👤",en:"Her talent",es:"Su talento (ella)"},
          {topic:"Posesivos G8",cat:"A",catLabel:"Adjetivos posesivos",emoji:"👤",en:"Its color",es:"Su color (cosa)"},
          {topic:"Posesivos G8",cat:"A",catLabel:"Adjetivos posesivos",emoji:"👤",en:"Our project",es:"Nuestro proyecto"},
          {topic:"Posesivos G8",cat:"A",catLabel:"Adjetivos posesivos",emoji:"👤",en:"Their culture",es:"Su cultura (ellos)"},
          {topic:"Posesivos G8",cat:"B",catLabel:"En contexto",emoji:"📝",en:"My mother's job",es:"El trabajo de mi mamá"},
          {topic:"Posesivos G8",cat:"B",catLabel:"En contexto",emoji:"📝",en:"Her brother's school",es:"El colegio del hermano de ella"},
          {topic:"Posesivos G8",cat:"B",catLabel:"En contexto",emoji:"📝",en:"Their team's name",es:"El nombre del equipo de ellos"},
          {topic:"Posesivos G8",cat:"B",catLabel:"En contexto",emoji:"📝",en:"His friend's address",es:"La dirección del amigo de él"},
          {topic:"Posesivos G8",cat:"B",catLabel:"En contexto",emoji:"📝",en:"Our school's rules",es:"Las reglas de nuestro colegio"},
          {topic:"Posesivos G8",cat:"B",catLabel:"En contexto",emoji:"📝",en:"Your sister's birthday",es:"El cumpleaños de tu hermana"},
          {topic:"Posesivos G8",cat:"B",catLabel:"En contexto",emoji:"📝",en:"My best friend's name",es:"El nombre de mi mejor amigo"},
          {topic:"Posesivos G8",cat:"B",catLabel:"En contexto",emoji:"📝",en:"Its owner's house",es:"La casa de su dueño"},
        ],
        games:["wordsearch","hangman","matching","scramble"],
        resources:[
          {title:"British Council — Possessives",desc:"Adjetivos posesivos nivel 8",url:"https://learnenglish.britishcouncil.org/grammar/beginner-to-pre-intermediate/possessives"},
          {title:"Quizlet — Possessive Adjectives G8",desc:"Flashcards y test de posesivos",url:"https://quizlet.com/subject/possessive-adjectives/"},
          {title:"Wordwall — My/Your/His/Her/Their",desc:"Actividades de posesivos nivel intermedio",url:"https://wordwall.net/"},
        ],
      },
      {
        id:"g8-feb-s4", topic:"Adverbs of Frequency", fecha:"23 feb – 1 mar",
        vocab:[
          {topic:"Adverbios frecuencia G8",cat:"A",catLabel:"Frecuencia alta",emoji:"📊",en:"Always (100%)",es:"Siempre"},
          {topic:"Adverbios frecuencia G8",cat:"A",catLabel:"Frecuencia alta",emoji:"📊",en:"Usually (80%)",es:"Usualmente"},
          {topic:"Adverbios frecuencia G8",cat:"A",catLabel:"Frecuencia alta",emoji:"📊",en:"Often (60%)",es:"A menudo"},
          {topic:"Adverbios frecuencia G8",cat:"A",catLabel:"Frecuencia alta",emoji:"📊",en:"Sometimes (40%)",es:"A veces"},
          {topic:"Adverbios frecuencia G8",cat:"A",catLabel:"Frecuencia alta",emoji:"📊",en:"Rarely (20%)",es:"Raramente"},
          {topic:"Adverbios frecuencia G8",cat:"A",catLabel:"Frecuencia alta",emoji:"📊",en:"Seldom (10%)",es:"Pocas veces"},
          {topic:"Adverbios frecuencia G8",cat:"A",catLabel:"Frecuencia alta",emoji:"📊",en:"Never (0%)",es:"Nunca"},
          {topic:"Adverbios frecuencia G8",cat:"B",catLabel:"Posición en oración",emoji:"✏️",en:"I always brush my teeth",es:"Siempre me cepillo los dientes"},
          {topic:"Adverbios frecuencia G8",cat:"B",catLabel:"Posición en oración",emoji:"✏️",en:"She usually walks to school",es:"Ella usualmente camina al colegio"},
          {topic:"Adverbios frecuencia G8",cat:"B",catLabel:"Posición en oración",emoji:"✏️",en:"He often plays football",es:"Él a menudo juega fútbol"},
          {topic:"Adverbios frecuencia G8",cat:"B",catLabel:"Posición en oración",emoji:"✏️",en:"We sometimes eat out",es:"A veces comemos afuera"},
          {topic:"Adverbios frecuencia G8",cat:"B",catLabel:"Posición en oración",emoji:"✏️",en:"They rarely watch TV",es:"Ellos raramente ven TV"},
          {topic:"Adverbios frecuencia G8",cat:"B",catLabel:"Posición en oración",emoji:"✏️",en:"I never smoke",es:"Nunca fumo"},
          {topic:"Adverbios frecuencia G8",cat:"B",catLabel:"Posición en oración",emoji:"✏️",en:"She seldom eats fast food",es:"Ella pocas veces come comida rápida"},
          {topic:"Adverbios frecuencia G8",cat:"B",catLabel:"Posición en oración",emoji:"✏️",en:"He is always late",es:"Él siempre llega tarde"},
        ],
        games:["wordsearch","hangman","truefalsegame","fillblank"],
        resources:[
          {title:"British Council — Adverbs of Frequency",desc:"Ejercicios de adverbios de frecuencia G8",url:"https://learnenglish.britishcouncil.org/grammar/beginner-to-pre-intermediate/adverbs-of-frequency"},
          {title:"ESL Games Plus — Frequency",desc:"Juego de adverbios de frecuencia",url:"https://www.eslgamesplus.com/"},
          {title:"Canva — Habits Infographic",desc:"Crea una infografía de hábitos con adverbios",url:"https://www.canva.com/"},
        ],
      },
    ],
    2: [ // Marzo — Grado 8
      {
        id:"g8-mar-s1", topic:"Daily Routine Vocabulary", fecha:"2 – 8 mar",
        vocab:[
          {topic:"Rutina G8",cat:"A",catLabel:"Mañana",emoji:"🌅",en:"Get up early",es:"Levantarse temprano"},
          {topic:"Rutina G8",cat:"A",catLabel:"Mañana",emoji:"🌅",en:"Have a shower",es:"Ducharse"},
          {topic:"Rutina G8",cat:"A",catLabel:"Mañana",emoji:"🌅",en:"Get dressed",es:"Vestirse"},
          {topic:"Rutina G8",cat:"A",catLabel:"Mañana",emoji:"🌅",en:"Skip breakfast",es:"Saltarse el desayuno"},
          {topic:"Rutina G8",cat:"A",catLabel:"Mañana",emoji:"🌅",en:"Catch the bus",es:"Tomar el bus"},
          {topic:"Rutina G8",cat:"A",catLabel:"Mañana",emoji:"🌅",en:"Arrive at school",es:"Llegar al colegio"},
          {topic:"Rutina G8",cat:"A",catLabel:"Mañana",emoji:"🌅",en:"Check my phone",es:"Revisar el teléfono"},
          {topic:"Rutina G8",cat:"B",catLabel:"Tarde/Noche",emoji:"🌙",en:"Do homework",es:"Hacer la tarea"},
          {topic:"Rutina G8",cat:"B",catLabel:"Tarde/Noche",emoji:"🌙",en:"Have lunch",es:"Almorzar"},
          {topic:"Rutina G8",cat:"B",catLabel:"Tarde/Noche",emoji:"🌙",en:"Go to the gym",es:"Ir al gimnasio"},
          {topic:"Rutina G8",cat:"B",catLabel:"Tarde/Noche",emoji:"🌙",en:"Cook dinner",es:"Preparar la cena"},
          {topic:"Rutina G8",cat:"B",catLabel:"Tarde/Noche",emoji:"🌙",en:"Watch a series",es:"Ver una serie"},
          {topic:"Rutina G8",cat:"B",catLabel:"Tarde/Noche",emoji:"🌙",en:"Go to bed late",es:"Acostarse tarde"},
          {topic:"Rutina G8",cat:"B",catLabel:"Tarde/Noche",emoji:"🌙",en:"Set the alarm",es:"Poner la alarma"},
          {topic:"Rutina G8",cat:"B",catLabel:"Tarde/Noche",emoji:"🌙",en:"Fall asleep",es:"Quedarse dormido"},
        ],
        games:["matching","scramble","truefalsegame","fillblank"],
        resources:[
          {title:"British Council — Daily Routine",desc:"Vocabulario de rutina diaria nivel 8",url:"https://learnenglish.britishcouncil.org/"},
          {title:"Canva — My Day Poster",desc:"Infografía de rutina diaria en inglés",url:"https://www.canva.com/"},
          {title:"Flipgrid — Video Diary",desc:"Graba tu rutina diaria en inglés",url:"https://info.flip.com/"},
        ],
      },
      {
        id:"g8-mar-s2", topic:"Integrated Practice: Routine, Adverbs & WH-Questions", fecha:"9 – 15 mar",
        vocab:[
          {topic:"Práctica integrada G8",cat:"A",catLabel:"Integración",emoji:"✨",en:"What time do you wake up?",es:"¿A qué hora te despiertas?"},
          {topic:"Práctica integrada G8",cat:"A",catLabel:"Integración",emoji:"✨",en:"How often do you exercise?",es:"¿Con qué frecuencia ejercitas?"},
          {topic:"Práctica integrada G8",cat:"A",catLabel:"Integración",emoji:"✨",en:"She always has breakfast",es:"Ella siempre desayuna"},
          {topic:"Práctica integrada G8",cat:"A",catLabel:"Integración",emoji:"✨",en:"Where do you study?",es:"¿Dónde estudias?"},
          {topic:"Práctica integrada G8",cat:"A",catLabel:"Integración",emoji:"✨",en:"He rarely goes to bed early",es:"Él raramente se acuesta temprano"},
          {topic:"Práctica integrada G8",cat:"A",catLabel:"Integración",emoji:"✨",en:"Why do you skip breakfast?",es:"¿Por qué te saltas el desayuno?"},
          {topic:"Práctica integrada G8",cat:"A",catLabel:"Integración",emoji:"✨",en:"We usually catch the 7am bus",es:"Usualmente tomamos el bus de las 7am"},
          {topic:"Práctica integrada G8",cat:"B",catLabel:"Más frases",emoji:"📝",en:"How do you go to school?",es:"¿Cómo vas al colegio?"},
          {topic:"Práctica integrada G8",cat:"B",catLabel:"Más frases",emoji:"📝",en:"I never skip class",es:"Nunca falto a clase"},
          {topic:"Práctica integrada G8",cat:"B",catLabel:"Más frases",emoji:"📝",en:"Does she do homework every day?",es:"¿Ella hace la tarea todos los días?"},
          {topic:"Práctica integrada G8",cat:"B",catLabel:"Más frases",emoji:"📝",en:"They sometimes eat fast food",es:"Ellos a veces comen comida rápida"},
          {topic:"Práctica integrada G8",cat:"B",catLabel:"Más frases",emoji:"📝",en:"Who cooks in your family?",es:"¿Quién cocina en tu familia?"},
          {topic:"Práctica integrada G8",cat:"B",catLabel:"Más frases",emoji:"📝",en:"My dad always drives to work",es:"Mi papá siempre conduce al trabajo"},
          {topic:"Práctica integrada G8",cat:"B",catLabel:"Más frases",emoji:"📝",en:"What do you usually do at night?",es:"¿Qué usualmente haces en la noche?"},
          {topic:"Práctica integrada G8",cat:"B",catLabel:"Más frases",emoji:"📝",en:"She often watches series online",es:"Ella a menudo ve series en línea"},
        ],
        games:["wordsearch","hangman","matching","scramble"],
        resources:[
          {title:"Google Forms — Daily Routine Survey",desc:"Encuesta digital de rutinas de la clase",url:"https://forms.google.com/"},
          {title:"Canva — Class Habits Report",desc:"Informe visual de hábitos de la clase",url:"https://www.canva.com/"},
          {title:"Wordwall — Mixed Review G8 P1",desc:"Repaso mixto primer período grado 8",url:"https://wordwall.net/"},
        ],
      },
      {
        id:"g8-mar-s3", topic:"Written Assessment — First Period", fecha:"16 – 22 mar", badge:"Assessment",
        vocab:[
          {topic:"Evaluación P1 G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"She doesn't eat meat",es:"Ella no come carne"},
          {topic:"Evaluación P1 G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"Do they play basketball?",es:"¿Ellos juegan baloncesto?"},
          {topic:"Evaluación P1 G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"He always arrives on time",es:"Él siempre llega a tiempo"},
          {topic:"Evaluación P1 G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"What do you usually eat?",es:"¿Qué usualmente comes?"},
          {topic:"Evaluación P1 G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"Our school starts at 7am",es:"Nuestro colegio empieza a las 7am"},
          {topic:"Evaluación P1 G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"Where does she work?",es:"¿Dónde trabaja ella?"},
          {topic:"Evaluación P1 G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"They rarely watch TV",es:"Ellos raramente ven TV"},
          {topic:"Evaluación P1 G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"Get dressed",es:"Vestirse"},
          {topic:"Evaluación P1 G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"Catch the bus",es:"Tomar el bus"},
          {topic:"Evaluación P1 G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"Usually",es:"Usualmente"},
          {topic:"Evaluación P1 G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"Their project",es:"Su proyecto (ellos)"},
          {topic:"Evaluación P1 G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"Fall asleep",es:"Quedarse dormido"},
          {topic:"Evaluación P1 G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"How often",es:"Con qué frecuencia"},
          {topic:"Evaluación P1 G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"My mom's job",es:"El trabajo de mi mamá"},
          {topic:"Evaluación P1 G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"Never",es:"Nunca"},
        ],
        games:["matching","scramble","truefalsegame","fillblank"],
        resources:[
          {title:"Kahoot — Evaluación P1 G8",desc:"Quiz de evaluación primer período grado 8",url:"https://kahoot.com/schools-u/"},
          {title:"Google Forms — Exam P1 G8",desc:"Evaluación digital del primer período",url:"https://forms.google.com/"},
          {title:"Quizlet — G8 P1 Final Review",desc:"Repaso final primer período grado 8",url:"https://quizlet.com/"},
        ],
      },
      {
        id:"g8-mar-s4", topic:"Feedback & Closing — First Period", fecha:"23 – 29 mar", badge:"Feedback",
        vocab:[
          {topic:"Retroalimentación G8",cat:"A",catLabel:"Reflexión",emoji:"💡",en:"My best skill is",es:"Mi mejor habilidad es"},
          {topic:"Retroalimentación G8",cat:"A",catLabel:"Reflexión",emoji:"💡",en:"I need to work on",es:"Necesito trabajar en"},
          {topic:"Retroalimentación G8",cat:"A",catLabel:"Reflexión",emoji:"💡",en:"I improved in",es:"Mejoré en"},
          {topic:"Retroalimentación G8",cat:"A",catLabel:"Reflexión",emoji:"💡",en:"My main mistake was",es:"Mi error principal fue"},
          {topic:"Retroalimentación G8",cat:"A",catLabel:"Reflexión",emoji:"💡",en:"Next period I will",es:"El próximo período voy a"},
          {topic:"Retroalimentación G8",cat:"A",catLabel:"Reflexión",emoji:"💡",en:"I am proud of",es:"Estoy orgulloso/a de"},
          {topic:"Retroalimentación G8",cat:"A",catLabel:"Reflexión",emoji:"💡",en:"I found it difficult to",es:"Me resultó difícil"},
          {topic:"Retroalimentación G8",cat:"B",catLabel:"Metas",emoji:"🎯",en:"My goal is to",es:"Mi meta es"},
          {topic:"Retroalimentación G8",cat:"B",catLabel:"Metas",emoji:"🎯",en:"I will practice more",es:"Practicaré más"},
          {topic:"Retroalimentación G8",cat:"B",catLabel:"Metas",emoji:"🎯",en:"I will ask for help",es:"Pediré ayuda"},
          {topic:"Retroalimentación G8",cat:"B",catLabel:"Metas",emoji:"🎯",en:"I will review my notes",es:"Repasaré mis apuntes"},
          {topic:"Retroalimentación G8",cat:"B",catLabel:"Metas",emoji:"🎯",en:"Keep going!",es:"¡Sigue adelante!"},
          {topic:"Retroalimentación G8",cat:"B",catLabel:"Metas",emoji:"🎯",en:"Great effort!",es:"¡Gran esfuerzo!"},
          {topic:"Retroalimentación G8",cat:"B",catLabel:"Metas",emoji:"🎯",en:"Well done!",es:"¡Bien hecho!"},
          {topic:"Retroalimentación G8",cat:"B",catLabel:"Metas",emoji:"🎯",en:"Keep it up!",es:"¡Continúa así!"},
        ],
        games:["wordsearch","hangman","matching","scramble"],
        resources:[
          {title:"Canva — Self-Assessment Card",desc:"Tarjeta de autoevaluación grado 8",url:"https://www.canva.com/"},
          {title:"Google Forms — Reflection Form",desc:"Formulario de reflexión del período",url:"https://forms.google.com/"},
          {title:"Mentimeter — Class Feedback",desc:"Retroalimentación en tiempo real",url:"https://www.mentimeter.com/"},
        ],
      },
    ],
    3: [ // Abril — Grado 8
      {
        id:"g8-abr-s1", topic:"Comparatives & Superlatives", fecha:"6 – 12 abr",
        vocab:[
          {topic:"Comparativos G8",cat:"A",catLabel:"Comparativos",emoji:"⚖️",en:"Bigger than",es:"Más grande que"},
          {topic:"Comparativos G8",cat:"A",catLabel:"Comparativos",emoji:"⚖️",en:"Smaller than",es:"Más pequeño que"},
          {topic:"Comparativos G8",cat:"A",catLabel:"Comparativos",emoji:"⚖️",en:"More expensive than",es:"Más caro que"},
          {topic:"Comparativos G8",cat:"A",catLabel:"Comparativos",emoji:"⚖️",en:"Better than",es:"Mejor que"},
          {topic:"Comparativos G8",cat:"A",catLabel:"Comparativos",emoji:"⚖️",en:"Worse than",es:"Peor que"},
          {topic:"Comparativos G8",cat:"A",catLabel:"Comparativos",emoji:"⚖️",en:"Faster than",es:"Más rápido que"},
          {topic:"Comparativos G8",cat:"A",catLabel:"Comparativos",emoji:"⚖️",en:"More intelligent than",es:"Más inteligente que"},
          {topic:"Comparativos G8",cat:"B",catLabel:"Superlativos",emoji:"🏆",en:"The biggest",es:"El más grande"},
          {topic:"Comparativos G8",cat:"B",catLabel:"Superlativos",emoji:"🏆",en:"The most beautiful",es:"El/La más hermoso/a"},
          {topic:"Comparativos G8",cat:"B",catLabel:"Superlativos",emoji:"🏆",en:"The best",es:"El/La mejor"},
          {topic:"Comparativos G8",cat:"B",catLabel:"Superlativos",emoji:"🏆",en:"The worst",es:"El/La peor"},
          {topic:"Comparativos G8",cat:"B",catLabel:"Superlativos",emoji:"🏆",en:"The tallest",es:"El/La más alto/a"},
          {topic:"Comparativos G8",cat:"B",catLabel:"Superlativos",emoji:"🏆",en:"The most popular",es:"El/La más popular"},
          {topic:"Comparativos G8",cat:"B",catLabel:"Superlativos",emoji:"🏆",en:"The fastest",es:"El/La más rápido/a"},
          {topic:"Comparativos G8",cat:"B",catLabel:"Superlativos",emoji:"🏆",en:"The most expensive",es:"El/La más caro/a"},
        ],
        games:["wordsearch","hangman","matching","scramble"],
        resources:[
          {title:"British Council — Comparatives & Superlatives",desc:"Ejercicios de comparativos y superlativos",url:"https://learnenglish.britishcouncil.org/grammar/intermediate-to-upper-intermediate/comparatives-and-superlatives"},
          {title:"ESL Games Plus — Comparatives",desc:"Juego de adjetivos comparativos",url:"https://www.eslgamesplus.com/"},
          {title:"Mentimeter — Class Ranking",desc:"Ranking de la clase con superlativos",url:"https://www.mentimeter.com/"},
        ],
      },
      {
        id:"g8-abr-s2", topic:"Simple Past — Affirmative", fecha:"13 – 19 abr",
        vocab:[
          {topic:"Pasado simple G8",cat:"A",catLabel:"Irregulares",emoji:"⏪",en:"Go → Went",es:"Ir → Fue/Fui"},
          {topic:"Pasado simple G8",cat:"A",catLabel:"Irregulares",emoji:"⏪",en:"Have → Had",es:"Tener → Tuvo/Tuve"},
          {topic:"Pasado simple G8",cat:"A",catLabel:"Irregulares",emoji:"⏪",en:"See → Saw",es:"Ver → Vio/Vi"},
          {topic:"Pasado simple G8",cat:"A",catLabel:"Irregulares",emoji:"⏪",en:"Eat → Ate",es:"Comer → Comió/Comí"},
          {topic:"Pasado simple G8",cat:"A",catLabel:"Irregulares",emoji:"⏪",en:"Come → Came",es:"Venir → Vino/Vine"},
          {topic:"Pasado simple G8",cat:"A",catLabel:"Irregulares",emoji:"⏪",en:"Buy → Bought",es:"Comprar → Compró/Compré"},
          {topic:"Pasado simple G8",cat:"A",catLabel:"Irregulares",emoji:"⏪",en:"Take → Took",es:"Tomar → Tomó/Tomé"},
          {topic:"Pasado simple G8",cat:"B",catLabel:"Regulares",emoji:"📅",en:"Watched",es:"Vio (watched)"},
          {topic:"Pasado simple G8",cat:"B",catLabel:"Regulares",emoji:"📅",en:"Played",es:"Jugó/Jugué"},
          {topic:"Pasado simple G8",cat:"B",catLabel:"Regulares",emoji:"📅",en:"Studied",es:"Estudió/Estudié"},
          {topic:"Pasado simple G8",cat:"B",catLabel:"Regulares",emoji:"📅",en:"Walked",es:"Caminó/Caminé"},
          {topic:"Pasado simple G8",cat:"B",catLabel:"Regulares",emoji:"📅",en:"Cooked",es:"Cocinó/Cociné"},
          {topic:"Pasado simple G8",cat:"B",catLabel:"Regulares",emoji:"📅",en:"Visited",es:"Visitó/Visité"},
          {topic:"Pasado simple G8",cat:"B",catLabel:"Regulares",emoji:"📅",en:"Worked",es:"Trabajó/Trabajé"},
          {topic:"Pasado simple G8",cat:"B",catLabel:"Regulares",emoji:"📅",en:"Listened",es:"Escuchó/Escuché"},
        ],
        games:["matching","scramble","truefalsegame","fillblank"],
        resources:[
          {title:"British Council — Past Simple",desc:"Ejercicios del pasado simple grado 8",url:"https://learnenglish.britishcouncil.org/grammar/beginner-to-pre-intermediate/past-simple"},
          {title:"ESL Games Plus — Irregular Verbs",desc:"Juego de verbos irregulares",url:"https://www.eslgamesplus.com/"},
          {title:"Quizlet — Irregular Verbs G8",desc:"Flashcards de verbos irregulares",url:"https://quizlet.com/subject/irregular-verbs/"},
        ],
      },
      {
        id:"g8-abr-s3", topic:"Simple Past — Negative & Questions (Did)", fecha:"20 – 26 abr",
        vocab:[
          {topic:"Did G8",cat:"A",catLabel:"Negativo",emoji:"❌",en:"I didn't go",es:"No fui"},
          {topic:"Did G8",cat:"A",catLabel:"Negativo",emoji:"❌",en:"She didn't eat",es:"Ella no comió"},
          {topic:"Did G8",cat:"A",catLabel:"Negativo",emoji:"❌",en:"We didn't win",es:"No ganamos"},
          {topic:"Did G8",cat:"A",catLabel:"Negativo",emoji:"❌",en:"He didn't come",es:"Él no vino"},
          {topic:"Did G8",cat:"A",catLabel:"Negativo",emoji:"❌",en:"They didn't study",es:"Ellos no estudiaron"},
          {topic:"Did G8",cat:"A",catLabel:"Negativo",emoji:"❌",en:"I didn't understand",es:"No entendí"},
          {topic:"Did G8",cat:"A",catLabel:"Negativo",emoji:"❌",en:"She didn't call",es:"Ella no llamó"},
          {topic:"Did G8",cat:"B",catLabel:"Interrogativo",emoji:"❓",en:"Did you go?",es:"¿Fuiste?"},
          {topic:"Did G8",cat:"B",catLabel:"Interrogativo",emoji:"❓",en:"Did she eat?",es:"¿Comió ella?"},
          {topic:"Did G8",cat:"B",catLabel:"Interrogativo",emoji:"❓",en:"Did they win?",es:"¿Ganaron ellos?"},
          {topic:"Did G8",cat:"B",catLabel:"Interrogativo",emoji:"❓",en:"What did you do?",es:"¿Qué hiciste?"},
          {topic:"Did G8",cat:"B",catLabel:"Interrogativo",emoji:"❓",en:"Where did she go?",es:"¿A dónde fue ella?"},
          {topic:"Did G8",cat:"B",catLabel:"Interrogativo",emoji:"❓",en:"Why didn't you come?",es:"¿Por qué no viniste?"},
          {topic:"Did G8",cat:"B",catLabel:"Interrogativo",emoji:"❓",en:"Who did you see?",es:"¿A quién viste?"},
          {topic:"Did G8",cat:"B",catLabel:"Interrogativo",emoji:"❓",en:"When did it happen?",es:"¿Cuándo ocurrió?"},
        ],
        games:["wordsearch","hangman","truefalsegame","fillblank"],
        resources:[
          {title:"British Council — Past Simple Questions",desc:"Preguntas en pasado simple con Did",url:"https://learnenglish.britishcouncil.org/grammar/beginner-to-pre-intermediate/past-simple-questions-and-negatives"},
          {title:"ESL Games Plus — Did/Didn't",desc:"Juego de pasado negativo e interrogativo",url:"https://www.eslgamesplus.com/"},
          {title:"Kahoot — Past Simple G8",desc:"Quiz del pasado simple grado 8",url:"https://kahoot.com/schools-u/"},
        ],
      },
      {
        id:"g8-abr-s4", topic:"Prepositions of Time", fecha:"27 abr – 3 may",
        vocab:[
          {topic:"Preposiciones tiempo G8",cat:"A",catLabel:"In / On / At",emoji:"📅",en:"In January",es:"En enero"},
          {topic:"Preposiciones tiempo G8",cat:"A",catLabel:"In / On / At",emoji:"📅",en:"On Monday",es:"El lunes"},
          {topic:"Preposiciones tiempo G8",cat:"A",catLabel:"In / On / At",emoji:"📅",en:"At 7 o'clock",es:"A las 7 en punto"},
          {topic:"Preposiciones tiempo G8",cat:"A",catLabel:"In / On / At",emoji:"📅",en:"In the morning",es:"En la mañana"},
          {topic:"Preposiciones tiempo G8",cat:"A",catLabel:"In / On / At",emoji:"📅",en:"On weekends",es:"Los fines de semana"},
          {topic:"Preposiciones tiempo G8",cat:"A",catLabel:"In / On / At",emoji:"📅",en:"At night",es:"En la noche"},
          {topic:"Preposiciones tiempo G8",cat:"A",catLabel:"In / On / At",emoji:"📅",en:"In 2010",es:"En 2010"},
          {topic:"Preposiciones tiempo G8",cat:"B",catLabel:"Ago / Last / Next",emoji:"⏰",en:"Two days ago",es:"Hace dos días"},
          {topic:"Preposiciones tiempo G8",cat:"B",catLabel:"Ago / Last / Next",emoji:"⏰",en:"Last week",es:"La semana pasada"},
          {topic:"Preposiciones tiempo G8",cat:"B",catLabel:"Ago / Last / Next",emoji:"⏰",en:"Next month",es:"El próximo mes"},
          {topic:"Preposiciones tiempo G8",cat:"B",catLabel:"Ago / Last / Next",emoji:"⏰",en:"Yesterday",es:"Ayer"},
          {topic:"Preposiciones tiempo G8",cat:"B",catLabel:"Ago / Last / Next",emoji:"⏰",en:"Last year",es:"El año pasado"},
          {topic:"Preposiciones tiempo G8",cat:"B",catLabel:"Ago / Last / Next",emoji:"⏰",en:"A month ago",es:"Hace un mes"},
          {topic:"Preposiciones tiempo G8",cat:"B",catLabel:"Ago / Last / Next",emoji:"⏰",en:"On my birthday",es:"En mi cumpleaños"},
          {topic:"Preposiciones tiempo G8",cat:"B",catLabel:"Ago / Last / Next",emoji:"⏰",en:"At Christmas",es:"En Navidad"},
        ],
        games:["wordsearch","hangman","matching","scramble"],
        resources:[
          {title:"British Council — Prepositions of Time",desc:"In/On/At para tiempo",url:"https://learnenglish.britishcouncil.org/grammar/beginner-to-pre-intermediate/prepositions-of-time-in-on-at"},
          {title:"ESL Games Plus — Time Prepositions",desc:"Juego de preposiciones de tiempo",url:"https://www.eslgamesplus.com/"},
          {title:"Wordwall — In/On/At Time",desc:"Actividades de preposiciones de tiempo",url:"https://wordwall.net/"},
        ],
      },
    ],
    4: [ // Mayo — Grado 8
      {
        id:"g8-may-s1", topic:"Eating Habits", fecha:"4 – 10 may",
        vocab:[
          {topic:"Alimentación G8",cat:"A",catLabel:"Alimentos saludables",emoji:"🥗",en:"Vegetables",es:"Verduras"},
          {topic:"Alimentación G8",cat:"A",catLabel:"Alimentos saludables",emoji:"🍎",en:"Fruit",es:"Fruta"},
          {topic:"Alimentación G8",cat:"A",catLabel:"Alimentos saludables",emoji:"🐟",en:"Fish",es:"Pescado"},
          {topic:"Alimentación G8",cat:"A",catLabel:"Alimentos saludables",emoji:"🫘",en:"Legumes",es:"Legumbres"},
          {topic:"Alimentación G8",cat:"A",catLabel:"Alimentos saludables",emoji:"💧",en:"Water",es:"Agua"},
          {topic:"Alimentación G8",cat:"A",catLabel:"Alimentos saludables",emoji:"🌾",en:"Whole grains",es:"Granos enteros"},
          {topic:"Alimentación G8",cat:"A",catLabel:"Alimentos saludables",emoji:"🥜",en:"Nuts",es:"Nueces"},
          {topic:"Alimentación G8",cat:"B",catLabel:"Alimentos no saludables",emoji:"🍔",en:"Junk food",es:"Comida chatarra"},
          {topic:"Alimentación G8",cat:"B",catLabel:"Alimentos no saludables",emoji:"🍟",en:"Fried food",es:"Comida frita"},
          {topic:"Alimentación G8",cat:"B",catLabel:"Alimentos no saludables",emoji:"🍭",en:"Sugary drinks",es:"Bebidas azucaradas"},
          {topic:"Alimentación G8",cat:"B",catLabel:"Alimentos no saludables",emoji:"🍕",en:"Processed food",es:"Comida procesada"},
          {topic:"Alimentación G8",cat:"B",catLabel:"Alimentos no saludables",emoji:"🍫",en:"Too much sugar",es:"Demasiada azúcar"},
          {topic:"Alimentación G8",cat:"B",catLabel:"Alimentos no saludables",emoji:"🧂",en:"Too much salt",es:"Demasiada sal"},
          {topic:"Alimentación G8",cat:"B",catLabel:"Alimentos no saludables",emoji:"🍺",en:"Alcohol",es:"Alcohol"},
          {topic:"Alimentación G8",cat:"B",catLabel:"Alimentos no saludables",emoji:"☕",en:"Too much caffeine",es:"Demasiada cafeína"},
        ],
        games:["matching","scramble","truefalsegame","fillblank"],
        resources:[
          {title:"British Council — Food & Health",desc:"Vocabulario de alimentación y salud",url:"https://learnenglish.britishcouncil.org/"},
          {title:"Canva — Healthy Menu",desc:"Crea un menú saludable digital",url:"https://www.canva.com/"},
          {title:"Wordwall — Food Vocabulary",desc:"Actividades de vocabulario de alimentos",url:"https://wordwall.net/"},
        ],
      },
      {
        id:"g8-may-s2", topic:"Imperative Form", fecha:"11 – 17 may",
        vocab:[
          {topic:"Imperativo G8",cat:"A",catLabel:"Afirmativo",emoji:"✅",en:"Open the book",es:"Abre el libro"},
          {topic:"Imperativo G8",cat:"A",catLabel:"Afirmativo",emoji:"✅",en:"Listen carefully",es:"Escucha con atención"},
          {topic:"Imperativo G8",cat:"A",catLabel:"Afirmativo",emoji:"✅",en:"Sit down please",es:"Siéntate por favor"},
          {topic:"Imperativo G8",cat:"A",catLabel:"Afirmativo",emoji:"✅",en:"Write your name",es:"Escribe tu nombre"},
          {topic:"Imperativo G8",cat:"A",catLabel:"Afirmativo",emoji:"✅",en:"Be quiet",es:"Haz silencio"},
          {topic:"Imperativo G8",cat:"A",catLabel:"Afirmativo",emoji:"✅",en:"Repeat after me",es:"Repite después de mí"},
          {topic:"Imperativo G8",cat:"A",catLabel:"Afirmativo",emoji:"✅",en:"Work in pairs",es:"Trabajen en parejas"},
          {topic:"Imperativo G8",cat:"B",catLabel:"Negativo",emoji:"🚫",en:"Don't run",es:"No corras"},
          {topic:"Imperativo G8",cat:"B",catLabel:"Negativo",emoji:"🚫",en:"Don't be late",es:"No llegues tarde"},
          {topic:"Imperativo G8",cat:"B",catLabel:"Negativo",emoji:"🚫",en:"Don't use your phone",es:"No uses el teléfono"},
          {topic:"Imperativo G8",cat:"B",catLabel:"Negativo",emoji:"🚫",en:"Don't cheat",es:"No hagas trampa"},
          {topic:"Imperativo G8",cat:"B",catLabel:"Negativo",emoji:"🚫",en:"Don't forget your homework",es:"No olvides la tarea"},
          {topic:"Imperativo G8",cat:"B",catLabel:"Negativo",emoji:"🚫",en:"Don't eat in class",es:"No comas en clase"},
          {topic:"Imperativo G8",cat:"B",catLabel:"Negativo",emoji:"🚫",en:"Never give up",es:"Nunca te rindas"},
          {topic:"Imperativo G8",cat:"B",catLabel:"Negativo",emoji:"🚫",en:"Don't shout",es:"No grites"},
        ],
        games:["wordsearch","hangman","matching","scramble"],
        resources:[
          {title:"British Council — Imperatives",desc:"La forma imperativa en inglés",url:"https://learnenglish.britishcouncil.org/grammar/beginner-to-pre-intermediate/imperative"},
          {title:"ESL Games Plus — Commands",desc:"Juego de comandos en inglés",url:"https://www.eslgamesplus.com/"},
          {title:"Canva — Class Rules Poster",desc:"Crea el reglamento del aula en inglés",url:"https://www.canva.com/posters/"},
        ],
      },
      {
        id:"g8-may-s3", topic:"Integrated Practice: Past Tense and Instructions", fecha:"18 – 24 may",
        vocab:[
          {topic:"Práctica P2 G8",cat:"A",catLabel:"Pasado + Imperativo",emoji:"✨",en:"Add two eggs",es:"Agrega dos huevos"},
          {topic:"Práctica P2 G8",cat:"A",catLabel:"Pasado + Imperativo",emoji:"✨",en:"Mix well",es:"Mezcla bien"},
          {topic:"Práctica P2 G8",cat:"A",catLabel:"Pasado + Imperativo",emoji:"✨",en:"Bake for 30 minutes",es:"Hornea por 30 minutos"},
          {topic:"Práctica P2 G8",cat:"A",catLabel:"Pasado + Imperativo",emoji:"✨",en:"I cooked yesterday",es:"Cociné ayer"},
          {topic:"Práctica P2 G8",cat:"A",catLabel:"Pasado + Imperativo",emoji:"✨",en:"She baked a cake",es:"Ella horneó un pastel"},
          {topic:"Práctica P2 G8",cat:"A",catLabel:"Pasado + Imperativo",emoji:"✨",en:"Don't burn it",es:"No lo quemes"},
          {topic:"Práctica P2 G8",cat:"A",catLabel:"Pasado + Imperativo",emoji:"✨",en:"We tried a new recipe",es:"Intentamos una receta nueva"},
          {topic:"Práctica P2 G8",cat:"B",catLabel:"Más frases",emoji:"📝",en:"Cut the vegetables",es:"Corta las verduras"},
          {topic:"Práctica P2 G8",cat:"B",catLabel:"Más frases",emoji:"📝",en:"She didn't like it",es:"A ella no le gustó"},
          {topic:"Práctica P2 G8",cat:"B",catLabel:"Más frases",emoji:"📝",en:"Heat the oil first",es:"Calienta el aceite primero"},
          {topic:"Práctica P2 G8",cat:"B",catLabel:"Más frases",emoji:"📝",en:"Did you eat breakfast?",es:"¿Desayunaste?"},
          {topic:"Práctica P2 G8",cat:"B",catLabel:"Más frases",emoji:"📝",en:"Serve immediately",es:"Sirve inmediatamente"},
          {topic:"Práctica P2 G8",cat:"B",catLabel:"Más frases",emoji:"📝",en:"It tasted delicious",es:"Supo delicioso"},
          {topic:"Práctica P2 G8",cat:"B",catLabel:"Más frases",emoji:"📝",en:"Don't overcook it",es:"No lo sobrecocines"},
          {topic:"Práctica P2 G8",cat:"B",catLabel:"Más frases",emoji:"📝",en:"We ate out last night",es:"Comimos afuera anoche"},
        ],
        games:["wordsearch","hangman","truefalsegame","fillblank"],
        resources:[
          {title:"Canva — Recipe Card",desc:"Crea una receta en inglés con imperativo",url:"https://www.canva.com/"},
          {title:"British Council — Recipes",desc:"Lee y escribe recetas en inglés",url:"https://learnenglish.britishcouncil.org/"},
          {title:"Google Slides — My Recipe",desc:"Presenta tu receta favorita en inglés",url:"https://slides.google.com/"},
        ],
      },
      {
        id:"g8-may-s4", topic:"General Review of the Period", fecha:"25 – 31 may",
        vocab:[
          {topic:"Repaso P2 G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"She didn't come yesterday",es:"Ella no vino ayer"},
          {topic:"Repaso P2 G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"He is taller than his brother",es:"Él es más alto que su hermano"},
          {topic:"Repaso P2 G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"Don't eat junk food",es:"No comas comida chatarra"},
          {topic:"Repaso P2 G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"She went to the market last week",es:"Ella fue al mercado la semana pasada"},
          {topic:"Repaso P2 G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"The best restaurant in town",es:"El mejor restaurante de la ciudad"},
          {topic:"Repaso P2 G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"Did they buy tickets?",es:"¿Compraron ellos las entradas?"},
          {topic:"Repaso P2 G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"Mix all ingredients well",es:"Mezcla bien todos los ingredientes"},
          {topic:"Repaso P2 G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"Whole grains",es:"Granos enteros"},
          {topic:"Repaso P2 G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"Last night",es:"Anoche"},
          {topic:"Repaso P2 G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"More expensive than",es:"Más caro que"},
          {topic:"Repaso P2 G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"Go → Went",es:"Ir → Fue"},
          {topic:"Repaso P2 G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"The fastest",es:"El más rápido"},
          {topic:"Repaso P2 G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"On weekends",es:"Los fines de semana"},
          {topic:"Repaso P2 G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"Fried food",es:"Comida frita"},
          {topic:"Repaso P2 G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"Didn't study",es:"No estudió"},
        ],
        games:["matching","scramble","truefalsegame","fillblank"],
        resources:[
          {title:"Kahoot — Repaso P2 G8",desc:"Quiz de repaso segundo período grado 8",url:"https://kahoot.com/schools-u/"},
          {title:"Quizlet — G8 P2 Review",desc:"Repaso con flashcards segundo período",url:"https://quizlet.com/"},
          {title:"Wordwall — Mixed Review G8 P2",desc:"Actividades mixtas de repaso",url:"https://wordwall.net/"},
        ],
      },
    ],
    5: [ // Junio — Grado 8
      {
        id:"g8-jun-s1", topic:"Written Assessment for the Period", fecha:"1 – 7 jun", badge:"Evaluación",
        vocab:[
          {topic:"Evaluación P2 G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"Did you finish?",es:"¿Terminaste?"},
          {topic:"Evaluación P2 G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"She ate salad for lunch",es:"Ella comió ensalada en el almuerzo"},
          {topic:"Evaluación P2 G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"Don't forget to study",es:"No olvides estudiar"},
          {topic:"Evaluación P2 G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"He is the best student",es:"Él es el mejor estudiante"},
          {topic:"Evaluación P2 G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"We went to the cinema",es:"Fuimos al cine"},
          {topic:"Evaluación P2 G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"This book is more interesting",es:"Este libro es más interesante"},
          {topic:"Evaluación P2 G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"She bought vegetables",es:"Ella compró verduras"},
          {topic:"Evaluación P2 G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"Junk food",es:"Comida chatarra"},
          {topic:"Evaluación P2 G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"Two weeks ago",es:"Hace dos semanas"},
          {topic:"Evaluación P2 G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"Better than",es:"Mejor que"},
          {topic:"Evaluación P2 G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"See → Saw",es:"Ver → Vio"},
          {topic:"Evaluación P2 G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"Sit down",es:"Siéntate"},
          {topic:"Evaluación P2 G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"On Saturday",es:"El sábado"},
          {topic:"Evaluación P2 G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"The most popular",es:"El/La más popular"},
          {topic:"Evaluación P2 G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"Didn't go",es:"No fue"},
        ],
        games:["wordsearch","hangman","matching","scramble"],
        resources:[
          {title:"Google Forms — Exam P2 G8",desc:"Evaluación digital segundo período grado 8",url:"https://forms.google.com/"},
          {title:"Kahoot — Final Quiz P2 G8",desc:"Quiz final del segundo período",url:"https://kahoot.com/schools-u/"},
          {title:"Quizlet — G8 P2 Final",desc:"Repaso final segundo período grado 8",url:"https://quizlet.com/"},
        ],
      },
      {
        id:"g8-jun-s2", topic:"Feedback and Wrap-Up", fecha:"8 – 14 jun", badge:"Retroalimentación",
        vocab:[
          {topic:"Cierre P2 G8",cat:"A",catLabel:"Reflexión",emoji:"💡",en:"I learned to use the past tense",es:"Aprendí a usar el pasado"},
          {topic:"Cierre P2 G8",cat:"A",catLabel:"Reflexión",emoji:"💡",en:"Comparatives were challenging",es:"Los comparativos fueron desafiantes"},
          {topic:"Cierre P2 G8",cat:"A",catLabel:"Reflexión",emoji:"💡",en:"I improved my writing",es:"Mejoré mi escritura"},
          {topic:"Cierre P2 G8",cat:"A",catLabel:"Reflexión",emoji:"💡",en:"I need to memorize irregular verbs",es:"Necesito memorizar verbos irregulares"},
          {topic:"Cierre P2 G8",cat:"A",catLabel:"Reflexión",emoji:"💡",en:"My vocabulary grew a lot",es:"Mi vocabulario creció mucho"},
          {topic:"Cierre P2 G8",cat:"A",catLabel:"Reflexión",emoji:"💡",en:"Next period I will read more",es:"El próximo período leeré más"},
          {topic:"Cierre P2 G8",cat:"A",catLabel:"Reflexión",emoji:"💡",en:"I understand English better now",es:"Entiendo el inglés mejor ahora"},
          {topic:"Cierre P2 G8",cat:"B",catLabel:"Compromisos",emoji:"🎯",en:"Study every day",es:"Estudia todos los días"},
          {topic:"Cierre P2 G8",cat:"B",catLabel:"Compromisos",emoji:"🎯",en:"Practice speaking",es:"Practica hablando"},
          {topic:"Cierre P2 G8",cat:"B",catLabel:"Compromisos",emoji:"🎯",en:"Review irregular verbs",es:"Repasa verbos irregulares"},
          {topic:"Cierre P2 G8",cat:"B",catLabel:"Compromisos",emoji:"🎯",en:"Watch series in English",es:"Ve series en inglés"},
          {topic:"Cierre P2 G8",cat:"B",catLabel:"Compromisos",emoji:"🎯",en:"Read short texts",es:"Lee textos cortos"},
          {topic:"Cierre P2 G8",cat:"B",catLabel:"Compromisos",emoji:"🎯",en:"Use a vocabulary notebook",es:"Usa un cuaderno de vocabulario"},
          {topic:"Cierre P2 G8",cat:"B",catLabel:"Compromisos",emoji:"🎯",en:"Speak in English in class",es:"Habla en inglés en clase"},
          {topic:"Cierre P2 G8",cat:"B",catLabel:"Compromisos",emoji:"🎯",en:"Ask when you don't understand",es:"Pregunta cuando no entiendas"},
        ],
        games:["wordsearch","hangman","truefalsegame","fillblank"],
        resources:[
          {title:"Canva — My English Goals",desc:"Cartel de metas de inglés para el próximo período",url:"https://www.canva.com/"},
          {title:"Google Forms — Self-Assessment P2",desc:"Autoevaluación digital del segundo período",url:"https://forms.google.com/"},
          {title:"Mentimeter — Reflection Wall",desc:"Muro de reflexiones del período en tiempo real",url:"https://www.mentimeter.com/"},
        ],
      },
    ],
    6: [ // Julio — G8 — P3 (10 semanas: 6 jul – 13 sep)
      {
        id:"g8-jul-s1", topic:"Weather and Seasons", fecha:"6 – 12 jul",
        vocab:[
          {topic:"Clima G8",cat:"A",catLabel:"Estaciones",emoji:"🌤️",en:"Spring",es:"Primavera"},
          {topic:"Clima G8",cat:"A",catLabel:"Estaciones",emoji:"☀️",en:"Summer",es:"Verano"},
          {topic:"Clima G8",cat:"A",catLabel:"Estaciones",emoji:"🍂",en:"Autumn / Fall",es:"Otoño"},
          {topic:"Clima G8",cat:"A",catLabel:"Estaciones",emoji:"❄️",en:"Winter",es:"Invierno"},
          {topic:"Clima G8",cat:"A",catLabel:"Estaciones",emoji:"🌧️",en:"Rainy season",es:"Temporada de lluvias"},
          {topic:"Clima G8",cat:"A",catLabel:"Estaciones",emoji:"🌵",en:"Dry season",es:"Temporada seca"},
          {topic:"Clima G8",cat:"A",catLabel:"Estaciones",emoji:"🌡️",en:"Temperature",es:"Temperatura"},
          {topic:"Clima G8",cat:"B",catLabel:"Clima",emoji:"⛅",en:"It is cloudy",es:"Está nublado"},
          {topic:"Clima G8",cat:"B",catLabel:"Clima",emoji:"🌩️",en:"It is stormy",es:"Hay tormenta"},
          {topic:"Clima G8",cat:"B",catLabel:"Clima",emoji:"🌨️",en:"It is snowing",es:"Está nevando"},
          {topic:"Clima G8",cat:"B",catLabel:"Clima",emoji:"🌬️",en:"It is windy",es:"Hace viento"},
          {topic:"Clima G8",cat:"B",catLabel:"Clima",emoji:"🌈",en:"It is humid",es:"Está húmedo"},
          {topic:"Clima G8",cat:"B",catLabel:"Clima",emoji:"🥵",en:"It is boiling hot",es:"Hace un calor sofocante"},
          {topic:"Clima G8",cat:"B",catLabel:"Clima",emoji:"🥶",en:"It is freezing",es:"Está helando"},
          {topic:"Clima G8",cat:"B",catLabel:"Clima",emoji:"🌦️",en:"What is the weather like?",es:"¿Cómo está el tiempo?"},
        ],
        games:["wordsearch","hangman","matching","scramble"],
        resources:[
          {title:"British Council — Weather",desc:"Vocabulario del clima en inglés",url:"https://learnenglish.britishcouncil.org/"},
          {title:"Wordwall — Weather Vocabulary",desc:"Actividades del vocabulario del clima",url:"https://wordwall.net/"},
          {title:"Canva — Weather Report",desc:"Crea un reporte del tiempo en inglés",url:"https://www.canva.com/"},
        ],
      },
      {
        id:"g8-jul-s2", topic:"Future with 'going to'", fecha:"13 – 19 jul",
        vocab:[
          {topic:"Going to G8",cat:"A",catLabel:"Afirmativo",emoji:"📋",en:"I am going to study",es:"Voy a estudiar"},
          {topic:"Going to G8",cat:"A",catLabel:"Afirmativo",emoji:"📋",en:"She is going to travel",es:"Ella va a viajar"},
          {topic:"Going to G8",cat:"A",catLabel:"Afirmativo",emoji:"📋",en:"They are going to win",es:"Ellos van a ganar"},
          {topic:"Going to G8",cat:"A",catLabel:"Afirmativo",emoji:"📋",en:"He is going to cook dinner",es:"Él va a cocinar la cena"},
          {topic:"Going to G8",cat:"A",catLabel:"Afirmativo",emoji:"📋",en:"We are going to celebrate",es:"Vamos a celebrar"},
          {topic:"Going to G8",cat:"A",catLabel:"Afirmativo",emoji:"📋",en:"It is going to rain",es:"Va a llover"},
          {topic:"Going to G8",cat:"A",catLabel:"Afirmativo",emoji:"📋",en:"I am going to be a doctor",es:"Voy a ser médico/a"},
          {topic:"Going to G8",cat:"B",catLabel:"Negativo e interrogativo",emoji:"❓",en:"He isn't going to eat",es:"Él no va a comer"},
          {topic:"Going to G8",cat:"B",catLabel:"Negativo e interrogativo",emoji:"❓",en:"Are you going to come?",es:"¿Vas a venir?"},
          {topic:"Going to G8",cat:"B",catLabel:"Negativo e interrogativo",emoji:"❓",en:"What are you going to do?",es:"¿Qué vas a hacer?"},
          {topic:"Going to G8",cat:"B",catLabel:"Negativo e interrogativo",emoji:"❓",en:"It's not going to be easy",es:"No va a ser fácil"},
          {topic:"Going to G8",cat:"B",catLabel:"Negativo e interrogativo",emoji:"❓",en:"Is she going to study?",es:"¿Ella va a estudiar?"},
          {topic:"Going to G8",cat:"B",catLabel:"Negativo e interrogativo",emoji:"❓",en:"They aren't going to play",es:"Ellos no van a jugar"},
          {topic:"Going to G8",cat:"B",catLabel:"Negativo e interrogativo",emoji:"❓",en:"Where are you going to go?",es:"¿A dónde vas a ir?"},
          {topic:"Going to G8",cat:"B",catLabel:"Negativo e interrogativo",emoji:"❓",en:"It's going to be fun!",es:"¡Va a ser divertido!"},
        ],
        games:["matching","scramble","truefalsegame","fillblank"],
        resources:[
          {title:"British Council — Going to",desc:"Futuro con going to",url:"https://learnenglish.britishcouncil.org/grammar/beginner-to-pre-intermediate/be-going-to"},
          {title:"ESL Games Plus — Going to",desc:"Juego de futuro con going to",url:"https://www.eslgamesplus.com/"},
          {title:"Kahoot — Going to Quiz",desc:"Quiz de going to grado 8",url:"https://kahoot.com/schools-u/"},
        ],
      },
      {
        id:"g8-jul-s3", topic:"Simple Future with 'will'", fecha:"20 – 26 jul",
        vocab:[
          {topic:"Will G8",cat:"A",catLabel:"Afirmativo",emoji:"🚀",en:"I will help you",es:"Te ayudaré"},
          {topic:"Will G8",cat:"A",catLabel:"Afirmativo",emoji:"🚀",en:"She will be a nurse",es:"Ella será enfermera"},
          {topic:"Will G8",cat:"A",catLabel:"Afirmativo",emoji:"🚀",en:"It will be sunny",es:"Estará soleado"},
          {topic:"Will G8",cat:"A",catLabel:"Afirmativo",emoji:"🚀",en:"They will arrive at 6",es:"Ellos llegarán a las 6"},
          {topic:"Will G8",cat:"A",catLabel:"Afirmativo",emoji:"🚀",en:"We will win the game",es:"Ganaremos el partido"},
          {topic:"Will G8",cat:"A",catLabel:"Afirmativo",emoji:"🚀",en:"I'll call you later",es:"Te llamaré más tarde"},
          {topic:"Will G8",cat:"A",catLabel:"Afirmativo",emoji:"🚀",en:"The world will change",es:"El mundo cambiará"},
          {topic:"Will G8",cat:"B",catLabel:"Negativo e interrogativo",emoji:"❓",en:"She won't come",es:"Ella no vendrá"},
          {topic:"Will G8",cat:"B",catLabel:"Negativo e interrogativo",emoji:"❓",en:"Will you help me?",es:"¿Me ayudarás?"},
          {topic:"Will G8",cat:"B",catLabel:"Negativo e interrogativo",emoji:"❓",en:"I won't be late",es:"No llegaré tarde"},
          {topic:"Will G8",cat:"B",catLabel:"Negativo e interrogativo",emoji:"❓",en:"Will it rain tomorrow?",es:"¿Lloverá mañana?"},
          {topic:"Will G8",cat:"B",catLabel:"Negativo e interrogativo",emoji:"❓",en:"They won't understand",es:"Ellos no entenderán"},
          {topic:"Will G8",cat:"B",catLabel:"Negativo e interrogativo",emoji:"❓",en:"Who will win?",es:"¿Quién ganará?"},
          {topic:"Will G8",cat:"B",catLabel:"Negativo e interrogativo",emoji:"❓",en:"I think it will snow",es:"Creo que nevará"},
          {topic:"Will G8",cat:"B",catLabel:"Negativo e interrogativo",emoji:"❓",en:"Won't you join us?",es:"¿No te unirás a nosotros?"},
        ],
        games:["wordsearch","hangman","truefalsegame","fillblank"],
        resources:[
          {title:"British Council — Will",desc:"Futuro con will en inglés",url:"https://learnenglish.britishcouncil.org/grammar/beginner-to-pre-intermediate/will"},
          {title:"ESL Games Plus — Will Future",desc:"Juego del futuro con will",url:"https://www.eslgamesplus.com/"},
          {title:"Wordwall — Will vs Going to",desc:"Actividades will vs going to",url:"https://wordwall.net/"},
        ],
      },
      {
        id:"g8-jul-s4", topic:"Comparing 'going to' and 'will'", fecha:"27 jul – 2 ago",
        vocab:[
          {topic:"Going to vs Will G8",cat:"A",catLabel:"Diferencias",emoji:"⚖️",en:"I will answer the phone (decision now)",es:"Contestaré el teléfono (decisión espontánea)"},
          {topic:"Going to vs Will G8",cat:"A",catLabel:"Diferencias",emoji:"⚖️",en:"I'm going to study (plan before)",es:"Voy a estudiar (plan previo)"},
          {topic:"Going to vs Will G8",cat:"A",catLabel:"Diferencias",emoji:"⚖️",en:"Look! It's going to rain (evidence)",es:"¡Mira! Va a llover (evidencia)"},
          {topic:"Going to vs Will G8",cat:"A",catLabel:"Diferencias",emoji:"⚖️",en:"I think it will be cold",es:"Creo que hará frío (predicción)"},
          {topic:"Going to vs Will G8",cat:"A",catLabel:"Diferencias",emoji:"⚖️",en:"She is going to have a baby",es:"Ella va a tener un bebé (plan/evidencia)"},
          {topic:"Going to vs Will G8",cat:"A",catLabel:"Diferencias",emoji:"⚖️",en:"I'll help you with that",es:"Te ayudaré con eso (ofrecimiento)"},
          {topic:"Going to vs Will G8",cat:"A",catLabel:"Diferencias",emoji:"⚖️",en:"We are going to visit Paris",es:"Vamos a visitar París (plan)"},
          {topic:"Going to vs Will G8",cat:"B",catLabel:"Práctica",emoji:"📝",en:"Promise: I will never lie",es:"Promesa: Nunca mentiré"},
          {topic:"Going to vs Will G8",cat:"B",catLabel:"Práctica",emoji:"📝",en:"Prediction: It will be hot",es:"Predicción: Hará calor"},
          {topic:"Going to vs Will G8",cat:"B",catLabel:"Práctica",emoji:"📝",en:"Plan: I'm going to exercise",es:"Plan: Voy a ejercitar"},
          {topic:"Going to vs Will G8",cat:"B",catLabel:"Práctica",emoji:"📝",en:"Offer: I'll carry that for you",es:"Ofrecimiento: Lo llevaré por ti"},
          {topic:"Going to vs Will G8",cat:"B",catLabel:"Práctica",emoji:"📝",en:"Evidence: She's going to fall",es:"Evidencia: Ella va a caer"},
          {topic:"Going to vs Will G8",cat:"B",catLabel:"Práctica",emoji:"📝",en:"Decision now: I'll have the soup",es:"Decisión ahora: Tomaré la sopa"},
          {topic:"Going to vs Will G8",cat:"B",catLabel:"Práctica",emoji:"📝",en:"Prior plan: We're going to move",es:"Plan previo: Vamos a mudarnos"},
          {topic:"Going to vs Will G8",cat:"B",catLabel:"Práctica",emoji:"📝",en:"Refusal: I won't do it",es:"Negativa: No lo haré"},
        ],
        games:["matching","scramble","truefalsegame","fillblank"],
        resources:[
          {title:"British Council — Will vs Going to",desc:"Diferencia entre will y going to",url:"https://learnenglish.britishcouncil.org/grammar/intermediate-to-upper-intermediate/will-and-going-to"},
          {title:"ESL Games Plus — Future Comparison",desc:"Juego comparativo del futuro",url:"https://www.eslgamesplus.com/"},
          {title:"Kahoot — Will vs Going to",desc:"Quiz comparativo del futuro G8",url:"https://kahoot.com/schools-u/"},
        ],
      },
    ],
    7: [ // Agosto — G8
      {
        id:"g8-ago-s1", topic:"Future Plans and Predictions", fecha:"3 – 9 ago",
        vocab:[
          {topic:"Planes futuro G8",cat:"A",catLabel:"Planes",emoji:"📅",en:"Next year I will study harder",es:"El próximo año estudiaré más"},
          {topic:"Planes futuro G8",cat:"A",catLabel:"Planes",emoji:"📅",en:"I am going to join a club",es:"Voy a unirme a un club"},
          {topic:"Planes futuro G8",cat:"A",catLabel:"Planes",emoji:"📅",en:"She will become a scientist",es:"Ella se convertirá en científica"},
          {topic:"Planes futuro G8",cat:"A",catLabel:"Planes",emoji:"📅",en:"We are going to save money",es:"Vamos a ahorrar dinero"},
          {topic:"Planes futuro G8",cat:"A",catLabel:"Planes",emoji:"📅",en:"They will travel to Europe",es:"Ellos viajarán a Europa"},
          {topic:"Planes futuro G8",cat:"A",catLabel:"Planes",emoji:"📅",en:"I'm going to learn to cook",es:"Voy a aprender a cocinar"},
          {topic:"Planes futuro G8",cat:"A",catLabel:"Planes",emoji:"📅",en:"He will be famous one day",es:"Él será famoso algún día"},
          {topic:"Planes futuro G8",cat:"B",catLabel:"Predicciones",emoji:"🔮",en:"In the future, robots will help us",es:"En el futuro, los robots nos ayudarán"},
          {topic:"Planes futuro G8",cat:"B",catLabel:"Predicciones",emoji:"🔮",en:"Cars will fly in 2050",es:"Los carros volarán en 2050"},
          {topic:"Planes futuro G8",cat:"B",catLabel:"Predicciones",emoji:"🔮",en:"Technology will change education",es:"La tecnología cambiará la educación"},
          {topic:"Planes futuro G8",cat:"B",catLabel:"Predicciones",emoji:"🔮",en:"People will live longer",es:"Las personas vivirán más tiempo"},
          {topic:"Planes futuro G8",cat:"B",catLabel:"Predicciones",emoji:"🔮",en:"It is going to be a great year",es:"Va a ser un gran año"},
          {topic:"Planes futuro G8",cat:"B",catLabel:"Predicciones",emoji:"🔮",en:"The economy will improve",es:"La economía mejorará"},
          {topic:"Planes futuro G8",cat:"B",catLabel:"Predicciones",emoji:"🔮",en:"Climate will get warmer",es:"El clima se volverá más cálido"},
          {topic:"Planes futuro G8",cat:"B",catLabel:"Predicciones",emoji:"🔮",en:"What will the world look like?",es:"¿Cómo se verá el mundo?"},
        ],
        games:["wordsearch","hangman","matching","scramble"],
        resources:[
          {title:"British Council — Future Plans",desc:"Planes y predicciones en inglés",url:"https://learnenglish.britishcouncil.org/"},
          {title:"Canva — My Future Vision",desc:"Infografía de planes para el futuro",url:"https://www.canva.com/"},
          {title:"Mentimeter — Class Predictions",desc:"Predicciones del grupo en tiempo real",url:"https://www.mentimeter.com/"},
        ],
      },
      {
        id:"g8-ago-s2", topic:"General Review", fecha:"10 – 16 ago",
        vocab:[
          {topic:"Repaso P3 G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"It was rainy last Monday",es:"Estuvo lluvioso el lunes pasado"},
          {topic:"Repaso P3 G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"She is going to be a doctor",es:"Ella va a ser médica"},
          {topic:"Repaso P3 G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"I think it will snow tomorrow",es:"Creo que nevará mañana"},
          {topic:"Repaso P3 G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"What are you going to do?",es:"¿Qué vas a hacer?"},
          {topic:"Repaso P3 G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"It is freezing outside",es:"Está helando afuera"},
          {topic:"Repaso P3 G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"Will you help me?",es:"¿Me ayudarás?"},
          {topic:"Repaso P3 G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"Look! It's going to rain",es:"¡Mira! Va a llover"},
          {topic:"Repaso P3 G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"Autumn",es:"Otoño"},
          {topic:"Repaso P3 G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"Won't come",es:"No vendrá"},
          {topic:"Repaso P3 G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"Going to study",es:"Va a estudiar"},
          {topic:"Repaso P3 G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"Stormy",es:"Tormentoso"},
          {topic:"Repaso P3 G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"I'll call you",es:"Te llamaré"},
          {topic:"Repaso P3 G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"Dry season",es:"Temporada seca"},
          {topic:"Repaso P3 G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"Technology will change",es:"La tecnología cambiará"},
          {topic:"Repaso P3 G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"Is she going to travel?",es:"¿Ella va a viajar?"},
        ],
        games:["matching","scramble","truefalsegame","fillblank"],
        resources:[
          {title:"Kahoot — Repaso P3 G8",desc:"Quiz de repaso tercer período G8",url:"https://kahoot.com/schools-u/"},
          {title:"Quizlet — G8 P3 Review",desc:"Repaso con flashcards del período 3",url:"https://quizlet.com/"},
          {title:"Wordwall — Mixed Review G8 P3",desc:"Actividades mixtas de repaso P3",url:"https://wordwall.net/"},
        ],
      },
      {
        id:"g8-ago-s3", topic:"Preparation for English's Day (Week 1)", fecha:"17 – 23 ago", badge:"English's Day prep",
        vocab:[
          {topic:"English's Day G8 S1",cat:"A",catLabel:"Presentación",emoji:"🎤",en:"Ladies and gentlemen",es:"Damas y caballeros"},
          {topic:"English's Day G8 S1",cat:"A",catLabel:"Presentación",emoji:"🎤",en:"I would like to present",es:"Me gustaría presentar"},
          {topic:"English's Day G8 S1",cat:"A",catLabel:"Presentación",emoji:"🎤",en:"My topic today is",es:"Mi topic hoy es"},
          {topic:"English's Day G8 S1",cat:"A",catLabel:"Presentación",emoji:"🎤",en:"According to my research",es:"Según mi investigación"},
          {topic:"English's Day G8 S1",cat:"A",catLabel:"Presentación",emoji:"🎤",en:"As you can see on the slide",es:"Como pueden ver en la diapositiva"},
          {topic:"English's Day G8 S1",cat:"A",catLabel:"Presentación",emoji:"🎤",en:"To conclude",es:"Para concluir"},
          {topic:"English's Day G8 S1",cat:"A",catLabel:"Presentación",emoji:"🎤",en:"Does anyone have questions?",es:"¿Alguien tiene preguntas?"},
          {topic:"English's Day G8 S1",cat:"B",catLabel:"Conectores",emoji:"🔗",en:"Furthermore",es:"Además"},
          {topic:"English's Day G8 S1",cat:"B",catLabel:"Conectores",emoji:"🔗",en:"However",es:"Sin embargo"},
          {topic:"English's Day G8 S1",cat:"B",catLabel:"Conectores",emoji:"🔗",en:"On the other hand",es:"Por otro lado"},
          {topic:"English's Day G8 S1",cat:"B",catLabel:"Conectores",emoji:"🔗",en:"As a result",es:"Como resultado"},
          {topic:"English's Day G8 S1",cat:"B",catLabel:"Conectores",emoji:"🔗",en:"For instance",es:"Por ejemplo"},
          {topic:"English's Day G8 S1",cat:"B",catLabel:"Conectores",emoji:"🔗",en:"In my opinion",es:"En mi opinión"},
          {topic:"English's Day G8 S1",cat:"B",catLabel:"Conectores",emoji:"🔗",en:"To summarize",es:"Para resumir"},
          {topic:"English's Day G8 S1",cat:"B",catLabel:"Conectores",emoji:"🔗",en:"I appreciate your attention",es:"Agradezco su atención"},
        ],
        games:["wordsearch","hangman","matching","scramble"],
        resources:[
          {title:"Canva — Presentation G8",desc:"Plantilla para English's Day grado 8",url:"https://www.canva.com/presentations/"},
          {title:"Google Slides — My Topic",desc:"Presenta tu topic en Google Slides",url:"https://slides.google.com/"},
          {title:"British Council — Presentations",desc:"Consejos para presentaciones en inglés",url:"https://learnenglish.britishcouncil.org/"},
        ],
      },
      {
        id:"g8-ago-s4", topic:"Preparation for English's Day (Week 2)", fecha:"24 – 30 ago", badge:"English's Day prep",
        vocab:[
          {topic:"English's Day G8 S2",cat:"A",catLabel:"Práctica oral",emoji:"🗣️",en:"Speak clearly and slowly",es:"Habla claro y despacio"},
          {topic:"English's Day G8 S2",cat:"A",catLabel:"Práctica oral",emoji:"🗣️",en:"Maintain eye contact",es:"Mantén contacto visual"},
          {topic:"English's Day G8 S2",cat:"A",catLabel:"Práctica oral",emoji:"🗣️",en:"Use body language",es:"Usa lenguaje corporal"},
          {topic:"English's Day G8 S2",cat:"A",catLabel:"Práctica oral",emoji:"🗣️",en:"Project your voice",es:"Proyecta tu voz"},
          {topic:"English's Day G8 S2",cat:"A",catLabel:"Práctica oral",emoji:"🗣️",en:"Pause for effect",es:"Haz pausas para dar énfasis"},
          {topic:"English's Day G8 S2",cat:"A",catLabel:"Práctica oral",emoji:"🗣️",en:"Smile and be confident",es:"Sonríe y sé seguro/a"},
          {topic:"English's Day G8 S2",cat:"A",catLabel:"Práctica oral",emoji:"🗣️",en:"Practice makes perfect",es:"La práctica hace al maestro"},
          {topic:"English's Day G8 S2",cat:"B",catLabel:"Autoevaluación",emoji:"⭐",en:"I did well in",es:"Lo hice bien en"},
          {topic:"English's Day G8 S2",cat:"B",catLabel:"Autoevaluación",emoji:"⭐",en:"I need to improve my",es:"Necesito mejorar mi"},
          {topic:"English's Day G8 S2",cat:"B",catLabel:"Autoevaluación",emoji:"⭐",en:"My best part was",es:"Mi mejor parte fue"},
          {topic:"English's Day G8 S2",cat:"B",catLabel:"Autoevaluación",emoji:"⭐",en:"Next time I will",es:"La próxima vez voy a"},
          {topic:"English's Day G8 S2",cat:"B",catLabel:"Autoevaluación",emoji:"⭐",en:"I feel confident about",es:"Me siento seguro/a sobre"},
          {topic:"English's Day G8 S2",cat:"B",catLabel:"Autoevaluación",emoji:"⭐",en:"I learned that",es:"Aprendí que"},
          {topic:"English's Day G8 S2",cat:"B",catLabel:"Autoevaluación",emoji:"⭐",en:"I am proud of",es:"Estoy orgulloso/a de"},
          {topic:"English's Day G8 S2",cat:"B",catLabel:"Autoevaluación",emoji:"⭐",en:"My weakness is",es:"Mi debilidad es"},
        ],
        games:["matching","scramble","truefalsegame","fillblank"],
        resources:[
          {title:"Flipgrid — Practice Video",desc:"Graba tu práctica para English's Day",url:"https://info.flip.com/"},
          {title:"Canva — Self-Assessment Card",desc:"Tarjeta de autoevaluación del English's Day",url:"https://www.canva.com/"},
          {title:"Google Forms — Peer Feedback",desc:"Coevaluación digital de presentaciones",url:"https://forms.google.com/"},
        ],
      },
    ],
    8: [ // Septiembre — G8
      {
        id:"g8-sep-s1", topic:"English's Day Presentation (Sept. 4)", fecha:"31 ago – 6 sep", badge:"English's Day",
        vocab:[
          {topic:"English's Day G8 Final",cat:"A",catLabel:"Reflexión",emoji:"🎤",en:"My presentation went well",es:"Mi presentación salió bien"},
          {topic:"English's Day G8 Final",cat:"A",catLabel:"Reflexión",emoji:"🎤",en:"I felt confident",es:"Me sentí seguro/a"},
          {topic:"English's Day G8 Final",cat:"A",catLabel:"Reflexión",emoji:"🎤",en:"The audience was engaged",es:"El público estaba atento"},
          {topic:"English's Day G8 Final",cat:"A",catLabel:"Reflexión",emoji:"🎤",en:"I should have practiced more",es:"Debería haber practicado más"},
          {topic:"English's Day G8 Final",cat:"A",catLabel:"Reflexión",emoji:"🎤",en:"My classmates presented brilliantly",es:"Mis compañeros presentaron brillantemente"},
          {topic:"English's Day G8 Final",cat:"A",catLabel:"Reflexión",emoji:"🎤",en:"Public speaking builds confidence",es:"Hablar en público genera confianza"},
          {topic:"English's Day G8 Final",cat:"A",catLabel:"Reflexión",emoji:"🎤",en:"It was a valuable experience",es:"Fue una experiencia valiosa"},
          {topic:"English's Day G8 Final",cat:"B",catLabel:"Logros",emoji:"🌟",en:"I expressed my ideas clearly",es:"Expresé mis ideas claramente"},
          {topic:"English's Day G8 Final",cat:"B",catLabel:"Logros",emoji:"🌟",en:"I used academic language",es:"Usé lenguaje académico"},
          {topic:"English's Day G8 Final",cat:"B",catLabel:"Logros",emoji:"🌟",en:"My topic was well-researched",es:"Mi topic estaba bien investigado"},
          {topic:"English's Day G8 Final",cat:"B",catLabel:"Logros",emoji:"🌟",en:"Congratulations to everyone",es:"Felicitaciones a todos"},
          {topic:"English's Day G8 Final",cat:"B",catLabel:"Logros",emoji:"🌟",en:"Next time I will do better",es:"La próxima vez lo haré mejor"},
          {topic:"English's Day G8 Final",cat:"B",catLabel:"Logros",emoji:"🌟",en:"English is the world's language",es:"El inglés es el idioma del mundo"},
          {topic:"English's Day G8 Final",cat:"B",catLabel:"Logros",emoji:"🌟",en:"Thank you for listening",es:"Gracias por escuchar"},
          {topic:"English's Day G8 Final",cat:"B",catLabel:"Logros",emoji:"🌟",en:"I am proud of my work",es:"Estoy orgulloso/a de mi trabajo"},
        ],
        games:["wordsearch","hangman","truefalsegame","fillblank"],
        resources:[
          {title:"Canva — Reflection Poster G8",desc:"Reflexión del English's Day grado 8",url:"https://www.canva.com/posters/"},
          {title:"Flipgrid — Year Reflection Video",desc:"Video de reflexión del English's Day",url:"https://info.flip.com/"},
          {title:"Google Forms — Self-Assessment ED",desc:"Autoevaluación del English's Day",url:"https://forms.google.com/"},
        ],
      },
      {
        id:"g8-sep-s2", topic:"Assessment and Feedback for the Period", fecha:"7 – 13 sep", badge:"Evaluación",
        vocab:[
          {topic:"Evaluación P3 G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"She is going to be a nurse",es:"Ella va a ser enfermera"},
          {topic:"Evaluación P3 G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"It will be stormy tomorrow",es:"Mañana habrá tormenta"},
          {topic:"Evaluación P3 G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"I won't be late, I promise",es:"No llegaré tarde, lo prometo"},
          {topic:"Evaluación P3 G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"Are they going to travel?",es:"¿Ellos van a viajar?"},
          {topic:"Evaluación P3 G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"Look! It's going to rain!",es:"¡Mira! ¡Va a llover!"},
          {topic:"Evaluación P3 G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"Technology will change our lives",es:"La tecnología cambiará nuestras vidas"},
          {topic:"Evaluación P3 G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"What is the weather like today?",es:"¿Cómo está el tiempo hoy?"},
          {topic:"Evaluación P3 G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"Rainy season",es:"Temporada de lluvias"},
          {topic:"Evaluación P3 G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"Going to cook",es:"Va a cocinar"},
          {topic:"Evaluación P3 G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"Won't understand",es:"No entenderá"},
          {topic:"Evaluación P3 G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"In my opinion",es:"En mi opinión"},
          {topic:"Evaluación P3 G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"Freezing cold",es:"Helado"},
          {topic:"Evaluación P3 G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"As a result",es:"Como resultado"},
          {topic:"Evaluación P3 G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"Will become",es:"Se convertirá"},
          {topic:"Evaluación P3 G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"It's going to be fun",es:"Va a ser divertido"},
        ],
        games:["matching","scramble","truefalsegame","fillblank"],
        resources:[
          {title:"Kahoot — Evaluación P3 G8",desc:"Quiz de evaluación tercer período G8",url:"https://kahoot.com/schools-u/"},
          {title:"Google Forms — Exam P3 G8",desc:"Evaluación digital del tercer período",url:"https://forms.google.com/"},
          {title:"Quizlet — G8 P3 Final Review",desc:"Repaso final tercer período G8",url:"https://quizlet.com/"},
        ],
      },
    ],
    9: [ // Octubre — G8 — P4 (receso 5-11 oct)
      {
        id:"g8-sep-p4-s1", topic:"Students' Duties and Rights", fecha:"14 – 20 sep",
        vocab:[
          {topic:"Deberes G8",cat:"A",catLabel:"Derechos",emoji:"⚖️",en:"Right to education",es:"Derecho a la educación"},
          {topic:"Deberes G8",cat:"A",catLabel:"Derechos",emoji:"⚖️",en:"Right to express yourself",es:"Derecho a expresarte"},
          {topic:"Deberes G8",cat:"A",catLabel:"Derechos",emoji:"⚖️",en:"Right to be respected",es:"Derecho a ser respetado/a"},
          {topic:"Deberes G8",cat:"A",catLabel:"Derechos",emoji:"⚖️",en:"Right to participate",es:"Derecho a participar"},
          {topic:"Deberes G8",cat:"A",catLabel:"Derechos",emoji:"⚖️",en:"Right to safe environment",es:"Derecho a un ambiente seguro"},
          {topic:"Deberes G8",cat:"A",catLabel:"Derechos",emoji:"⚖️",en:"Right to fair treatment",es:"Derecho a un trato justo"},
          {topic:"Deberes G8",cat:"A",catLabel:"Derechos",emoji:"⚖️",en:"Right to quality education",es:"Derecho a educación de calidad"},
          {topic:"Deberes G8",cat:"B",catLabel:"Deberes",emoji:"📋",en:"Attend class regularly",es:"Asistir a clase regularmente"},
          {topic:"Deberes G8",cat:"B",catLabel:"Deberes",emoji:"📋",en:"Respect teachers and classmates",es:"Respetar profesores y compañeros"},
          {topic:"Deberes G8",cat:"B",catLabel:"Deberes",emoji:"📋",en:"Complete your homework",es:"Completar la tarea"},
          {topic:"Deberes G8",cat:"B",catLabel:"Deberes",emoji:"📋",en:"Follow school rules",es:"Seguir las normas del colegio"},
          {topic:"Deberes G8",cat:"B",catLabel:"Deberes",emoji:"📋",en:"Take care of school property",es:"Cuidar los bienes del colegio"},
          {topic:"Deberes G8",cat:"B",catLabel:"Deberes",emoji:"📋",en:"Be punctual",es:"Ser puntual"},
          {topic:"Deberes G8",cat:"B",catLabel:"Deberes",emoji:"📋",en:"Participate actively",es:"Participar activamente"},
          {topic:"Deberes G8",cat:"B",catLabel:"Deberes",emoji:"📋",en:"Keep the school clean",es:"Mantener el colegio limpio"},
        ],
        games:["wordsearch","hangman","matching","scramble"],
        resources:[
          {title:"British Council — Rights & Responsibilities",desc:"Derechos y deberes estudiantiles",url:"https://learnenglish.britishcouncil.org/"},
          {title:"Canva — School Rights Poster",desc:"Poster de derechos estudiantiles",url:"https://www.canva.com/posters/"},
          {title:"Mentimeter — Class Discussion",desc:"Debate sobre derechos y deberes",url:"https://www.mentimeter.com/"},
        ],
      },
      {
        id:"g8-sep-p4-s2", topic:"The Model Citizen", fecha:"21 – 27 sep",
        vocab:[
          {topic:"Ciudadano G8",cat:"A",catLabel:"Valores",emoji:"🌟",en:"Honest",es:"Honesto/a"},
          {topic:"Ciudadano G8",cat:"A",catLabel:"Valores",emoji:"🌟",en:"Responsible",es:"Responsable"},
          {topic:"Ciudadano G8",cat:"A",catLabel:"Valores",emoji:"🌟",en:"Respectful",es:"Respetuoso/a"},
          {topic:"Ciudadano G8",cat:"A",catLabel:"Valores",emoji:"🌟",en:"Empathetic",es:"Empático/a"},
          {topic:"Ciudadano G8",cat:"A",catLabel:"Valores",emoji:"🌟",en:"Cooperative",es:"Cooperativo/a"},
          {topic:"Ciudadano G8",cat:"A",catLabel:"Valores",emoji:"🌟",en:"Tolerant",es:"Tolerante"},
          {topic:"Ciudadano G8",cat:"A",catLabel:"Valores",emoji:"🌟",en:"Committed",es:"Comprometido/a"},
          {topic:"Ciudadano G8",cat:"B",catLabel:"Acciones cívicas",emoji:"🤝",en:"Help your community",es:"Ayuda a tu comunidad"},
          {topic:"Ciudadano G8",cat:"B",catLabel:"Acciones cívicas",emoji:"🤝",en:"Vote when you can",es:"Vota cuando puedas"},
          {topic:"Ciudadano G8",cat:"B",catLabel:"Acciones cívicas",emoji:"🤝",en:"Protect the environment",es:"Protege el medioambiente"},
          {topic:"Ciudadano G8",cat:"B",catLabel:"Acciones cívicas",emoji:"🤝",en:"Report problems responsibly",es:"Reporta problemas responsablemente"},
          {topic:"Ciudadano G8",cat:"B",catLabel:"Acciones cívicas",emoji:"🤝",en:"Respect diversity",es:"Respeta la diversidad"},
          {topic:"Ciudadano G8",cat:"B",catLabel:"Acciones cívicas",emoji:"🤝",en:"Lead by example",es:"Lidera con el ejemplo"},
          {topic:"Ciudadano G8",cat:"B",catLabel:"Acciones cívicas",emoji:"🤝",en:"Think of others first",es:"Piensa primero en los demás"},
          {topic:"Ciudadano G8",cat:"B",catLabel:"Acciones cívicas",emoji:"🤝",en:"Be the change you want to see",es:"Sé el cambio que quieres ver"},
        ],
        games:["matching","scramble","truefalsegame","fillblank"],
        resources:[
          {title:"Canva — Ideal Citizen Poster",desc:"El ciudadano modelo en inglés",url:"https://www.canva.com/posters/"},
          {title:"Mentimeter — Values Poll",desc:"Encuesta de valores cívicos",url:"https://www.mentimeter.com/"},
          {title:"Google Forms — Citizenship Reflection",desc:"Reflexión sobre ciudadanía",url:"https://forms.google.com/"},
        ],
      },
      {
        id:"g8-oct-s1", topic:"Modal Verbs: may, might", fecha:"28 sep – 4 oct",
        vocab:[
          {topic:"May Might G8",cat:"A",catLabel:"Posibilidad",emoji:"🎲",en:"It may rain today",es:"Puede que llueva hoy"},
          {topic:"May Might G8",cat:"A",catLabel:"Posibilidad",emoji:"🎲",en:"She might be late",es:"Ella podría llegar tarde"},
          {topic:"May Might G8",cat:"A",catLabel:"Posibilidad",emoji:"🎲",en:"They may not come",es:"Puede que ellos no vengan"},
          {topic:"May Might G8",cat:"A",catLabel:"Posibilidad",emoji:"🎲",en:"It might snow tomorrow",es:"Podría nevar mañana"},
          {topic:"May Might G8",cat:"A",catLabel:"Posibilidad",emoji:"🎲",en:"He may be right",es:"Puede que él tenga razón"},
          {topic:"May Might G8",cat:"A",catLabel:"Posibilidad",emoji:"🎲",en:"She might not know the answer",es:"Ella podría no saber la respuesta"},
          {topic:"May Might G8",cat:"A",catLabel:"Posibilidad",emoji:"🎲",en:"We may go to the beach",es:"Puede que vayamos a la playa"},
          {topic:"May Might G8",cat:"B",catLabel:"En contexto",emoji:"📝",en:"I may be wrong about this",es:"Puede que esté equivocado/a"},
          {topic:"May Might G8",cat:"B",catLabel:"En contexto",emoji:"📝",en:"She might have left already",es:"Ella podría ya haberse ido"},
          {topic:"May Might G8",cat:"B",catLabel:"En contexto",emoji:"📝",en:"They may not understand",es:"Puede que ellos no entiendan"},
          {topic:"May Might G8",cat:"B",catLabel:"En contexto",emoji:"📝",en:"It might get better soon",es:"Podría mejorar pronto"},
          {topic:"May Might G8",cat:"B",catLabel:"En contexto",emoji:"📝",en:"May I come in?",es:"¿Puedo entrar? (permiso)"},
          {topic:"May Might G8",cat:"B",catLabel:"En contexto",emoji:"📝",en:"You might need an umbrella",es:"Podrías necesitar un paraguas"},
          {topic:"May Might G8",cat:"B",catLabel:"En contexto",emoji:"📝",en:"She may be at home",es:"Puede que ella esté en casa"},
          {topic:"May Might G8",cat:"B",catLabel:"En contexto",emoji:"📝",en:"I might try that later",es:"Podría intentar eso más tarde"},
        ],
        games:["wordsearch","hangman","matching","scramble"],
        resources:[
          {title:"British Council — May and Might",desc:"Verbos modales may y might",url:"https://learnenglish.britishcouncil.org/grammar/intermediate-to-upper-intermediate/modal-verbs"},
          {title:"ESL Games Plus — May/Might",desc:"Juego de may y might",url:"https://www.eslgamesplus.com/"},
          {title:"Kahoot — May Might Quiz",desc:"Quiz de may y might G8",url:"https://kahoot.com/schools-u/"},
        ],
      },
      {
        id:"g8-oct-s2", topic:"Modal verbs: should, must, have to", fecha:"12 – 18 oct",
        vocab:[
          {topic:"Should Must G8",cat:"A",catLabel:"Should",emoji:"💡",en:"You should study more",es:"Deberías estudiar más"},
          {topic:"Should Must G8",cat:"A",catLabel:"Should",emoji:"💡",en:"She shouldn't eat junk food",es:"Ella no debería comer chatarra"},
          {topic:"Should Must G8",cat:"A",catLabel:"Should",emoji:"💡",en:"Should I call him?",es:"¿Debería llamarlo?"},
          {topic:"Should Must G8",cat:"A",catLabel:"Should",emoji:"💡",en:"We should leave now",es:"Deberíamos irnos ahora"},
          {topic:"Should Must G8",cat:"A",catLabel:"Should",emoji:"💡",en:"You should see a doctor",es:"Deberías ver un médico"},
          {topic:"Should Must G8",cat:"A",catLabel:"Should",emoji:"💡",en:"They shouldn't be rude",es:"No deberían ser groseros"},
          {topic:"Should Must G8",cat:"A",catLabel:"Should",emoji:"💡",en:"Should we bring food?",es:"¿Deberíamos llevar comida?"},
          {topic:"Should Must G8",cat:"B",catLabel:"Must / Have to",emoji:"⚡",en:"You must wear a seatbelt",es:"Debes usar cinturón"},
          {topic:"Should Must G8",cat:"B",catLabel:"Must / Have to",emoji:"⚡",en:"She must study harder",es:"Ella debe estudiar más"},
          {topic:"Should Must G8",cat:"B",catLabel:"Must / Have to",emoji:"⚡",en:"You mustn't smoke here",es:"No debes fumar aquí"},
          {topic:"Should Must G8",cat:"B",catLabel:"Must / Have to",emoji:"⚡",en:"I have to go now",es:"Tengo que irme ahora"},
          {topic:"Should Must G8",cat:"B",catLabel:"Must / Have to",emoji:"⚡",en:"She doesn't have to come",es:"Ella no tiene que venir"},
          {topic:"Should Must G8",cat:"B",catLabel:"Must / Have to",emoji:"⚡",en:"Do you have to work today?",es:"¿Tienes que trabajar hoy?"},
          {topic:"Should Must G8",cat:"B",catLabel:"Must / Have to",emoji:"⚡",en:"Must I wear a uniform?",es:"¿Debo usar uniforme?"},
          {topic:"Should Must G8",cat:"B",catLabel:"Must / Have to",emoji:"⚡",en:"We have to finish by Friday",es:"Tenemos que terminar para el viernes"},
        ],
        games:["matching","scramble","truefalsegame","fillblank"],
        resources:[
          {title:"British Council — Should Must Have to",desc:"Modales de obligación y consejo",url:"https://learnenglish.britishcouncil.org/grammar/intermediate-to-upper-intermediate/modal-verbs"},
          {title:"ESL Games Plus — Must/Should",desc:"Juego de must y should",url:"https://www.eslgamesplus.com/"},
          {title:"Wordwall — Should Must Have to",desc:"Actividades de modales de obligación",url:"https://wordwall.net/"},
        ],
      },
      {
        id:"g8-oct-s3", topic:"Present Perfect (Structure)", fecha:"19 – 25 oct",
        vocab:[
          {topic:"Presente perfecto estructura G8",cat:"A",catLabel:"Afirmativo",emoji:"✅",en:"I have visited Bogotá",es:"He visitado Bogotá"},
          {topic:"Presente perfecto estructura G8",cat:"A",catLabel:"Afirmativo",emoji:"✅",en:"She has finished her project",es:"Ella ha terminado su proyecto"},
          {topic:"Presente perfecto estructura G8",cat:"A",catLabel:"Afirmativo",emoji:"✅",en:"They have lived here for years",es:"Ellos han vivido aquí por años"},
          {topic:"Presente perfecto estructura G8",cat:"A",catLabel:"Afirmativo",emoji:"✅",en:"We have learned a lot",es:"Hemos aprendido mucho"},
          {topic:"Presente perfecto estructura G8",cat:"A",catLabel:"Afirmativo",emoji:"✅",en:"He has eaten already",es:"Él ya ha comido"},
          {topic:"Presente perfecto estructura G8",cat:"A",catLabel:"Afirmativo",emoji:"✅",en:"I have worked here since 2020",es:"He trabajado aquí desde 2020"},
          {topic:"Presente perfecto estructura G8",cat:"A",catLabel:"Afirmativo",emoji:"✅",en:"She has won three prizes",es:"Ella ha ganado tres premios"},
          {topic:"Presente perfecto estructura G8",cat:"B",catLabel:"Negativo e interrogativo",emoji:"❓",en:"I haven't seen that film",es:"No he visto esa película"},
          {topic:"Presente perfecto estructura G8",cat:"B",catLabel:"Negativo e interrogativo",emoji:"❓",en:"Has she called yet?",es:"¿Ella ha llamado ya?"},
          {topic:"Presente perfecto estructura G8",cat:"B",catLabel:"Negativo e interrogativo",emoji:"❓",en:"Have you ever been abroad?",es:"¿Alguna vez has estado en el exterior?"},
          {topic:"Presente perfecto estructura G8",cat:"B",catLabel:"Negativo e interrogativo",emoji:"❓",en:"They haven't arrived yet",es:"Ellos todavía no han llegado"},
          {topic:"Presente perfecto estructura G8",cat:"B",catLabel:"Negativo e interrogativo",emoji:"❓",en:"How long have you lived here?",es:"¿Cuánto tiempo has vivido aquí?"},
          {topic:"Presente perfecto estructura G8",cat:"B",catLabel:"Negativo e interrogativo",emoji:"❓",en:"Have they finished?",es:"¿Ellos han terminado?"},
          {topic:"Presente perfecto estructura G8",cat:"B",catLabel:"Negativo e interrogativo",emoji:"❓",en:"She hasn't eaten lunch",es:"Ella no ha almorzado"},
          {topic:"Presente perfecto estructura G8",cat:"B",catLabel:"Negativo e interrogativo",emoji:"❓",en:"I have never tried sushi",es:"Nunca he probado sushi"},
        ],
        games:["wordsearch","hangman","matching","scramble"],
        resources:[
          {title:"British Council — Present Perfect",desc:"Presente perfecto nivel intermedio",url:"https://learnenglish.britishcouncil.org/grammar/intermediate-to-upper-intermediate/present-perfect"},
          {title:"ESL Games Plus — Present Perfect",desc:"Juego del presente perfecto",url:"https://www.eslgamesplus.com/"},
          {title:"Quizlet — Present Perfect G8",desc:"Flashcards del presente perfecto",url:"https://quizlet.com/"},
        ],
      },
      {
        id:"g8-oct-s4", topic:"Present Perfect (already, yet, just, ever)", fecha:"26 oct – 1 nov",
        vocab:[
          {topic:"Perfecto adverbios G8",cat:"A",catLabel:"Already / Yet",emoji:"✅",en:"I have already done it",es:"Ya lo he hecho"},
          {topic:"Perfecto adverbios G8",cat:"A",catLabel:"Already / Yet",emoji:"✅",en:"She has already eaten",es:"Ella ya ha comido"},
          {topic:"Perfecto adverbios G8",cat:"A",catLabel:"Already / Yet",emoji:"✅",en:"Have you finished yet?",es:"¿Has terminado ya?"},
          {topic:"Perfecto adverbios G8",cat:"A",catLabel:"Already / Yet",emoji:"✅",en:"I haven't called yet",es:"Todavía no he llamado"},
          {topic:"Perfecto adverbios G8",cat:"A",catLabel:"Already / Yet",emoji:"✅",en:"Has he eaten yet?",es:"¿Él ha comido ya?"},
          {topic:"Perfecto adverbios G8",cat:"A",catLabel:"Already / Yet",emoji:"✅",en:"We have already left",es:"Ya nos hemos ido"},
          {topic:"Perfecto adverbios G8",cat:"A",catLabel:"Already / Yet",emoji:"✅",en:"They haven't arrived yet",es:"Ellos todavía no han llegado"},
          {topic:"Perfecto adverbios G8",cat:"B",catLabel:"Just / Ever / Never",emoji:"⏱️",en:"I have just arrived",es:"Acabo de llegar"},
          {topic:"Perfecto adverbios G8",cat:"B",catLabel:"Just / Ever / Never",emoji:"⏱️",en:"She has just finished",es:"Ella acaba de terminar"},
          {topic:"Perfecto adverbios G8",cat:"B",catLabel:"Just / Ever / Never",emoji:"⏱️",en:"Have you ever tried it?",es:"¿Alguna vez lo has probado?"},
          {topic:"Perfecto adverbios G8",cat:"B",catLabel:"Just / Ever / Never",emoji:"⏱️",en:"I have never been to Europe",es:"Nunca he estado en Europa"},
          {topic:"Perfecto adverbios G8",cat:"B",catLabel:"Just / Ever / Never",emoji:"⏱️",en:"Has she ever won a prize?",es:"¿Ella alguna vez ha ganado un premio?"},
          {topic:"Perfecto adverbios G8",cat:"B",catLabel:"Just / Ever / Never",emoji:"⏱️",en:"He has just called",es:"Él acaba de llamar"},
          {topic:"Perfecto adverbios G8",cat:"B",catLabel:"Just / Ever / Never",emoji:"⏱️",en:"We have never met before",es:"Nunca nos habíamos conocido"},
          {topic:"Perfecto adverbios G8",cat:"B",catLabel:"Just / Ever / Never",emoji:"⏱️",en:"They have just started",es:"Ellos acaban de empezar"},
        ],
        games:["matching","scramble","truefalsegame","fillblank"],
        resources:[
          {title:"British Council — Already Yet Just",desc:"Adverbios con el presente perfecto",url:"https://learnenglish.britishcouncil.org/"},
          {title:"ESL Games Plus — Perfect Adverbs",desc:"Juego del presente perfecto con adverbios",url:"https://www.eslgamesplus.com/"},
          {title:"Wordwall — Already Yet Just Ever",desc:"Actividades con already/yet/just/ever",url:"https://wordwall.net/"},
        ],
      },
    ],
    10: [ // Noviembre — G8 — P4 cierre
      {
        id:"g8-nov-s1", topic:"Integrated Practice: Modals and Present Perfect", fecha:"2 – 8 nov",
        vocab:[
          {topic:"Integración P4 G8",cat:"A",catLabel:"Gramática integrada",emoji:"✨",en:"She might have already left",es:"Puede que ella ya se haya ido"},
          {topic:"Integración P4 G8",cat:"A",catLabel:"Gramática integrada",emoji:"✨",en:"You should have studied more",es:"Deberías haber estudiado más"},
          {topic:"Integración P4 G8",cat:"A",catLabel:"Gramática integrada",emoji:"✨",en:"Have you ever used modal verbs?",es:"¿Alguna vez has usado verbos modales?"},
          {topic:"Integración P4 G8",cat:"A",catLabel:"Gramática integrada",emoji:"✨",en:"She must have forgotten",es:"Ella debe de haber olvidado"},
          {topic:"Integración P4 G8",cat:"A",catLabel:"Gramática integrada",emoji:"✨",en:"I have just finished my homework",es:"Acabo de terminar mi tarea"},
          {topic:"Integración P4 G8",cat:"A",catLabel:"Gramática integrada",emoji:"✨",en:"You mustn't forget your ID",es:"No debes olvidar tu identificación"},
          {topic:"Integración P4 G8",cat:"A",catLabel:"Gramática integrada",emoji:"✨",en:"Have they arrived yet?",es:"¿Ya llegaron ellos?"},
          {topic:"Integración P4 G8",cat:"B",catLabel:"Ciudadanía",emoji:"🤝",en:"A good citizen is responsible",es:"Un buen ciudadano es responsable"},
          {topic:"Integración P4 G8",cat:"B",catLabel:"Ciudadanía",emoji:"🤝",en:"You should respect others",es:"Deberías respetar a los demás"},
          {topic:"Integración P4 G8",cat:"B",catLabel:"Ciudadanía",emoji:"🤝",en:"We must protect our rights",es:"Debemos proteger nuestros derechos"},
          {topic:"Integración P4 G8",cat:"B",catLabel:"Ciudadanía",emoji:"🤝",en:"I have already voted",es:"Ya voté"},
          {topic:"Integración P4 G8",cat:"B",catLabel:"Ciudadanía",emoji:"🤝",en:"She may become a leader",es:"Puede que ella se convierta en líder"},
          {topic:"Integración P4 G8",cat:"B",catLabel:"Ciudadanía",emoji:"🤝",en:"They have never disrespected anyone",es:"Ellos nunca han faltado el respeto a nadie"},
          {topic:"Integración P4 G8",cat:"B",catLabel:"Ciudadanía",emoji:"🤝",en:"I have to be a good citizen",es:"Tengo que ser un buen ciudadano"},
          {topic:"Integración P4 G8",cat:"B",catLabel:"Ciudadanía",emoji:"🤝",en:"We should lead by example",es:"Deberíamos liderar con el ejemplo"},
        ],
        games:["wordsearch","hangman","matching","scramble"],
        resources:[
          {title:"Kahoot — Modales + Presente Perfecto",desc:"Quiz integrado de modales y presente perfecto",url:"https://kahoot.com/schools-u/"},
          {title:"Quizlet — G8 P4 Integrated Review",desc:"Repaso integrado cuarto período G8",url:"https://quizlet.com/"},
          {title:"Canva — My Rights and Duties Card",desc:"Tarjeta de derechos y deberes",url:"https://www.canva.com/"},
        ],
      },
      {
        id:"g8-nov-s2", topic:"Final Assessment for the Term", fecha:"9 – 15 nov", badge:"Evaluación",
        vocab:[
          {topic:"Evaluación Final G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"I have already finished",es:"Ya he terminado"},
          {topic:"Evaluación Final G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"She might not come tomorrow",es:"Puede que ella no venga mañana"},
          {topic:"Evaluación Final G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"You must follow the rules",es:"Debes seguir las reglas"},
          {topic:"Evaluación Final G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"Have they ever visited Colombia?",es:"¿Ellos alguna vez han visitado Colombia?"},
          {topic:"Evaluación Final G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"She is going to be a scientist",es:"Ella va a ser científica"},
          {topic:"Evaluación Final G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"You should respect diversity",es:"Deberías respetar la diversidad"},
          {topic:"Evaluación Final G8",cat:"A",catLabel:"Gramática",emoji:"📝",en:"It will rain next weekend",es:"Lloverá el próximo fin de semana"},
          {topic:"Evaluación Final G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"Just arrived",es:"Acaba de llegar"},
          {topic:"Evaluación Final G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"Mustn't smoke",es:"No debe fumar"},
          {topic:"Evaluación Final G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"Have to finish",es:"Tienen que terminar"},
          {topic:"Evaluación Final G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"May be right",es:"Puede que tenga razón"},
          {topic:"Evaluación Final G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"Haven't called yet",es:"Todavía no ha llamado"},
          {topic:"Evaluación Final G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"Empathetic citizen",es:"Ciudadano/a empático/a"},
          {topic:"Evaluación Final G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"Won't be late",es:"No llegará tarde"},
          {topic:"Evaluación Final G8",cat:"B",catLabel:"Vocabulario",emoji:"📚",en:"Has already eaten",es:"Ya ha comido"},
        ],
        games:["matching","scramble","truefalsegame","fillblank"],
        resources:[
          {title:"Google Forms — Final Exam G8",desc:"Evaluación final grado 8",url:"https://forms.google.com/"},
          {title:"Kahoot — Year Final G8",desc:"Quiz final del año grado 8",url:"https://kahoot.com/schools-u/"},
          {title:"Quizlet — G8 Year Review",desc:"Repaso anual grado 8",url:"https://quizlet.com/"},
        ],
      },
      {
        id:"g8-nov-s3", topic:"Feedback and End-of-Year Wrap-Up", fecha:"16 – 22 nov", badge:"Cierre",
        vocab:[
          {topic:"Cierre G8",cat:"A",catLabel:"Logros",emoji:"🌟",en:"I have improved my English",es:"He mejorado mi inglés"},
          {topic:"Cierre G8",cat:"A",catLabel:"Logros",emoji:"🌟",en:"I have learned new grammar",es:"He aprendido gramática nueva"},
          {topic:"Cierre G8",cat:"A",catLabel:"Logros",emoji:"🌟",en:"I presented in English",es:"Presenté en inglés"},
          {topic:"Cierre G8",cat:"A",catLabel:"Logros",emoji:"🌟",en:"I have grown as a student",es:"He crecido como estudiante"},
          {topic:"Cierre G8",cat:"A",catLabel:"Logros",emoji:"🌟",en:"English opens doors",es:"El inglés abre puertas"},
          {topic:"Cierre G8",cat:"A",catLabel:"Logros",emoji:"🌟",en:"Next year I will focus on",es:"El próximo año me enfocaré en"},
          {topic:"Cierre G8",cat:"A",catLabel:"Logros",emoji:"🌟",en:"I have made fewer mistakes",es:"He cometido menos errores"},
          {topic:"Cierre G8",cat:"B",catLabel:"Despedida",emoji:"👋",en:"It has been a great year",es:"Ha sido un gran año"},
          {topic:"Cierre G8",cat:"B",catLabel:"Despedida",emoji:"👋",en:"See you in 9th grade",es:"Nos vemos en noveno"},
          {topic:"Cierre G8",cat:"B",catLabel:"Despedida",emoji:"👋",en:"Keep practising English",es:"Sigan practicando inglés"},
          {topic:"Cierre G8",cat:"B",catLabel:"Despedida",emoji:"👋",en:"You have all improved so much",es:"Todos han mejorado muchísimo"},
          {topic:"Cierre G8",cat:"B",catLabel:"Despedida",emoji:"👋",en:"Thank you for everything",es:"Gracias por todo"},
          {topic:"Cierre G8",cat:"B",catLabel:"Despedida",emoji:"👋",en:"Have a wonderful vacation",es:"Que tengan unas vacaciones maravillosas"},
          {topic:"Cierre G8",cat:"B",catLabel:"Despedida",emoji:"👋",en:"Come back ready to learn",es:"Regresen listos para aprender"},
          {topic:"Cierre G8",cat:"B",catLabel:"Despedida",emoji:"👋",en:"You should be proud of yourselves",es:"Deberían estar orgullosos de ustedes mismos"},
        ],
        games:["wordsearch","hangman","matching","scramble"],
        resources:[
          {title:"Canva — Year End Card G8",desc:"Carta de cierre del año grado 8",url:"https://www.canva.com/cards/"},
          {title:"Flipgrid — Reflection Video G8",desc:"Video de reflexión del año",url:"https://info.flip.com/"},
          {title:"Google Forms — Year Self-Assessment G8",desc:"Autoevaluación final grado 8",url:"https://forms.google.com/"},
        ],
      },
    ],
  };

  export default g8;
